### ISSUE TITLE
WebUI: ERR_CONNECTION_TIMED_OUT after most requests but sickrage service is up and running

### ISSUE THREAD

**Issue by KaputtZimon** [SickChill/SickChill#3722]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: e1af3a8af8da
OS: FreeNAS-9.10.2-U1
What you did: Trying to access the web interface
What happened: I received a ERR_CONNECTION_TIMED_OUT
What you expected: No timeout
Logs:
I did not find logs regarding the webui. There are no errors in /var/db/sickrage/Sickrage/Logs

I have this issue for a while now but since sickrage is still running and working I did not address this issue. 
The behaviour is often (but not always) like this. I can access the sickrage webui (any url like /home or /showlist) but then the second request I do is always a time out. After waiting a few minutes I can do another request and then the next times out again.

But sometimes it works for a few request and then stopped working completely. Adding a new show is basically impossible. I tried different browsers and I have the feeling that Safari is worse than Chrome. But also on chrome is does not work.
I did not find any logs regarding the webUI, are there any?

**Comment by sharkykh** [comment]
@KaputtZimon 

> I did not find any logs regarding the webUI, are there any?

The only thing I can think of is you can enable debug logging + Tornado logging:
* Debug: General Configuration > Advanced Settings > Enable debug logs
* HTTP logs: General Configuration > Interface > Web Interface > HTTP logs

(Then wait for it to happen again and check the logs)

**Comment by KaputtZimon** [comment]
Are the http logs also written to /var/db/sickrage/Logs?
If so, there is nothing...

**Comment by sharkykh** [comment]
@KaputtZimon Yes, they do

Perhaps some kind of firewall issue?

**Comment by andofrjando** [comment]
SickRage times out for me when I try and use the web interface, but the service is up and running. It's weird - NZBToMedia also times out, but I ping the API endpoint sb.ping every 30 seconds with Monit to make sure everything is ok and it responds fine. The service itself is running fine, because it snatches shows and sends them to SAB.
My sickrage log (with debug + tornado log) is here: https://gist.github.com/andofrjando/8f603304ccd3e31a7e4b6a5aa27fca29
From about 30 seconds into this log, the web ui is trying to load a show page.


Below is the log from NZBtoMedia being run from Sab after sickrage snatched something and the corresponding sickrage.log from the same period is here https://gist.github.com/andofrjando/69f8a8ae7e25b09ae7984f3575a13411:

```
[08:40:14] [INFO]::MAIN: Loading config from [/opt/nzbToMedia/autoProcessMedia.cfg]
[08:40:14] [INFO]::MAIN: Checking database structure...
[08:40:14] [INFO]::MAIN: Checking if git needs an update
[08:40:15] [INFO]::MAIN: No update needed
[08:40:15] [INFO]::MAIN: nzbToMedia Version:80c8ad58523ab99825c02f3855f9bd3dc9945d57 Branch:master (Linux 4.4.0-78-generic)
[08:40:15] [INFO]::MAIN: #########################################################
[08:40:15] [INFO]::MAIN: ## ..::[nzbToMedia.py]::.. ##
[08:40:15] [INFO]::MAIN: #########################################################
[08:40:15] [INFO]::MAIN: Script triggered from SABnzbd
[08:40:16] [INFO]::MAIN: Auto-detected SECTION:SickBeard
[08:40:16] [INFO]::MAIN: Calling SickBeard:tv to post-process:Bobs.Burgers.S07E21.720p.HDTV.x264-AVS.nzb
[08:42:16] [ERROR]::SERVER: Server failed to respond at http://localhost:8081
[08:42:16] [ERROR]::SICKBEARD: Server did not respond. Exiting
[08:42:16] [ERROR]::MAIN: A problem was reported in the /var/lib/sabnzbd/scripts/nzbToMedia.py script.
SickBeard: Failed to post-process - SickBeard did not respond.!
```


My set up is a little different from the OPs:
Ubuntu 16.04.01
Sickrage commit `f5278dee021f52ef2529fdca3a9787a97249a22a`
Running behind NGINX reverse proxy (except for calls to localhost/127.0.0.1:8081 obviously)

**Comment by sharkykh** [comment]
@andofrjando just to make sure, let's say `https` is disabled for SickRage, the url you're trying to load is an `http` one, correct? (Also the other way around if `https` is enabled)

**Comment by KaputtZimon** [comment]
Well I did not figure it out yet because I need more different machines to verify the problem.
I could reproduce the behaviour I described with 2 laptops (both are connected via wifi) and an iPad.
When I try to access the webui via a windows desktop machine (ethernet) it works perfect. Furthermore whenever I have a timeout on a laptop and I go to the window machine and load the webui, the timeout on the laptop stops and it works there as well.

I also try switching the wifi without any difference. I try to get a usb to ethernet adapter so I can check if the problem is somehow only wifi related..

**Comment by sharkykh** [comment]
@KaputtZimon This sounds to me like SickRage is not allowed through the firewall.
(I also had this when I first installed SR, couldn't access it from my phone.)

**Comment by andofrjando** [comment]
@sharkykh Thanks for your response. In regards to your first question - definitely only running over http, not https, and the reverse proxy is connecting to the correct port 8081. I double checked in the settings.
Your second question, I will run it from the shell and leave it for a few days. The problem is not occurring at the moment, and mostly seems to running ok. Maybe related, but when I run from the shell and try an access a show page, I see the following get logged:
```
16:06:58 DEBUG::Thread-14 :: Looking up XEM scene mapping for show 71663 on theTVDB
16:07:28 INFO::Thread-14 :: Request failed: HTTPConnectionPool(host='thexem.de', port=80): Max retries exceeded with url: /map/havemap?origin=tvdb (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7ffb5005f3d0>, 'Connection to thexem.de timed out. (connect timeout=30)'))
16:07:56 DEBUG::Thread-14 :: Looking up XEM scene mapping for show 277165 on theTVDB
16:08:26 INFO::Thread-14 :: Request failed: HTTPConnectionPool(host='thexem.de', port=80): Max retries exceeded with url: /map/havemap?origin=tvdb (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x7ffb700a2a90>, 'Connection to thexem.de timed out. (connect timeout=30)'))
```

The Web UI hangs for a bit when the first line gets logged, (`Looking up XEM scene mapping`), then when it times out (`Request failed: HTTPConnectionPool(host='thexem.de', port=80)`), the page loads. I wonder: if thexem.de sent only a partial response and the timeout never occurs if this would cause the type of symptoms being reported.

**Comment by mgaulton** [comment]
Any progress on this. I've been noticing something similar, that seems like it resolves itself over time. I haven't been able to find anything in the logs that jumped out at me but its breaking my nzbToMedia processing, so i'm a bit concerned.
