### ISSUE TITLE
Add support for betaseries.com as subtitle providers

### ISSUE THREAD

**Issue by zaibon** [SickChill/SickChill#3730]
I would like to add the support of [betaseries](https://www.betaseries.com) to the list of subtitle providers. 
I'm willing to work on it myself. Is there any documentation about the interface I should implement as a subtitle provider ?
I had a look  in the `sickrage/providers/subtitle` folder, is `itasa.py` a good example ?

**Comment by sharkykh** [comment]
@zaibon 
Under the hood, we use [Diaoul/subliminal](https://github.com/Diaoul/subliminal) for downloading subtitles, so we don't really add providers in here. You should propose it over there. (though it will probably take some time for it to get merged).

ItaSA was added some time ago,
and I don't think @miigotu would approve such changes now.
(Take a look at https://github.com/SickRage/SickRage/pull/3651#issuecomment-296435609)

**Comment by miigotu** [comment]
We can add providers to SR, since you can register an external provider. 
We use an external provider for itasa in `SickRage/sickrage/providers/subtitle/itasa.py`
and we register that provider with subliminal in `SickRage/sickbeard/subtitles.py`

The comment mentioned above was related to changing the actual subliminal source provided in SR, which is discouraged. We like to keep our 3rd party libs in a vanilla state and provide PR's to them upstream.

**Comment by sharkykh** [comment]
@miigotu sry, I guess I saw an old commit, because the contributor that added itasa did edit the subliminal lib.

**Comment by zaibon** [comment]
Thank you for the clarification, I'll start working on that and send PR when ready.

**Comment by WebSpider** [comment]
Hi @zaibon how is the PR coming?
