### ISSUE TITLE
Multiple torrent names --> Unable to parse the XML

### ISSUE THREAD

**Issue by segator** [SickChill/SickChill#3740]
Branch/Commit: b5b2262ad0acfd0ca679b1964950a147dfc5e193
OS: Docker Linux UnRaid
What you did: search tvshow from sickrage
What happened: notthing
What you expected:  download a expected torrent.
Logs:
```
2017-05-10 17:57:59 SEARCHQUEUE-BACKLOG-302205 :: [jackett-myaccount] :: [b5b2262] Unable to parse the XML of victoria..S01.[1080i.hdtv][dual+subs][grupo.hdt.series], not splitting it
2017-05-10 17:13:42 SEARCHQUEUE-BACKLOG-308110 :: [jackett-myaccount] :: [b5b2262] Unable to parse the XML of stag..S01.[1080i.hdtv][dual+sub][grupo.hdt.series], not splitting it
```
I expected sickrage download a torrent with this name
 [Pack]Victoria S01 [1080i HDTV][Dual+Subs][Grupo HDT Series]

but I get this warning [b5b2262] Unable to parse the XML of victoria..S01.[1080i.hdtv][dual+subs][grupo.hdt.series], not splitting it

**Comment by sharkykh** [comment]
@segator 
I think it fails because of the double-dot in the names:
```
victoria..S01
stag..S01
```

So IMO, the naming is wrong. We won't change the naming RegExp because it can cause issues for other release names.

Since you're using jackett and not one of the providers embedded in SR,
I'm not sure I can help you with this issue.

If there's a way in jackett to tweak the names and remove the extra dot, do that.
That should fix your issue.

**Comment by sharkykh** [comment]
@segator I see that you're using jackett... What did you put in the custom provider you created?

**Comment by segator** [comment]
Hi, there aren't any point in the names, it seems I guess sickrage change spaces to points.
about the provider options..
enable provider to perform daily searches. checked 
enable provider to perform backlog searches. checked 

season packs only. checked
Enable fallback. checked

It's important to say that it works almost all the time but specific torrent names seems get this error.

**Comment by sharkykh** [comment]
I removed my comment about the dots because it was incorrect.

The fact that it's working most of the time tells me that the error may rely in the feed created by Jackett (this is how it works, correct?) or the actual providers you're using from/in Jackett.

Maybe the specific torrents are corrupted?
Is there something in common for all the torrents that you get this error on?
Maybe.. all are season packs?

**Comment by segator** [comment]
I am 90% sure it's problem related with the torrent name, because this torrent is never downloaded, I suppose sickrage when search find out this torrent but didn't like the name and throw this error.

**Comment by sharkykh** [comment]
After some more digging, it seems to me like you added the provider as a custom **NZB** provider instead of an custom **Torrent/RSS** provider?

**Comment by segator** [comment]
Yes, exactly, Jackett is compatible with backlog search, but it seems torrent options it isn't so I added as a NZB provider

**Comment by sharkykh** [comment]
Then there's the root of your issue.
NZBs are treated differently than torrents. The custom NZB provider is based on the Newznab protocol, the custom torrent provider is based on RSS feeds, that's why it doesn't have and can't have backlog search capabilities.

It's trying to do something you can only do with an NZB on a torrent file and thats why it fails.

P.S.
I'm very surprised it worked for you thus far...

**Comment by segator** [comment]
I don't understand,
I downloaded more than 300 torrents sucessfully using this method. Which difference have this torrent to not be able to download and get this error? could we someway debug what is going on?
May be a problem related with jackett that doesn't send all the necesary data to be processed by sickrage in some  single cases like what i mentioned in my first message?

**Comment by sharkykh** [comment]
> I don't understand,
> I downloaded more than 300 torrents sucessfully using this method. Which difference have this torrent to not be able to download and get this error? could we someway debug what is going on?

I'm debugging by reading the code ([important part is this](https://github.com/SickRage/SickRage/blob/599431d9c5a99ad57512c2e84c54ff15bb493a88/sickbeard/search.py#L578-L609))

Okay, so, basically...
Up to now, you probably downloaded torrents that contained only one episode or (possibly) a season pack that **all the episodes it contains** are set to Wanted in your SickRage database.

The problem occurs when the picked search result contains a season pack,
but you **don't have all of the episodes it contains** set to Wanted.

In order to only add the desired episodes to the NZB client,
it tries to **split the NZB file** which basically [a XML file](https://en.wikipedia.org/wiki/NZB#File_format_example),
but instead it receives a torrent file, which is [a binary file](https://en.wikipedia.org/wiki/Torrent_file#File_structure).
It can't split it using the same method used for NZBs, completely different file types.
And even more so, SR doesn't support splitting season packs for torrent clients.

***

> May be a problem related with jackett that doesn't send all the necesary data to be processed by sickrage in some single cases like what i mentioned in my first message?

I don't think so anymore as I explained above.
Jackett works fine,
I just don't think SickRage is designed for this kind of use (creating a torrents provider as an NZB provider)

**Comment by sharkykh** [comment]
@segator 
As a workaround, to avoid this warning, you can **disable searching for season packs**
(in the provider config set to episodes only and disable the fallback)
It will cause you to download more torrents of single episodes,
but only when you're searching for multiple episodes of the same season, or complete series.
