### ISSUE TITLE
Search frequency values not being honored

### ISSUE THREAD

**Issue by rEes9P** [SickChill/SickChill#3792]
**Branch/Commit:** master/f5278dee021f52ef2529fdca3a9787a97249a22a

**OS:** OS X 10.12.5

**What you did:** I want to use SickRage for post-processing alone and not to snatch NZB files, for which I use another service. I have set backlog search days = 1 days, Backlog search frequency = 21024021 minutes (40 years), Daily search frequency = 10512007 minutes (20 years), Usenet retention = 1 day and set the send nzb option to Black hole. I haven't disabled NZB search providers as that brings up a notification each time.

**What happened:** SickRage sporadically snatches NZB files.

**What you expected:** I expected that the very high search frequency values (in multiple years) would prevent SickRage from snatching NZB files.

**Comment by sharkykh** [comment]
Don't know exactly why that is but you should check the logs and manually check the config file after a save and after a restart.

If I was in your shoes,
I would've just paused all of the shows using the Mass Update table.
That should stop all types of searches, since pauses shows aren't being searched.
Not sure if it affects other aspects of SR... Probably **not** the Post-Processor, but maybe the automatic show refresh...
