### ISSUE TITLE
Add TV Show 'sort by' "Last Episode"

### ISSUE THREAD

**Issue by himpich** [SickChill/SickChill#3805]
I really love the TV Show overview and sorting for "next episode" - but a "sort by last episode [aired]" would make it perfect. 

Thanks in advance

**Comment by sharkykh** [comment]
For now, this sort option is only available for the other layouts of the home page (the ones that contain tables).

**Comment by Gitarski** [comment]
I think this is not an "issue" but is a feature request to add sort by Last or Previous episode in the Poster layout as sort by Previous episode is available in all other layouts.

Isn't this only for issues and not feature requests?  Aren't feature requests supposed to be entered at http://feathub.com/SickRage/SickRage instead of here?
