### ISSUE TITLE
Differentiate WEB-DL vs WEBRIP in Custom Quality 

### ISSUE THREAD

**Issue by pyrodex** [SickChill/SickChill#3866]
I know in the past there have been discussions around this but I think this needs to be looked at much closer now since WEBRIPs in some cases are better than WEB-DL due to the recent DRM removal methods. A few great examples of this in terms of shows would be as follows but not limited too:

Fargo
iZombie
Better Call Saul

Yes there are times when WEB-DLs are still provided via their older methods but around the same time or shortly after WEBRIPs are hitting of greater quality making it harder to put either or before one another. 

I personally work around this with release requirement settings in advanced for shows I know have superior WEBRIPs vs WEB-DLs but it would be nice to have an Custom Quality still to leverage for integration factors. For example I have written a SickRage to AUTODL-IRSSI integration using the SR-API and if there was a custom quality of WEBRIP it would make it easier to ensure ONLY proper WEBRIPs are provided.

**Comment by sharkykh** [comment]
[@miigotu once said...](https://github.com/SickRage/SickRage/issues/3115#issuecomment-280209118) 
>For that "nice feature" it would take hundreds of lines of code changes, because we don't have room for more qualities [...]

Even though this is about a slightly different request, the current answer is the same.

The current quality system is full.
I can't explain it properly because I just don't understand it that well.

What I do understand is that it uses numbers to compare qualities and allowed/prefered preferences.
They're intertwined with one another, and a big refactor is needed to make that system extendable.

**Comment by BenjV** [comment]
If that is the problem then maybe is removing other qualities is an option.
For example nobody uses "RAWHD" so in maybe remove that one, "SD" is also becoming a absolute format. 

Webrip's are fast becoming a major factor.

**Comment by duramato** [comment]
>For example nobody uses "RAWHD" so in maybe remove that one, "SD" is also becoming a absolute format.

That's not quite true
