### ISSUE TITLE
Postprocessing Remote Directory

### ISSUE THREAD

**Issue by mplunkett5** [SickChill/SickChill#4015]
### Before submitting your issue:

Branch/Commit: Master
OS: Windows 10
What you did: Postprocessing of a remote directory added to my PC via WinsshFS
What happened: Failed to correctly the post process. It copied the file with the correct naming convention but with 0kb filesize.
What you expected: To copy the file as per normal.
Logs:
```
AA IOError: [Errno 22] Invalid argument
AA buf = fsrc.read(length)
AA File "C:\SickRage\Python\lib\shutil.py", line 49, in copyfileobj
AA return copyfileobj_orig(fsrc, fdst, length)
AA File "C:\SickRage\SickRage\sickbeard\helpers.py", line 95, in _copyfileobj
AA copyfileobj(fsrc, fdst)
AA File "C:\SickRage\Python\lib\shutil.py", line 84, in copyfile
AA result = function(*args, **kwargs)
AA File "C:\SickRage\SickRage\sickrage\helper\encoding.py", line 41, in ek
AA ek(shutil.copyfile, srcFile, destFile)
AA File "C:\SickRage\SickRage\sickbeard\helpers.py", line 381, in copyFile
AA Traceback (most recent call last):
```

**Comment by OldskoolOrion** [comment]
You know SSH uses UDP? Which is like streaming where dropped packets are no issue and not even checked for since it's pointless. For a true copy, dropped packets however are a big issue, since the CRC check will fail in the end if source <> destination file. Trying to get a webdav-like solution working will give you a lot of trouble unless the connection is ALWAYS rock solid and extremely fast. And even then you will need to tweak the registry since it's not prepared for large files and the timeout settings are too low. And pray basically hoping never a packet will drop.. which is not realistic..   I can only recommend using a protocol not based on UDP - this is not a SickRage issue :-)
