### ISSUE TITLE
Schedule Table shows only first episode of daily recurring shows

### ISSUE THREAD

**Issue by mationic** [SickChill/SickChill#4031]
Branch/Commit: master / d8c2613583ce8b321a5adc9ff70c52e830f224a8
OS: Linux-3.10.0-042stab123.9-x86_64-with-centos-7.3.1611-Core
What you did: Loaded schedule table
What happened: Daily recurring shows are only shown on first day
What you expected:  Every episode of these shows are shown in weekly schedule

This bug occurred a few weeks ago.

**Comment by OldskoolOrion** [comment]
Which show(s) does this happen to and didn't a forced full update resolve the issue for ?
You checked thetvdb.com if they were added correctly there ?

**Comment by mationic** [comment]
Every show that is aired daily. The Daily Show, Colbert, Conan. The episodes are added correctly. I just can't see them in the schedule table anymore (except the next one). Full update didn't help, because the episodes are already added.

**Comment by OldskoolOrion** [comment]
Ok clear answer.. keeping your database and config and pictures, a refresh of the rest should resolve this for you : 1) in Data directory keep sickbeard.db, config.ini, and the backup- cache and logs directory : remove cache.db + failed.db  2) either go the git way to refresh codebase or download master repository as zip file and overwrite your existing files with the ones from the zip file for just the SickRage directory.

the git refresh/reset method :

git remote add upstream https://github.com/SickRage/SickRage.git
git fetch upstream
git checkout master
git branch -u upstream/master
git reset --hard upstream/master
git pull

**Comment by OldskoolOrion** [comment]
I just executed same refresh to test and can confirm that I saw daily show in schedule like you would expect (was already added as existing show i follow)

**Comment by mationic** [comment]
Thanks for your help. Did the steps you suggested. Didn't help unfortunately. The Daily Show has the next 10 episodes listed (as unaired), but still only the next one is shown in the schedule tab. No matter which layout (Poster, Calendar, Banner or List). :(

**Comment by OldskoolOrion** [comment]
In that case you will have to wait for a core developer to help. Unfortunately I'm not deep enough into the sourcecode myself to know all ins and outs.

I think (!! not sure tho !!) that for daily shows they no matter what never go beyond the current week.  My daily show had when I did the update today's and tomorrow's (as last of the week) in calendar-view. When today's got grabbed that went of course, so I am also left with just the one ep this week - as of next week I'm sure all days it gets aired it shows up. I never paid attention to further beyond than that to be honest, but I'm sure 4 eps show up next week for my setup.  At the moment I don't have a Linux setup but only a Windows machine, since my server died of old age.  I'll setup a VM this weekend running CentOS so I can compare 1 on 1 - unless a core developer produces the answer coming days : it might give some more insight if it's an OS related thing (don't think so but cant rule it out either).
Hopefully I have some time as well to look thru the code. Maybe helps you further and knowing the internals never hurt anyone :-)

**Comment by OldskoolOrion** [comment]
I know it's not the fastest help.. actually not any help at all so far.. but I can at least try :-)

**Comment by OldskoolOrion** [comment]
a quick search in the sourcecode at least confirmed that they basically divide future shows in three slices     Today:    today
Soon:     tomorrow till next week
Later:     later than next week
so it's either a bug, where the "Later" part doesn't work as it should, or by design for dailies - that is IF daily shows are treated differently from "regular" weekly shows..  have to look into that as I said

**Comment by mationic** [comment]
It's not a pressing issue, SickRage itself is working. But I can't be the only one with this problem.
You're help is much appreciated.

**Comment by OldskoolOrion** [comment]
You are 100% right... I installed it on CentOS.. but it's on my current Windows install as well actually.. just having 1 show added (Daily show), with just on the cut-off for the week, didn't clearly show it, but adding few more shows (Conan, Colbert, Fallon) makes it abundantly clear. It's not a week by week thing either which I speculated, which could be it, because I can see full seasons for Stranger Things which is still a month away and even the full season 2 of The Crown which is 3 months into the future.
So.. no.. you are not the only one - that's 100% confirmed hehe.

This doesn't solve it yet.. but at least you have peace of mind and are not going crazy :-) I never noticed myself since I only look at the schedule of the current week in calendar view and mainly what is supposed to run the very day that I look at it.

I'm going to find myself an IDE with debugger for Python, so I'm able to step thru the code and see if I can spot who the culprit is.

**Comment by mationic** [comment]
This issue is old, but it's still there. It's pretty obvious too.
Go to schedule and open the calendar layout (for the week). If you have a daily show (like The Daily Show or Colbert) you'll see just the next episode, as if there weren't other episodes this week.
Not sure what "tag me to reopen" tbh :)

**Comment by miigotu** [comment]
It is by design, it is only supposed to show the next episode. Otherwise people with hundreds (or even dozen) of shows would not be able to load the page.

**Comment by mationic** [comment]
Alright, no worries. I'm happy with the way it is. Just want to point out that the first years it wasn't that way. And for what its worth, it had its advantages. If there was a short week in the USA (I'm from Europe), I could see it there. But I can very much live without it ^^
Thanks for your work!
