### ISSUE TITLE
Rarbg search_tvdb fails

### ISSUE THREAD

**Issue by plato79** [SickChill/sickchill#4068]
Branch/Commit: master/ d8c2613583ce8b321a5adc9ff70c52e830f224a8
OS: FreeBSD-11.0-STABLE-amd64-64bit-ELF
What you did: BACKLOG an anime 
What happened: It searched through Rarbg's tvdb index
What you expected: There is a tvdb record for it ( 299506 ). I thought it should find this information.
Logs:
```
2017-09-30 08:31:33 INFO     SEARCHQUEUE-BACKLOG-299506 :: [Rarbg] :: Performing episode search for Chivalry of a Failed Knight
2017-09-30 08:31:35 INFO     SEARCHQUEUE-BACKLOG-299506 :: [Rarbg] :: Cant find search_tvdb in database. Are you sure it exists?
2017-09-30 08:31:37 INFO     SEARCHQUEUE-BACKLOG-299506 :: [Rarbg] :: Cant find search_tvdb in database. Are you sure it exists?
2017-09-30 08:31:39 INFO     SEARCHQUEUE-BACKLOG-299506 :: [Rarbg] :: Cant find search_tvdb in database. Are you sure it exists?
```

**Comment by FGOD1983** [comment]
I am having this same issue with the current version of Sickchill at the moment:

```
2022-10-28 09:49:37 INFO :: SEARCHQUEUE-BACKLOG-73444 :: [Rarbg] :: Cant find search_tvdb in database. Are you sure it exists?
2022-10-28 09:49:33 INFO :: SEARCHQUEUE-BACKLOG-73444 :: [Rarbg] :: Cant find search_tvdb in database. Are you sure it exists?
2022-10-28 09:49:29 INFO :: SEARCHQUEUE-BACKLOG-73444 :: [Rarbg] :: Cant find search_tvdb in database. Are you sure it exists?
2022-10-28 09:49:25 INFO :: SEARCHQUEUE-BACKLOG-73444 :: [Rarbg] :: Cant find search_tvdb in database. Are you sure it exists?
2022-10-28 09:49:21 INFO :: SEARCHQUEUE-BACKLOG-73444 :: [Rarbg] :: Cant find search_tvdb in database. Are you sure it exists?
2022-10-28 09:49:17 INFO :: SEARCHQUEUE-BACKLOG-73444 :: [Rarbg] :: Cant find search_tvdb in database. Are you sure it exists?
2022-10-28 09:49:13 INFO :: SEARCHQUEUE-BACKLOG-73444 :: [Rarbg] :: Cant find search_tvdb in database. Are you sure it exists?
2022-10-28 09:49:09 INFO :: SEARCHQUEUE-BACKLOG-73444 :: [Rarbg] :: Cant find search_tvdb in database. Are you sure it exists?
2022-10-28 09:49:05 INFO :: SEARCHQUEUE-BACKLOG-73444 :: [Rarbg] :: Cant find search_tvdb in database. Are you sure it exists?
```

```
SickChill Info:
Install: [pip](https://anonym.to/?https://pypi.org/project/sickchill/)
Version: [2022.10.13](https://anonym.to/?https://github.com/SickChill/SickChill/releases/tag/2022.10.13)
Database Version: 44.2
  Python Version:3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  SSL Version:OpenSSL 1.1.1f 31 Mar 2020
  OS:Linux-5.4.0-92-generic-x86_64-with-glibc2.29
```

**Comment by miigotu** [comment]
That error comes back directly from rarbg. 
https://github.com/SickChill/sickchill/blob/master/sickchill/oldbeard/providers/rarbg.py#L111

You need to enable debug logging like the issue template says and provide the debug log, because not only does it help us see if it's something we can fix, but sometimes it shows the users where they messed up. If we have enough logs and proof we can contact rarbg or PR to their API code.

**Comment by FGOD1983** [comment]
I've enabled the debug logs, but still nothing more then that error in the logs. But could this also be some sort of rarbg saying that it can't find the show in their database?

**Comment by BKSteve** [comment]
You need to restart SC after changing the setting

**Comment by miigotu** [comment]
#8282 Need to investigate.

**Comment by miigotu** [comment]
@rarbg I came across https://github.com/Jackett/Jackett/issues/13663#issue-1417877577 when looking for other reports of this issue on other applications. Is this possibly because of rate limiting or running out of resources due to rate overloading?

I plan on digging into our requests to the API again and reducing it (I think 3591 is also too much, even if it is much less than jackett). Is there something obvious you see on your end that I can fix?

Maybe the next API version we could sepec

**Comment by FGOD1983** [comment]
@miigotu some more logs since I enabled debug:
```
2022-10-31 10:57:12 INFO :: SEARCHQUEUE-BACKLOG-268592 :: [Rarbg] :: Request failed: 429 Client Error: Too Many Requests for url: http://torrentapi.org/pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=w0qo5i8bk4&category=tv&sort=seeders&mode=search&search_tvdb=268592&search_string=the.100.S03E12 (HTTPError)
2022-10-31 10:57:08 INFO :: SEARCHQUEUE-BACKLOG-268592 :: [Rarbg] :: Request failed: 429 Client Error: Too Many Requests for url: http://torrentapi.org/pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=w0qo5i8bk4&category=tv&sort=seeders&mode=search&search_tvdb=268592&search_string=The.100.S03E12 (HTTPError)
2022-10-31 10:57:04 INFO :: SEARCHQUEUE-BACKLOG-268592 :: [Rarbg] :: Request failed: 429 Client Error: Too Many Requests for url: http://torrentapi.org/pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=w0qo5i8bk4&category=tv&sort=seeders&mode=search&search_tvdb=268592&search_string=The.100.S03E11 (HTTPError)
```
Seems to be indeed rate limits

**Comment by miigotu** [comment]
> @miigotu some more logs since I enabled debug:
> ```
> 2022-10-31 10:57:12 INFO :: SEARCHQUEUE-BACKLOG-268592 :: [Rarbg] :: Request failed: 429 Client Error: Too Many Requests for url: http://torrentapi.org/pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=TOKEN&category=tv&sort=seeders&mode=search&search_tvdb=268592&search_string=the.100.S03E12 (HTTPError)
> 2022-10-31 10:57:08 INFO :: SEARCHQUEUE-BACKLOG-268592 :: [Rarbg] :: Request failed: 429 Client Error: Too Many Requests for url: http://torrentapi.org/pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=TOKEN&category=tv&sort=seeders&mode=search&search_tvdb=268592&search_string=The.100.S03E12 (HTTPError)
> 2022-10-31 10:57:04 INFO :: SEARCHQUEUE-BACKLOG-268592 :: [Rarbg] :: Request failed: 429 Client Error: Too Many Requests for url: http://torrentapi.org/pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=TOKEN&category=tv&sort=seeders&mode=search&search_tvdb=268592&search_string=The.100.S03E11 (HTTPError)
> ```
> Seems to be indeed rate limits

Yeah I was fairly sure about that. Seeing as rarbg has had to open issues and pull requests for like 10 different projects within the last 10 days related to API abuse caused by code mistakes or otherwise tells me that it has had a hard impact on the allotted resources for the machine running the API. We don't want to cause delays for the web page either, because the web experience is how enough is earned to try and get the site to be self sustaining if it isn't already.

I'm hoping that modularizing the rarbg support in SickChill and allowing it to control its own requests and coaching completely sandboxed from sickchill or other plugins screwing with it's settings or configuration. It will be a prime example, since rarbg is the only provider I have started making with support for the movies, but I intend to also modularize that. Maybe a sickchill.providers.rarbg, sickchill.providers.rarbg.series, sickchill.providers.rarbg.movie, sickchill.providers.rarbg.musoc

I'm not sure the layout yet, but it's epic from my point of view! I can hardly type at this moment with one eye open so disregard the length of this post rambling on😆

**Comment by rarbg** [comment]
hey @miigotu whats the sleep between requests on sickchill ?
Can you replicate hitting the api rate limits on your side ?

**Comment by rarbg** [comment]
``` 

IP.HI.DD.EN - - [31/Oct/2022:12:01:41 +0100] "GET /pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=TOKEN_HIDDEN&category=tv&sort=seeders&mode=search&search_tvdb=75978&search_string=Family.Guy.S11E01 HTTP/1.1" 200 71 "-" "SickChill/2021.3.7.post2 (Linux x86_64 4.15.0-192-generic; 27e1b072-2f65-11ed-acae-3ef797c4028a)"
IP.HI.DD.EN - - [31/Oct/2022:12:01:44 +0100] "GET /pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=TOKEN_HIDDEN&category=tv&sort=seeders&mode=search&search_tvdb=75978&search_string=Family.Guy.S11E02 HTTP/1.1" 200 71 "-" "SickChill/2021.3.7.post2 (Linux x86_64 4.15.0-192-generic; 27e1b072-2f65-11ed-acae-3ef797c4028a)"
IP.HI.DD.EN - - [31/Oct/2022:12:01:47 +0100] "GET /pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=TOKEN_HIDDEN&category=tv&sort=seeders&mode=search&search_tvdb=75978&search_string=Family.Guy.S11E03 HTTP/1.1" 200 71 "-" "SickChill/2021.3.7.post2 (Linux x86_64 4.15.0-192-generic; 27e1b072-2f65-11ed-acae-3ef797c4028a)"
IP.HI.DD.EN - - [31/Oct/2022:12:01:50 +0100] "GET /pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=TOKEN_HIDDEN&category=tv&sort=seeders&mode=search&search_tvdb=75978&search_string=Family.Guy.S11E04 HTTP/1.1" 200 71 "-" "SickChill/2021.3.7.post2 (Linux x86_64 4.15.0-192-generic; 27e1b072-2f65-11ed-acae-3ef797c4028a)"
IP.HI.DD.EN - - [31/Oct/2022:12:01:53 +0100] "GET /pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=TOKEN_HIDDEN&category=tv&sort=seeders&mode=search&search_tvdb=75978&search_string=Family.Guy.S11E05 HTTP/1.1" 200 71 "-" "SickChill/2021.3.7.post2 (Linux x86_64 4.15.0-192-generic; 27e1b072-2f65-11ed-acae-3ef797c4028a)"
IP.HI.DD.EN - - [31/Oct/2022:12:01:56 +0100] "GET /pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=TOKEN_HIDDEN&category=tv&sort=seeders&mode=search&search_tvdb=75978&search_string=Family.Guy.S11E06 HTTP/1.1" 200 71 "-" "SickChill/2021.3.7.post2 (Linux x86_64 4.15.0-192-generic; 27e1b072-2f65-11ed-acae-3ef797c4028a)"
IP.HI.DD.EN - - [31/Oct/2022:12:01:59 +0100] "GET /pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=TOKEN_HIDDEN&category=tv&sort=seeders&mode=search&search_tvdb=75978&search_string=Family.Guy.S11E07 HTTP/1.1" 200 71 "-" "SickChill/2021.3.7.post2 (Linux x86_64 4.15.0-192-generic; 27e1b072-2f65-11ed-acae-3ef797c4028a)"
IP.HI.DD.EN - - [31/Oct/2022:12:02:02 +0100] "GET /pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=TOKEN_HIDDEN&category=tv&sort=seeders&mode=search&search_tvdb=75978&search_string=Family.Guy.S11E08 HTTP/1.1" 200 71 "-" "SickChill/2021.3.7.post2 (Linux x86_64 4.15.0-192-generic; 27e1b072-2f65-11ed-acae-3ef797c4028a)"


```

I can answer my questions myself - i don't really see a huge issue with how your code works
I've enabled logs for sickchill to examine whats going on
Sleep is 3 seconds ? I cant find it in the code... the sleep is fine. If you want increase it 2x
If you can optimize per episode search to do a single season search like you wrote it will be great

**Comment by rarbg** [comment]
@FGOD1983 whats your ip address net block ?

**Comment by miigotu** [comment]
> ```
> 
> IP.HI.DD.EN - - [31/Oct/2022:12:01:41 +0100] "GET /pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=TOKEN_HIDDEN&category=tv&sort=seeders&mode=search&search_tvdb=75978&search_string=Family.Guy.S11E01 HTTP/1.1" 200 71 "-" "SickChill/2021.3.7.post2 (Linux x86_64 4.15.0-192-generic; 27e1b072-2f65-11ed-acae-3ef797c4028a)"
> IP.HI.DD.EN - - [31/Oct/2022:12:01:44 +0100] "GET /pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=TOKEN_HIDDEN&category=tv&sort=seeders&mode=search&search_tvdb=75978&search_string=Family.Guy.S11E02 HTTP/1.1" 200 71 "-" "SickChill/2021.3.7.post2 (Linux x86_64 4.15.0-192-generic; 27e1b072-2f65-11ed-acae-3ef797c4028a)"
> IP.HI.DD.EN - - [31/Oct/2022:12:01:47 +0100] "GET /pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=TOKEN_HIDDEN&category=tv&sort=seeders&mode=search&search_tvdb=75978&search_string=Family.Guy.S11E03 HTTP/1.1" 200 71 "-" "SickChill/2021.3.7.post2 (Linux x86_64 4.15.0-192-generic; 27e1b072-2f65-11ed-acae-3ef797c4028a)"
> IP.HI.DD.EN - - [31/Oct/2022:12:01:50 +0100] "GET /pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=TOKEN_HIDDEN&category=tv&sort=seeders&mode=search&search_tvdb=75978&search_string=Family.Guy.S11E04 HTTP/1.1" 200 71 "-" "SickChill/2021.3.7.post2 (Linux x86_64 4.15.0-192-generic; 27e1b072-2f65-11ed-acae-3ef797c4028a)"
> IP.HI.DD.EN - - [31/Oct/2022:12:01:53 +0100] "GET /pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=TOKEN_HIDDEN&category=tv&sort=seeders&mode=search&search_tvdb=75978&search_string=Family.Guy.S11E05 HTTP/1.1" 200 71 "-" "SickChill/2021.3.7.post2 (Linux x86_64 4.15.0-192-generic; 27e1b072-2f65-11ed-acae-3ef797c4028a)"
> IP.HI.DD.EN - - [31/Oct/2022:12:01:56 +0100] "GET /pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=TOKEN_HIDDEN&category=tv&sort=seeders&mode=search&search_tvdb=75978&search_string=Family.Guy.S11E06 HTTP/1.1" 200 71 "-" "SickChill/2021.3.7.post2 (Linux x86_64 4.15.0-192-generic; 27e1b072-2f65-11ed-acae-3ef797c4028a)"
> IP.HI.DD.EN - - [31/Oct/2022:12:01:59 +0100] "GET /pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=TOKEN_HIDDEN&category=tv&sort=seeders&mode=search&search_tvdb=75978&search_string=Family.Guy.S11E07 HTTP/1.1" 200 71 "-" "SickChill/2021.3.7.post2 (Linux x86_64 4.15.0-192-generic; 27e1b072-2f65-11ed-acae-3ef797c4028a)"
> IP.HI.DD.EN - - [31/Oct/2022:12:02:02 +0100] "GET /pubapi_v2.php?app_id=sickchill&min_seeders=1&min_leechers=0&limit=100&format=json_extended&ranked=1&token=TOKEN_HIDDEN&category=tv&sort=seeders&mode=search&search_tvdb=75978&search_string=Family.Guy.S11E08 HTTP/1.1" 200 71 "-" "SickChill/2021.3.7.post2 (Linux x86_64 4.15.0-192-generic; 27e1b072-2f65-11ed-acae-3ef797c4028a)"
> ```
> 
> I can answer my questions myself - i don't really see a huge issue with how your code works I've enabled logs for sickchill to examine whats going on Sleep is 3 seconds ? I cant find it in the code... the sleep is fine. If you want increase it 2x If you can optimize per episode search to do a single season search like you wrote it will be great



> hey @miigotu whats the sleep between requests on sickchill ? Can you replicate hitting the api rate limits on your side ?

I can't personally, but I'm sure some people have lowered the CPU throttle in SickChill which is 1, 3, or 5 iirc, and then the provider I have limiting that by a sleep again. So minimal sleep ends up being 2 seconds, but I feel like there is a hole somewhere. Probably when a proper search is happening since that is a different thread than a regular search and is not locking between them.

**Comment by miigotu** [comment]
With the plugin I will be able to run all provider operations in a single thread, and have more fine grained control over when and how long to sleep, as well as setting the defaults WAY higher than necessary. That combined with more intelligent searches and parsing more than the  first page should DRASTICALLY reduce hits.

I wish SC got more financial support so I could forward some to  you providers a bit to offset costs. But honestly, not much coming 🤷‍♂️

**Comment by rarbg** [comment]
> I can't personally, but I'm sure some people have lowered the CPU throttle in SickChill which is 1, 3, or 5 iirc, and then the provider I have limiting that by a sleep again. So minimal sleep ends up being 2 seconds, but I feel like there is a hole somewhere. Probably when a proper search is happening since that is a different thread than a regular search and is not locking between them.

2 seconds might be a bit low for both our rate limiters and Cloudflare ones
and Im planning to raise that to a minimum of 4 seconds within 90 days. that's why i opened the issues. Its really becoming an issue to sustain 300req/s peaks when most of those requests are abuse and/or devs that didn't implement the API properly. To fix that the only way is to kill the abusers by rate limit and fix the devs mistakes ( not yours )
i honestly didn't see an issue with your app_id that's why i didn't think about opening an issue here but i was wrong because obviously people are complaining here too

i would suggest implementing the following : 


1. Increase the sleep between requests x2 - if its 3 make it 6
2. if the API returns 429 retry in 2 minutes , 429 returns a custom json with rate_limit 1 - ignore it
3. if the API returns 520 retry in 3 minutes
4. if the API returns 200 with a json that contains rate_limit 1 retry in 5 minutes
5. if you can optimize the search by thetvdb to not search for each episode one by one - for example search for season and then for missing episodes from that season that are left - it would be great



> I wish SC got more financial support so I could forward some to you providers a bit to offset costs. But honestly, not much coming man_shrugging

thanks for the thought but we don't accept donations. even when we tried to do so we got $10 for 3 months. people don't like to pay for something that is working they only pay for stuff that don't or are actually are a necessity

**Comment by FGOD1983** [comment]
@rarbg is my IP range still needed for this? (looks like you guys figured out what is going on)

**Comment by rarbg** [comment]
@FGOD1983 both of us cant reproduce your issue
unless you can tell me what your ip range is i cant see if there is an issue with your particular ip or its something else
if you dont want to provide it - youll have to wait for @miigotu to implement his planned changes and see what happens

**Comment by FGOD1983** [comment]
@rarbg `87.253.152.128/25` (if you don't mind I would like to delete it again from the board afterwards :) )

**Comment by rarbg** [comment]
@FGOD1983 i asked for the range not your ip but you can delete it
This is a VPN/VPS/dedicated ip address shared with other people correct ?

**Comment by FGOD1983** [comment]
yes it is a shared range with others through a hosting company

**Comment by rarbg** [comment]
@FGOD1983 so your sickchill was never working on that range

**Comment by miigotu** [comment]
The plugin I'm creating will be sort of a reusable library for rarbg. A person could technically start a thread with it and pass search terms to it and get results, with caching and storing results in a local db and respecting etags and delay requests.

Going to be at least a few days, because I want it to be as generic and universal as possible, since it will be the example for other providers' libraries. I wish I had direct contact with some of the other site operators smh.
