### ISSUE TITLE
Can you add ettv.tv as a Search Provider?

### ISSUE THREAD

**Issue by rr0ss0rr** [SickChill/SickChill#4145]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS:
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by bobbysteel** [comment]
You might want to try Jackett in the meantime to add unsupported providers here.

**Comment by rr0ss0rr** [comment]
Thanks .. Will give it a try

**Comment by bobbysteel** [comment]
Be sure to use the slightly older version of Jackett per this thread here:
https://github.com/SickRage/SickRage/issues/4132 until this bug is fixed.
But can confirm it works just fine w/ many more providers than the built in
ones.

**Comment by MonkWho** [comment]
The bug described in #4132 can be bypassed if you use Jackett version before v0.8.396 because that's the version where they changed the usage of the file arguments. However support for ETTV was added in Jackett version v0.8.396. So it seems there is no way to get around this issue and have support for ETTV eh?
