### ISSUE TITLE
Cannot find Stranger Things in the Search

### ISSUE THREAD

**Issue by achmetinternet** [SickChill/SickChill#4188]
Branch/Commit: master/d8c2613583ce8b321a5adc9ff70c52e830f224a8
OS: Win10 64bit
What you did: I am trying to find Stranger Things via search (Trakt.tv, imdb, etc.) but cannot find it.
What you expected: To find the show.
Not showing an error so cannot send you logs.

**Comment by marka65** [comment]
Not sure if it is a feature or not, but if the show you are searching is already in your list of shows, then it will not show up as a show to add in the returned list.

**Comment by marka65** [comment]
Why would you add it again? - simple mistake - I have done it before wondering why it wouldn't find the show only to realise it was already there.

**Comment by achmetinternet** [comment]
I understand but that I'd have checked before posting. Did you try it yourself? Try to add that show when it is not already in your list.

**Comment by marka65** [comment]
Yes, I have added a few shows in the last day or so and the search function has worked fine. Since the latest update (12 hours ago), the search UI is different and now shows the shows even if it is already in your list, but you can not select it.

You need to update your version to the latest version as the version you have shown was committed on 31 Aug. That may fix your problem.
