### ISSUE TITLE
Adding a new show times out

### ISSUE THREAD

**Issue by royteeuwen** [SickChill/SickChill#4190]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: QNAP
What you did: Try to add a new show with theTVDB (the only indexer available default?)
What happened: search timed out, try again or try another indexer
What you expected: To find the show
Logs:
2017-12-13 21:23:00 DEBUG Thread-270 :: Searching for Show with searchterm(s): ['young sheldon'] on Indexer: theTVDB

**Comment by HappyTreeBeard** [comment]
I am not able to reproduce this problem on the development branch. Are there any additional debug messages after "searching for show with searchterms(s)"? Where is the log showing the error message that says "search timed out, try again or try another indexer"?

**Comment by royteeuwen** [comment]
Nop no more log lines after this one, else I would have pasted it :)! And is it safe to just switch to develop? Im on the master branch, dont know what the policy is and how good it tested is before a PR is merged into develop?

**Comment by HappyTreeBeard** [comment]
The development branch has changes that are not fully tested but you can always give it a try. New changes to the develop branch are vetted with admins and verified with unit tests but new changes are added to development for a reason. 

Do you have the debug or error message that says "search timed out, try again or try another indexer"? How did you know the search timed out? 

Are you still able to get the error? There is a chance theTVDB server / API took too long to response due to heavy load or happen to be down when you tried to add the show.

**Comment by roeiegans** [comment]
Same thing here... Since the new UI I can't add any shows manually. Never had this problem before. The search wheel keeps turning forever, whatever show I try (existing or non-existing). I have even left it running for two hours... Nothing comes up. i checked the TVDB website, the shows are there...

**Comment by DrDrewZA** [comment]
Yup - I second this as an issue - I have the same problem.  An no error appears in the debug level log.  The only indication anything is happening is the entry saying its searching for the particular show - then nothing...  I'm on master version - up to date of course.
