### ISSUE TITLE
YggTorrent Error

### ISSUE THREAD

**Issue by PHD59fr** [SickChill/SickChill#4554]
**Following the change of their interface and domain:**

08:19:10 INFO::SEARCHQUEUE-BACKLOG-263365 :: [YggTorrent] :: Request failed: Exceeded 30 redirects.

> Change url to **https://yggtorrent.is**
> The website has changed so it will rewrite the functions of **search** and **connection**

Updated **next week** on dev

**Comment by pluzun** [comment]
Already in PR ;)

**Comment by phtagn** [comment]
Hi,
I think this needs a couple of fixes as it did not work on my end:
1) use logout instead of déconnexion for checking login. I had a recurring not logged in error.
2) the address is httpS, not http. This triggers a nasty bug with deluge : the first request gets a 301 answer, then there's a second request using httpS which gives a 200, but what comes out is not a proper torrent file and makes the encode function choke with a traceback.
Once I fixed those two things it worked like a charm. Thanks a lot for updating the plugin so quickly.

**Comment by pluzun** [comment]
Hi @phtagn,

We know for thoses two points. But YGGTorrent team make daily updates on their website, so it's pretty hard top prevent their changes. (When i did this PR, the website wasn't on HTTPS for exemple)
That's why i closed my PR waiting the YGGTorrent update finish ;)

**Comment by lejudoka13** [comment]
Hi everybody,
the providers works very well, you can i think begin to rewrite the function search
