### ISSUE TITLE
Knights of Sidonia (anime) season 2 post processing fails

### ISSUE THREAD

**Issue by neo21670** [SickChill/SickChill#4645]
Branch/Commit: master
OS: Linux (in Docker)
Browser: Chrome, though I guess it's irrelevant
What you did: tried to post process Knights of Sidonia S02
What happened: it failed
What you expected: it recognizes episode name by season name specified for the show
Logs:
```
2018-05-01 14:24:29 WARNING POSTPROCESSOR-AUTO :: Processing failed for /srv/storage/Process/Anime/Knights of Sidonia S2 - The Ninth Planet Crusade (TV_1280x720)/Knights of Sidonia S2 - The Ninth Planet Crusade - 11 720p .mkv:
2018-05-01 14:24:29 INFO POSTPROCESSOR-AUTO :: Not enough information to determine what episode this is. Quitting post-processing
2018-05-01 14:24:26 INFO POSTPROCESSOR-AUTO :: Processing /srv/storage/Process/Anime/Knights of Sidonia S2 - The Ninth Planet Crusade (TV_1280x720)/Knights of Sidonia S2 - The Ninth Planet Crusade - 11 720p .mkv (None)
```

This goes on for all the S2 episodes. Show's registered under /home/displayShow?show=278154, advenced tab shows the folder name listed as season alternative. S01 got processed with a similar folder name (`Knights of Sidonia (BD_1280x720)`).

**Comment by VietTPham** [comment]
you need to either do absoulete episode numbering or change it to 
"Knights of Sidonia S2 - The Ninth Planet Crusade - 11 720p .mkv" -> "Knights of Sidonia S2E11 720p .mkv"

**Comment by neo21670** [comment]
I changed the show to scene numbered, but it did not resolve this issue. I intend to rename the episodes as a last resort: i fail to understand how a file that has the exact scene season name in the filename has not enough information to determine the show name and episode number.

**Comment by VietTPham** [comment]
It is not problem with Sickrage, it is with the way the files was named from the scene.
Sickrage is not able to detect `Knights of Sidonia S2 - The Ninth Planet Crusade - 11 720p .mkv` Because there is the ` - The Ninth Planet Crusade - ` part, and program does not know what the hell it is, it does not know that that is what the season 2 is call.

I tested it with the filename `Knights of Sidonia S2E11 720p .mkv` and it was able to process it fine
`Moving file from Knights of Sidonia S2E11 720p .mkv to Knights of Sidonia/Season 02/Knights of Sidonia - S02E11 - Random Encounter [720p HDTV].mkv`

**Comment by neo21670** [comment]
I see your point, though I do not understand, what's the point of adding
season specific names then, especially when they're already provided by
tvdb. In my opinion (season specific name)(separator)(scene absolute
episode) should be a valid recognition pattern if it is not there already.

**Comment by neo21670** [comment]
Just to wake up this kind of dormant issue: I am experiencing this kind of behavior on more and more batch packs and it is getting even more annoying in the case where it is an already known fact that the show has ended.
