### ISSUE TITLE
Sickracke package available for Armada38x ?

### ISSUE THREAD

**Issue by markusd1984** [SickChill/SickChill#4845]
I added http://packages.synocommunity.com but I couldn't find sickracke package for my DS416slim.

Is it available for Armada38x or any chance for a build please?

**Comment by markusd1984** [comment]
Found it at https://packages.sickrage.ca v 20180708-3

https://www.sickrage.ca/forums/forum/main-category/main-forum/36127-permission-issue

Not sure how it's different from BenjV's .SPK Sickrage package  SickRage DSM 6 noarch V1.0.spk?
https://github.com/BenjV/SYNO-packages

**Comment by BenjV** [comment]
Don't use that one.
That's Echelon's version and is not from this site.

You can use my version but it is preferable to use the Sickbeard-custom from the SynoCommunity.
I created my package because when the SynoCommunity did not supported DSM 6, but that is fixed now.
It will ask for a github (default to Sickbeard), and you must change it to  this github.
Also read this:
https://github.com/SynoCommunity/spksrc/wiki/Permission-Management

**Comment by OmgImAlexis** [comment]
@markusd1984 please do not link to that site again or your whole comment will be removed.
