### ISSUE TITLE
Feature Request: Web-UI: checkbox to hide full and ended show

### ISSUE THREAD

**Issue by NiocB** [SickChill/SickChill#4849]
Hi,

I use SickRage for a long time and I have a lot of shows. I would like a mean to hide all the shows that I have fully downloaded/archived/... and ended. 

I would like to not delete them or stop SickRage to watch these shows since in some cases, an other network may continue the show or have some final episodes launched afterwards...

So, is it possible to have this feature?

Thanks,
Nioc

**Comment by JoshuaArus** [comment]
Hi,

This could indeed be a good feature.

Waiting for the implementation, here is a little trick : create a new bookmark in your browser, and instead of specifying an URL, enter this code : 

`javascript:(function(){var completedShows = document.getElementsByClassName("ui-progressbar-complete");for (var i = 0; i < completedShows.length; i++){var show = completedShows[i].parentElement.parentElement.parentElement;show.style.display = "none";}})();`

Now, just go to the main page of your sickrage server, and when the show list is loaded, click on the bookmark. It will hide shows with completed progressBar. Just reload the page to display them again.

It doesn't work very well in "poster mode" because of some CSS issues, but just use the slider to zoom/dezoom after you clicked on the bookmark, and it will be prettier ;)

**Comment by JoshuaArus** [comment]
Also available as a userScript with icon to activate/deactivate the feature (and a setting save in cookie) here if you prefer : https://github.com/JoshuaArus/SickrageCompletedHider

**Comment by NiocB** [comment]
Hi, thanks! 

It helps to hide completed shows, it's a really nice trick.
The issue is that is do not respond fully to the request. 
I would like to hide completed AND ended.

The idea is to hide only the shows that will have no more activities. 
I know that the easy way is to delete the show but sometimes the show is bought by another company and seasons continue after a time.

Thanks for the help!
