### ISSUE TITLE
Synology fail to run package

### ISSUE THREAD

**Issue by vegeto10** [SickChill/SickChill#4970]
### Before submitting your issue:

Enable debug logging in SickRage settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Benji 999999 and then update
OS: synology
Browser:
What you did: installed sickrage 20 times now, will work for 2 days then fail to run package. It was working successfully for last 2 years. Just tired now. 
What happened:
What you expected: Is there any other way to install sickrage on synology. Adding community repo not showing sickrage 
Logs:
```
PASTE LOGS HERE
```

**Comment by BenjV** [comment]
You can use the SynoCommunity package  named sickbeard_custum and the use this github instead of the sickbeard github.

But I am still use my package still without any problems so it must be some problem on your Nas settings.
Did you update SickRage from within SickRage after the installation of the package?

**Comment by vegeto10** [comment]
i will try that

Yesterday end up installing Sonarr , so far working great
