### ISSUE TITLE
qbittorrent "Unable to send Torrent"

### ISSUE THREAD

**Issue by dsm1212** [SickChill/SickChill#5016]
In the qbittorrent client code when a torrent is sent there is a function _verify_added(). Maybe this is a recent addition? This function queries and checks to see if piece_size is != -1. It tries this 5 times 2 seconds apart. So 10 seconds. On my NAS this is never enough time. The problem is that the file does not get labeled after this failure and then it doesn't get moved the right folder and post processed. I think waiting for the transfer to start is problematic. The function either has to wait longer or maybe return success just from finding the entry.

**Comment by dsm1212** [comment]
For now I bumped retries from 5 to 15 and it seems ok.

**Comment by XxUnkn0wnxX** [comment]
I seem to be having same issue here: #5016

how did you bump up the timer? as looking for "verify_added()" within SC source files I don't see such a function or is this in qB source code? [I don't run qB from source]

**Comment by dsm1212** [comment]
I don't have it in front of me but in qbittorrent_client.py look for the number 5. Its passed as an argument "attempts". Change that to 15. Would be great if someone would promote this.

**Comment by XxUnkn0wnxX** [comment]
still cannot find qbittorrent_client.py + I cannot run from source as I'm running into a compiling issue:

`/usr/local/include/libtorrent/hasher.hpp:57:10: fatal error: 'openssl/sha.h' file not found` which is odd

I did DL qB from here: https://github.com/qbittorrent/qBittorrent - source code. maybe because you have a different setup then mine I cannot seem to find it.

**Comment by dsm1212** [comment]
See here: https://github.com/SickChill/SickChill/blob/master/sickbeard/clients/qbittorrent_client.py

On line 134 change the default for attempts from 5 to 15 like this:

    def _verify_added(self, torrent_hash, attempts=15):

Sorry I don't have time to promote. Probably we should make this a configurable setting anyhow.

steve

**Comment by miigotu** [comment]
qbittorent is fixed ^

**Comment by sumarimike** [comment]
I was also having this issue with Qbittorrent v4.1.5 and SickChill v2019.01.06-1 "Unable to Send Torrent". Troubleshooting, it seems that Qbittorrent sometimes adds a torrent but doesn't have the "pieces" for a while. The _verify_added function is looking for "piece_size" (line 163 in qbittorrent_client.py). Because this is often a blank field until the torrent connects and activates even setting the attempts high may not always work.

Checking out the current Web UI API, it seems a better check is the following:

`def _verify_added(self, torrent_hash, attempts=25):
        self.url = urljoin(self.host, 'query/propertiesGeneral/{}'.format(torrent_hash.lower()))
        for i in range(attempts):
            if self._request(method='get', cookies=self.session.cookies):
                if self.response.json()['**addition_date**'] != -1:
                    return True
            sleep(2)
        return False`
Change this, then restart SickChill and when the torrent is added to the torrent list, even if there are no pieces yet, the acknowledgement is there that the torrent was successfully snatched. 

I'm not fully versed in checking the status or not of a torrent in progress, but this seems like a good way to check that it was added. It works very quickly and accurately as far as I can tell.
