### ISSUE TITLE
Unable to start after update. (windows installer version)

### ISSUE THREAD

**Issue by akselfoley** [SickChill/SickChill#5144]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:
OS: Server 2012 R2
Browser: Firefox
What you did: Sickchill updated itself
What happened: Did'nt start afterwards
What you expected: A solution for this when you're not a pro git'er :D

Any solutions to this problem when you have used the installer? :)

**Comment by izakbar** [comment]
look at webserve.py

from requests.compat unquote_plus

should be :

from requests.compat import unquote_plus


Looks like an untested check-in occur'd and killed peoples sickchill installs (cannot auto update if it won't start). Fix that file, it will check GIT and auto update with a working version.

**Comment by miigotu** [comment]
Its already fixed, just do a pull... Did you try a pull before opening this issue?

**Comment by izakbar** [comment]
> Its already fixed, just do a pull... Did you try a pull before opening this issue?

Guess what the update broke on my Synology within the sickbeard-custom package. 
I had to find problem and fix manually so it would re-pull later fixed/tested version.

BTW "It's" not "its" - More care required in a few things it seems.

**Comment by miigotu** [comment]
Excuse me? I dont need policed on grammar. I dont work for you, and I am not writing a resume.
BTW, search before you open an issue, try to fix the problem yourself, and make sure it hasnt already been fixed before you open an issue. And when you do, dont be a rude fuck to people who do shit for you for free.

**Comment by izakbar** [comment]
> Excuse me? I dont need policed on grammar. I dont work for you, and I am not writing a resume.
> BTW, search before you open an issue, try to fix the problem yourself, and make sure it hasnt already been fixed before you open an issue. And when you do, dont be a rude fuck to people who do shit for you for free.

Wow. What a numbskull.
1. I never said you worked for me. I wouldn't employ you - bad attitude.
2. I didn't raise the issue - READ the issue before acting like you are God. You are not - you are just a developer.
3. Try not to be rude to people trying to help other users fixing a problem YOU caused.
4. Try to follow your own advice - don't be a "rude fuck" to people who help you for free - I was pointing out the fix for akselfoley's issue - you came in big'n'bad waving your dick about. 
5. Grow the fuck up.

**Comment by miigotu** [comment]
1. Your advice was incorrect, because "force git update" is not checked by default
2. "BTW "It's" not "its" - More care required in a few things it seems." - You are a snotty jackass correcting people who do not need correcting. I will not apologize for skipping a fucking apostrophe when in a rush.
3. Bye.

**Comment by miigotu** [comment]
Fucking break a build for less than an hour ONCE in 4 years and this dickwad wants to run his mouth about free software. Entitled prick.

**Comment by miigotu** [comment]
`net stop sickchill && cd c:\SickChill\SickChill && c:\SickChill\Git\bin\git fetch origin && c:\SickChill\Git\bin\git reset --hard origin/master && net start sickchill`

**Comment by akselfoley** [comment]
Thank you miigotu. Saving that solution for later as well!! :)
