### ISSUE TITLE
RFE: Don't replace existing even if it's preferred

### ISSUE THREAD

**Issue by brianjmurrell** [SickChill/SickChill#5207]
It would be useful to be able to set a preferred quality, but NOT replace an existing episode if it exists even if it's not preferred quality.

As an aside and additionally, it would be also useful to be able to configure a time delay between finding an episode that is not of preferred quality and downloading one from the allowed quality list.  So for example configure to wait for 2 days for a preferred quality download but download any allowed quality if preferred is not found within 2 days.

Both of these could be used to conserve bandwidth by waiting for and preferring an SD download over an HD download but to use an HD download if an SD download doesn't become available within a given time frame.

**Comment by brianjmurrell** [comment]
It's only stale because nobody has even triaged it yet.

**Comment by brianjmurrell** [comment]
How many times are we going to play this game of stale/not stale?

**Comment by potestus** [comment]
This is quite an issue for me.. I download exclusively X265 1080p.. This is not accounted for in sickchill so I have to set custom/Unknown..  I can't set a preferred option as it just looks for 264.. As a result all of my shows that are not wanted are set to allowed (hundreds) .. This causes a huge amount of backlog scan which exceeds my provider limits..

1/ It would be good to have a "any" ie don't care option for allowed

2/ the backlog force could be graduated form. More often  in the first two days then less often gradually over the next 5..
3/ the backlog screen should allow a filter between wanted and allowed.. 
4/ a big button to do all wanted forced. 
Be good to fix the x265 thing though.

**Comment by tjenvy** [comment]
I had an entire series download and almost crashed my server because of this  I had gotten them elsewhere on my own and then in the middle of the night it finally found them and tried downloading them.  It was some backlog of files form ages ago that popped up somewhere.  wiped out 175 gb of space and stopped the server.   

So yes, if a file is downloaded (by checking the directory to see if its there) then yes dont download would be great.  Maybe a checkmark somewhere?

**Comment by deepseth** [comment]
> So yes, if a file is downloaded (by checking the directory to see if its there) then yes dont download would be great. Maybe a checkmark somewhere?

So, the default presets under 'preferred qualities' (Any, SD, HD, HD720p, HD1080p at least) only include 'Allowed' qualities in their list, and no 'Preferred' qualities in their list. If you stick to these, you wont have this occur.

If you use a custom 'Preferred Quality', if you restrict your selection to 'Allowed', then this wont happen. If you make selections from 'Preferred', then this will still happen.

**Comment by deepseth** [comment]
So the checkbox to ignore downloaded episodes from backlog searches is now there.

How do the people who want a time limited function feel about using the 'Backlog search day(s)' counter for this?

Or more importantly, what does @miigotu think about using that?

If there's general approval, I might get it done. I might also move the toggle higher up the screen to be closer to that number as well then, since it'll relate to it rather than being a standalone independent thing.

**Comment by brianjmurrell** [comment]
Why close if it's actually still an issue?

**Comment by miigotu** [comment]
hover your mouse over the tag I added to it and read the details. It isnt an issue its a feature request.

**Comment by brianjmurrell** [comment]
Interesting.  I've never noticed that there is a hover-over for tags.

Is there a feature tracker somewhere that these are added to, or is 'BACK-BURNER" the feature tracker?  I wonder if it would be more obvious to people if the tag were named FEATURE-REQUEST rather than BACK-BURNER.

**Comment by miigotu** [comment]
![image](https://user-images.githubusercontent.com/390379/76170293-f8f35600-6156-11ea-8942-e97d262e2030.png)
It is tagged feature request, the new tag is to note that its closed because it isnt an issue but can be pulled up in the future when someone wants to work on adding a feature.
https://github.com/SickChill/SickChill/issues?q=label%3ABACK-BURNER

**Comment by miigotu** [comment]
Also, some people have a habit of spamming feature requests. It's easy to say `I wish it did this` and post an issue for it, but it isn't productive unless its a novel idea. Most things like `Do movies also` are so redundant it's silly, like we haven't thought of that.

The important thing is to get it working nearly flawless FIRST.

**Comment by miigotu** [comment]
We used to have a feathub for it, but we lost control of that in the rename:
https://feathub.com/SickRage/SickRage

I will probably be adding a new feathub to address this problem of issue tracker spam.
