### ISSUE TITLE
yggtorrent miss lot of animes

### ISSUE THREAD

**Issue by cswormy** [SickChill/SickChill#5209]
#4947 introduces an error : when an anime is named S01E01, it can't be found.
Why ?
self.show.is_anime is used for naming search (S08E12 if false, E120 if true). But in yygtorrent search it is also used for sub_category (anime or TV serie).
So it leads : 
- TV series is always numbered S08E12
- anime is always numbered E120
So it is too restrictive.

**Comment by cswormy** [comment]
@miigotu Hello, yes I know that but you don't understand the problem.
In yggtorrent provider, the search is too restrictive. It uses the variable self.show.is_anime to search in anime section of yggtorrent. So if an anime is released as SxxExx, disable the anime option leads to search in TV Series of yggtorrent. This is an error. That's why I purpose to remove the restriction.

A best solution should be splitting self.show.is_anime in two variables : self.show.search_with_absolute_number and self.show.anime_category
But I think it is easier to remove subcategory in yggtorrent search.

**Comment by miigotu** [comment]
@cswormy The problem I have with it is that if you remove the restriction it will break daily/rss search, because too many results will be on the first page that are not in the correct categories. If SxxExx is not found in the normal TV subcategory, it will not be found in anime. The same that if Show.xxx (absolute number) is not found in the anime category it will not be in the other categories.

The solution is that if your show is released on the providers as SxxExx you disable the anime setting for that show and force a full update, and the search will succeed and find matches. If it is released with Exxx then you enable the anime setting for that show and force an update and it will be found in the anime category.

We cannot break one search type to try and fix another search type (especially to only fix anime, which is a tertiary feature compared to normal shows which are the priority)
If I am wrong about the categorization on the site, show me some search results on the site and what category they are in so I can see where the site is messing up. I might be able to talk to the site owners about fixing it on their end properly.

**Comment by cswormy** [comment]
Thanks, I have purposed this solution because I don't see regression and I use it since one week. But of course, I didn't use all functionnalities. 
I think there is a confusion about self.show.is_anime. For example, in http://localhost:8081/config/anime/
we can split anime and series. But for anime with season numbering, they are not correctly sorted of course.

**Comment by cswormy** [comment]
An example : the anime "Goblin Slayer" is released in ygg : 
https://ygg.to/engine/search?name=Goblin+Slayer&description=&file=&uploader=&category=2145&sub_category=2179&do=search
But ygg search has a default : it searches only exact words (not substring) so when you check "anime" option, Sickchill search : 
https://ygg.to/engine/search?category=2145&do=search&sub_category=2179&name=Goblin+Slayer+02 
And he finds nothing

When you uncheck anime, Sickchill search : 
https://ygg.to/engine/search?category=2145&do=search&sub_category=2184&name=Goblin+Slayer+S01E02 
And he finds nothing.

That's why I remove the sub_category.

**Comment by miigotu** [comment]
The anime setting isnt for splitting the home page, it is for changing the way that the scene numbers them on providers ^
We just leverage that for the added feature of splitting the home page.
