### ISSUE TITLE
Migration to python3

### ISSUE THREAD

**Issue by swetoast** [SickChill/SickChill#5347]
Hi @miigotu since python 2.x is nearing EOL is this project gonna migrate to python 3.x ?

**Comment by BenjV** [comment]
EOL is not the correct term.
First of all EOL means End Of Line and not End OF Life

Second Python 2 is not End Of Life but End Of Development.

Which means no new development will be done for Python 2 but it will be around for many, many more years because of the millions of line of code which is written for Python 2.

But of course an investigation of the effort needed to port to python 3 would be wise.

**Comment by WebSpider** [comment]
Unstale

**Comment by rmbleeker** [comment]
I hate to be "that guy" but @BenjV you're wrong twice. First of all [EOL](https://en.wikipedia.org/wiki/End-of-life_(product))is a commonly accepted acronym for End Of Life in the software world. Secondly Python 2.7 will not be maintained anymore per [01-01-2020](https://pythonclock.org/), which means there will be no more security updates. New features haven't been implemented in Python 2 for years.

So a move to python 3 is getting more and more urgent, but I'm sure @miigotu and the rest are already working on it.

**Comment by BenjV** [comment]
First of all you do not hate to "be that guy" dut you are "that guy" otherwise you would not reacted this way on my little joke about EOL.
Secondly it is of course not a bad idea to port to python 3 but not because new features are not implemented in python2, that would only be the case if such a feature would be needed for the application and of course there are no such need.

And python2 is still getting security updates when that would be needed.
The urgency is just there because the software world has the state of mind "old is bad", but I would call it mature.
A whole world is writing code in for example java and everybody knows what a security crapp that is, so give me python 2 anytime.

**Comment by pro-src** [comment]
Somebody doesn't like to be corrected :rofl:

**Comment by rmbleeker** [comment]
Here it is directly from the horse's mouth, from https://www.python.org/dev/peps/pep-0373/#update

> Being the last of the 2.x series, 2.7 will have an extended period of maintenance. Specifically, 2.7 will receive bugfix support until January 1, 2020. After the last release, 2.7 will receive no support.

Furthermore, several cybersecurity organizations have put out warnings that Python 2 will no longer receive bugfixes and security updates after 1-1-2020, for example the British National Cyber Security Center: https://www.ncsc.gov.uk/blog-post/time-to-shed-python-2

> As of the 1st of January 2020, Python 2 will no longer be supported. There will be no more bug fixes, or security updates, from Python's core developers.

**Comment by swetoast** [comment]
im closing this issue since there seems to be a clear lack of interest in progressing with python3 

suggest moving to medusa that already supports python3

**Comment by miigotu** [comment]
Way to go, bud. Obviously we will get to py3 asap, but it isn't a serious issue since we control the chain from start to finish. Py27 will still get updated packages from the community, the interpreter itself is all that will not.

**Comment by cheese1** [comment]
interest is alive, as eg fedora is starting to remove python2. timeframe here is fedora 32 (in around 6 months) https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3

**Comment by BenjV** [comment]
Just like on all other systems you kan install python 2 yourself when fedora no longer bundle it with the release.

**Comment by swetoast** [comment]
or just migrate to medusa instead and be done with this

**Comment by cheese1** [comment]
@BenjV : thats clear, but no solution in the long run. distros will remove python2 and lots of subpackages if not tomorrow, but in the long run. i clearly will start packaging for python2, but my main interest is in a python3 version. other similar systems like medusa (which i currently test privately and will release in a couple of days after some checks) are no real solution for me, eg it misses german airdates, as far as i know.

**Comment by miigotu** [comment]
@cheese1 Im very interested in any help I can get with a python3 migration in SC. I dont have as much time right now as I used to, but it absolutely needs done.

**Comment by cheese1** [comment]
@miigotu : would like to help, but i'm not very skilled in python3

**Comment by jonpspri** [comment]
I've been working on a fork of it in my spare time over the last few days, but think I'll wait for the next major rev to come out.  Biggest headache is with strings become Unicode, a lot of the internal encoding code is superfluous.  I've been ripping at that and hoping not to break anything...

**Comment by miigotu** [comment]
@jonpspri being py3 compatible is easy, the libs is the issue

**Comment by jonpspri** [comment]
@miigotu Agreed.  I've patched adba and fanart.  If I use latest versions of the rest of them, I can get through init after moving all internal representations to _str_ and accounting for the peculiarities of the github library.  But, I seem to have introduced breaking upgrades for Tornado (and I'm sure some other things), which is where I'm now focused.  Once I've got a stable working version, I'll go back and look to freeze the libraries (or maybe bootstrap _venv_ on startup since it comes standard with Python 3).

**Comment by JonathanLydall** [comment]
It appears that use of Python 2.7 is becoming a real problem aside from just security.

On startup SickChill shows the following error: 

`DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2t  10 Sep 2019) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.`

And the reporter of issue #6037 is experiencing this exact error when scraping a source.

**Comment by rmbleeker** [comment]
Actually that is a security issue, to there's no "aside"

It seems that soon to be released distro versions like for example Ubuntu 20.04 LTS will also ship [without Python 2.7](https://www.phoronix.com/scan.php?page=news_item&px=Python-2-EOL-Ubuntu-20.04) in their main repositories.

**Comment by BenjV** [comment]
Has nothing to do with python 2.7.
An update of the openssl library should be sufficient.
I this case I assume urllib3.

**Comment by miigotu** [comment]
@BenjV python2.7 on windows has openssl bundled, and has to be self compiled to get a newer ssl.

@rmbleeker First, openssl/python2.7 aren't a security issue for us, even if they don't do security updates, because we aren't using it in the ways that are vulnerable. Also, 20.04 and beyond will have 2.7 in their main repos, they just won't ship with it pre-installed.

That aside, I want to migrate to python3, PRs are welcome.

**Comment by tmcarr** [comment]
No pressure or anything, but sickchill will flat out not run on my Debian testing box anymore due to the Python2 removal... I'm forced to use a competitor now, much to my dismay. :(

**Comment by miigotu** [comment]
You can still install python2 on Debian and ubuntu. They aren't going to remove python2 from the repos.

**Comment by tmcarr** [comment]
They absolutely did.

**Comment by tmcarr** [comment]
I can no longer install pip2, only pip3. I also no longer have /usr/local/python. They fully removed it.

**Comment by tmcarr** [comment]
Keep in mind, im not on stable, im on testing, so this is moving faster than the average release. Either way.... python3 is getting more and more needed every day,

**Comment by tmcarr** [comment]
python-pip (20.0.2-1) unstable; urgency=medium

  * Team upload

  [ Emmanuel Arias ]
  * Add patch: fix Type error on list outdated comand (Closes: #878082)
    - Add 0007-Fix-Type-Error-on-lis-outdated-command.patch
    - Add test on d/tests/pip3-user.sh
  * Bump Standard-Version to 4.4.1 (from 4.2.1)

  [ Ondřej Nový ]
  * Use debhelper-compat instead of debian/compat.

  [ Scott Kitterman ]
  * New upstream release (Closes: #949128)
    - Delete d/p/Properly_catch_requests_HTTPError_in_index.py.patch,
      incorporated upstream
    - Delete d/p/0007-Fix-Type-Error-on-lis-outdated-command.patch,
      incorporated upstream
    - Refresh patches
  * Set minimum version requirements in build-depends for unvendored packages
    based on version vendored by upstream
  * Add python3-contextlib2, python3-msgpack. and python3-pep517 to
    build-depends because they are vendored by upstream and run dirtbike in
    d/rules to produce the required wheels
  * Drop python2 support (Closes: #938027)
  * Add appdirs to unbundled lib list in src/pip/_vendor/__init__.py so
    Debian's unbundled approach works (already fixed upstream for 20.0.3)

 -- Scott Kitterman <scott@kitterman.com>  Sun, 15 Mar 2020 19:35:26 -0400

**Comment by miigotu** [comment]
1. Pip doesnt need to be installed with apt
2. It is still available as python2-pip

**Comment by tmcarr** [comment]
Ok, those are not entirely true in debian, but either way, there is now a missing dep in the latest release that is impossible to install without pip...

**Comment by miigotu** [comment]
What isnt true? I'm using debian testing too smh.

**Comment by tmcarr** [comment]
python-pip no longer exists, python2.7 is installed on my system. I can no longer install feedparser, which is making the latest update fail to launch...

**Comment by miigotu** [comment]
I'll install a new debian testing box and show my steps. Brb

**Comment by miigotu** [comment]
You dont need to install feedparser, see #6230

**Comment by miigotu** [comment]
And, as stated above, pip is better installed outside of the package manager, just like node is also.
```bash
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python2 get-pip.py  --user
```

**Comment by tmcarr** [comment]
Fair enough, I didn't see that bug. Either way, python3 will become more and more important and debian is actively ripping it out. I still cannot find a working pip in the debian repos for testing... and even their wiki shows it doesn't exist anymore. It wont be long before they remove the interpreter too.

**Comment by tmcarr** [comment]
Also, thanks for your work on this project... I just checked out Sickrage again and whoooooooboy am I glad this went in a better direction.
