### ISSUE TITLE
Cannot find series from tvdb while it exist on webportal

### ISSUE THREAD

**Issue by antipiot** [SickChill/SickChill#5467]
Branch/Commit: v2019.04.07-1
OS: Docker - debian
Browser: Mozilla
What you did: try to add new Show called "watchmen" 
What happened: only one result is returned for the searche instead of 3 when searched from portal
What you expected: finding all 3 entries wich are returned when searching from web tvdb portal.
Logs: NONE
![add2](https://user-images.githubusercontent.com/26579988/57573348-96420880-7426-11e9-8f54-49ca34138452.PNG)
![add1](https://user-images.githubusercontent.com/26579988/57573349-96da9f00-7426-11e9-9e59-a46a8ae0e8c0.PNG)

**Comment by tjenvy** [comment]
I am having this issue as well with a show form 2018.  I have tried the IMDB number, the TVDB umber, the name, the name + (year)  I can find it right on TVDB site, but SC wont find it at all.

**Comment by stevegilbert23** [comment]
Is there a workaround for this?
This show starts soon.
https://www.thetvdb.com/series/watchmen
Is there a way to get a show into the show list manually if the thetvdb.com series number is known? (360733)

**Comment by tjenvy** [comment]
yup same here thats the one I was trying too.  a few others showed up weird with "unknown premier date"  and was able to add them and they were right.  this one it refuses to find.

**Comment by tjenvy** [comment]
hey @stevegilbert23   Go to:

add show > imdb > watchmen   add from there 

just saw it.

Doesnt excuse the software screwing up but hey its added!

![Screen Capture 2019-09-27 at 8 23 22 AM](https://user-images.githubusercontent.com/11091359/65768847-1def9180-e100-11e9-9ba8-579d25617d7b.PNG)

**Comment by stevegilbert23** [comment]
That worked, but yeah.

**Comment by nobodyspecial** [comment]
Use this search string:

`Watchmen \:`

**Comment by tjenvy** [comment]
I did not try that workaround since I already have the show in there now
via the IMDb list. However can you elaborate on this search string and it’s
purpose? What specifically is this doing and does it work for other
searches etc.

It still doesn’t stop this from being a bug however because who in the
world would have thought of that as something to just try lol.

Sent from my iPhone

On Oct 21, 2019, at 8:09 AM, nobodyspecial <notifications@github.com> wrote:

﻿

Use this search string:

Watchmen \:

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/SickChill/SickChill/issues/5467?email_source=notifications&email_token=ACUT3HYQTPQSRQOAP3BJ5OLQPWLZHA5CNFSM4HMIVPCKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEB2C57A#issuecomment-544485116>,
or unsubscribe

**Comment by nobodyspecial** [comment]
When searching for watchmen the only show that came up is "Watchmen: Motion Comic". I figured the colon was stopping the search for some reason so I escaped it. It worked.

**Comment by miigotu** [comment]
#5789 fixes, is in develop branch. Will be on master after more testing.
