### ISSUE TITLE
[FEATURE REQUEST] Kickass is back can you add to the Search Providers

### ISSUE THREAD

**Issue by Victorvdc** [SickChill/SickChill#5475]
Kickass Torrent site is back. Can you please add it back to the Search provider list if it is not too much trouble

**Comment by WebSpider** [comment]
It appears the current URL (https://kickass.best/ contains a mirror redirector. In order to prevent us changing URL's every other week, we should see if we can pick up the main mirror automatically

**Comment by NeoMod** [comment]
AFAIK the KickAss portal has been closed since 2016 and there hasn't been any official come-back.
All present sites, including the one mentioned, which have "KAT" in their name are actually SCAM/CLONES of the original.
The one mentioned, for example, is a black-pit infested with JS Adware (like JS/Adware.Agent.AA ) and the "usual" redirect clickjacking, but no actual content is present.
This should be closed, not marked as featured request.

**Comment by WebSpider** [comment]
If there is nobody objecting this, i will close this in a few days. Want to give the submitter chance to reply.

**Comment by Victorvdc** [comment]
Hi

 

Go ahead and close this  if you get this email. I have been to busy to log in the last few days to change the status but I will try soon.

 

Thanks for your efforts.

 

Victor
