### ISSUE TITLE
Could not open static file (.png) error

### ISSUE THREAD

**Issue by rEes9P** [SickChill/SickChill#5482]
**Branch/Commit:** master/175df89cabf295358b8caa2d96dafadb2347622d

**OS:** macOS High Sierra (10.13.6)

**Browser:** Safari

**What you did:** Looked at the logs to see why shows were not being updated

**What happened:** Saw the following error messages, referencing a file path that I think was used over a couple of years ago as a root directory and a show that was deleted from SickChill a week or so ago.

**What you expected:** Not to see these error messages

**Logs:**
```
AA 2019-05-14 12:53:23 ERROR    Could not open static file u'/Applications/SickChill/gui/slick/images/subtitles/flags/Volumes/path that no longer exists/SickRage/Show that has been deleted from SickChill/Season 3/3x01 - Episode name.srt.png'
AA 2019-05-07 16:40:08 ERROR    Could not open static file u'/Applications/SickChill/gui/slick/images/subtitles/flags/Volumes/path that no longer exists/SickRage/Show that has been deleted from SickChill/Season 3/3x01 - Episode name.srt.png'
AA 2019-05-07 15:39:56 ERROR    Could not open static file u'/Applications/SickChill/gui/slick/images/subtitles/flags/Volumes/path that no longer exists/SickRage/Show that has been deleted from SickChill/Season 3/3x01 - Episode name.srt.png'
AA 2019-05-07 11:25:06 ERROR    Could not open static file u'/Applications/SickChill/gui/slick/images/subtitles/flags/Volumes/path that no longer exists/SickRage/Show that has been deleted from SickChill/Season 3/3x01 - Episode name.srt.png'
```

**Comment by WebSpider** [comment]
As a help reproducing this, do you remember if you removed the show before you removed the media directory from SC?

**Comment by rEes9P** [comment]
> As a help reproducing this, do you remember if you removed the show before you removed the media directory from SC?

I'm sorry but I don't remember as it was a long time ago.

**Comment by OldskoolOrion** [comment]
it turns out that streamed shows e.g. on Netflix, are starting to follow ISO standards in naming languages for local areas within the main language, with their correct code.. I noticed it with a show today myself. 

One would expect to find the the Norwegian subtitle in a container to be named "nor" - as it has been for ages.  Today I saw them using "nno" and "nob" as well.. since "lib/hachoir_core/iso639.py" actually is the iso630-2 table, the code doesn't need to change.. just the nor.png needs to be copied to nno.png, and nob.png .

They are actually working on the iso639-5 standard to get that finalized (and I saw a hell of a lot additions and changes), so the moment subtitles are included for regions that have a lot of local dialects, at that time that will have to change and be expanded. The flags don't change, but content gets offered far more targeted by Netflix.. a lot of cash goes into each country they are in, to create local content in native tongue.

Anyway.. bit of a vague story, but that's where it's probably originating.. check the mkv.. see what subs are in there and apply the fix in your install, for a quick fix, so you can at least get your shows processed right :-)

**Comment by rEes9P** [comment]
Thanks @OldskoolOrion for that super detailed response! I don't think I see the errors anymore so all good!
