### ISSUE TITLE
Docker build travis-ci is failing

### ISSUE THREAD

**Issue by utdrmac** [SickChill/SickChill#5575]
Can someone please investigate why the docker build process is failing? sickchill:latest tag is now 3 months old.

https://travis-ci.org/SickChill/SickChill/builds

**Comment by sandervankasteel** [comment]
@utdrmac I noticed the same thing. 

I just did some small investigation, and it turns out that in the "not working" build (https://travis-ci.org/SickChill/SickChill/builds/551440806#L316) the `isort` process returns with a -1 exit code, while in the "working" build (https://travis-ci.org/SickChill/SickChill/builds/551178808#L303) the same error occurs but with a 0 exit code. 

For the moment, the only real change I can see between the two builds is the difference in Tox version (3.7.7 vs 3.7.8). 

The changelog for Tox (https://flake8.pycqa.org/en/latest/release-notes/3.7.8.html) doesn't reveal much on how, what and why. 

So this story will be continued :wink:

**Comment by sandervankasteel** [comment]
@utdrmac There is a PR ready to fix the CI pipeline :)

**Comment by seanmccabe** [comment]
Do we know when we are going to get an update docker build?

**Comment by sandervankasteel** [comment]
My PR (which fixes this) has just been merged, so it's matter of time is my guess.

**Comment by WebSpider** [comment]
There are some other fixes in develop that need a few days of testing, once that's OK, this will go to master

**Comment by seanmccabe** [comment]
Any further update, its been a "few days"
