### ISSUE TITLE
Feature Request: Post Processing None/Noop Method

### ISSUE THREAD

**Issue by cewood** [SickChill/SickChill#5594]
I'd like to propose implementing a "None/Noop" Post Processing Method.

The use case where I see this being useful is where you have Post Processing Extra Scripts configured that you would like to exclusively handle all the post processing with.

In this situation you want to trigger the Post Processing in order to call your Extra Scripts, but you don't want any of the existing/normal Post Processing Methods to be called.

**Comment by BenjV** [comment]
Just use the "Move" qualifier and nothing else.
Then your own postprocessing can act on that location instead of the location your downloader puts the files.

**Comment by WebSpider** [comment]
What @benjv said.

**Comment by cewood** [comment]
> Just use the "Move" qualifier and nothing else.
> Then your own postprocessing can act on that location instead of the location your downloader puts the files.

This misses the point of not breaking any active downloads/seeds.

Having a post processing option to only run a script would be a very logical option IMO, and I would hope that someone could see this and reconsider.

**Comment by BenjV** [comment]
I am afraid that you are missing the point yourself.
If you want to keep seeding you have to choose "copy" instead of "move" because SickChill has no knowledge of seeding goals and when they are satisfies.
And with the copy option you can still let your own postprocessing act on the copied files and let the original files keep on seeding.

If it would be done as you suggested then your own script would also be called the moment the download is completed and not the moment the download has reached its seeding goal.

**Comment by cewood** [comment]
> If you want to keep seeding you have to choose "copy" instead of "move" because SickChill has no knowledge of seeding goals and when they are satisfies.
> And with the copy option you can still let your own postprocessing act on the copied files and let the original files keep on seeding.

Doing a copy is not ideal, as then I'd have files to delete later on, and I'd really like to avoid the risks associated with that.


> If it would be done as you suggested then your own script would also be called the moment the download is completed and not the moment the download has reached its seeding goal.

You're entirely correct, but since my script calls the torrent client to move the files, it does this in a safe way without breaking seeding.

I still think there's a valid use case for a post processing option that has no action but to call a script, which then handles all the post processing.

**Comment by BenjV** [comment]
> Doing a copy is not ideal, as then I'd have files to delete later on, and I'd really like to avoid the risks associated with that.


I cannot see any risk here because you already have a copy of the files.

> You're entirely correct, but since my script calls the torrent client to move the files, it does this in a safe way without breaking seeding.


It seems to me that doing so, SickChill does not know anymore where the files are and will alway keep them in the "fetched" state. This would not be desirable in my opinion because SickChill will be constantly keep on searching for those fill to complete.

My suggestion would be as follow.

Most torrents client can move files when then the seeding goals are met, so use this and add also a minimal time limit to the seeding goals.
Set this time limit higher then the post-processing frequentie of SickChill so you are sure SickChill has a copy of the files before the seeding goals are met and the files moved by the torrent client.

Make a little script that runs on say a weekly base to cleanup the folder (and subfolder) where the torrent client copies the files to.

**Comment by WebSpider** [comment]
I'm actually doing almost the same myself, other than I'm not using copies, but using hardlinks. One version in the location to seed from, one in the location for the post processor. Then apply the same logic @benjv suggest, presto!
