### ISSUE TITLE
Notification to run after post processing

### ISSUE THREAD

**Issue by rsouthgate** [SickChill/SickChill#5597]
more a feature request than a bug but in my setup I have post-processing enabled using MOVE method. But Kodi is notified of the new file after download yet the file is not there yet since it hasn’t been moved... is there any way of notifying kodi AFTER post processing?

**Comment by consenti** [comment]
This would also solve my problem with Plex notifier.  The Notification seems to run after each file postprocessed.  Since the plex notifier triggers a scan on plex after each file, there are files in my postprocessing batch that haven't completed copy or move.  Moving the Plex notification to the end of the batch will eliminate this problem because all files will be in their proper place before plex starts a scan.
