### ISSUE TITLE
Add “Preferred Words”

### ISSUE THREAD

**Issue by loungebob** [SickChill/SickChill#5629]
There is a similar feature request but with a STALE label and I don't know what that really means.

Anyway, since AMZN, NF, DCU, Disney+ etc. are not avail under quality settings, could you add a preferred words setting where one can more clearly define what e.g. WEB-DL is being looked for?

Or how else do I tell SC that the final quality I’m looking for is AMZN WEB-DL but until avail I’ll take the original networks web release as well?

**Comment by loungebob** [comment]
That would only get me AMZN releases. If there is none, there would be no download at all...
Preferred, not required.

**Comment by markprins** [comment]
Came here to create an issue as well. Would also love this as it is a means to put in a preference for audio options. I would us it for terms  like DD, DDP, 5.1, TrueHD as to exclude releases which are just 2.0 or use AAC (but do not put it in the release name).

Another option would be to handle this in post-processing and using mediainfo for example to determine if it is multichannel, and if not, send a 'failure'. This would however be _after_ the download and therefor a waste of bandwidth.

I agree with Loungebob that this is in fact _not_ the same as using the required word as search terms might differ and you might not want to exclude.

**Comment by BenjV** [comment]
If audio information like  AAC or 2.0  is not in the release name how could SickChill determine what audiostream that video contains?
SickChill does not download every available video on the internet and analyse its contents.
It just searches for filename and based on that information downloads the best match.

**Comment by markprins** [comment]
I think you must re-read my post as I think you might have misread it.

I'm seeing two different scenario's:

**Option 1** - Provide "preferred" keywords in SickChill

This would introduce an additional field which contains comma separated values on which SickChill can match.
These are preferred and not required, which would mean that when sickchill normally finds multiple releases, it would give preference to files that match the "prefered" keywords 
(this as opposed to 'required' which could result in 0 results).

As a quick example:
```
preferred = ['dd', 'ddp', '5.1']
found_releases = [
 'Some Serie 1080p - S01E01 - WEB-DL, 
 'Some Serie 1080p - S01E01 - WEB-DL AAC', 
 'Some Serie 1080p - S01E01 - WEB-DL DDP5.1'
]
[ release for release in releases if [pref for pref in preferred if pref.lower() in release.lower()] ]

results in:
['Some Serie 1080p - S01E01 - WEB-DL DDP5.1']
```

This does not download every available video.

**Option 2** Let a post-processing script do the heavy lifting

In this case, I'm going to assume option 1 will not be implemented.
We then could handle it in a post-processing script, which could, after downloading and extracting the file which was handled by the downloading application like sabnzbd for example.

After this we have downloaded what SickChill _thinks_ is the best option. So in the example from option 1 it would have probably downloaded the first file in the list.

The postprocesser could invoke an application like 'mediainfo' to determine if it is acceptable. If it is not, it would trigger a 'failed' to sickchill. SickChill would then mark it as failed and try the next one. This one is an AAC as well, so it downloads it again, processes it, and then marks it as failed. The last one is ok and it won't send a 'failed' to SickChill anymore.


Based on the above example, option 1 would be the most efficient.

And as can be determined from above example, when the first item in the releases list would actually be a ddp5.1 release, that release would not be used, and the other which did have the DDP5.1 in there would be downloaded instead.

When, using the preferred list, a list with 0 items would be returned, it would ignore the prefrerence and download that first one instead.


Option 1 would be fully compatible with what loungebob wanted

**Comment by BenjV** [comment]
I did not misunderstood, you wrote something different then what you want.
Your post states:
[quote]
as to exclude releases which are just 2.0 or use AAC (but do not put it in the release name).
[/quote]
If it is not in the release name SickChill cannot determine which audiostream is in the video without downloading it.

**Comment by markprins** [comment]
Well, I still read it different than you did (taking into account what the feature would do), but I have updated my comment to be more explicit in what I meant. Hope its more clear now.

Fact remains that it would be a nice feature to have

**Comment by loungebob** [comment]
As far as I understand, it’s actually quite easy to go the mediainfo parsing way and it’s already being done with other tools. All that needs to be done is for SR to download the first piece of the torrent file (at least it works with mkv) and read the metadata and then apply filter criteria.
That wont work for rar-ed releases, they could only be done in post.
Fact is, the way SR works now doesnt cater at all to the developments in video and audio quality releasing since NF/AMZN are not the only kids on the block anymore.
The very least a “preferred words” option is needed.

**Comment by loungebob** [comment]
Looks like I need to get another solution. The way SR works now I basically download the whole internet and sort it out locally. This is highly inefficient. Especially since an easy “preferred words” option would fix it.

**Comment by markprins** [comment]
At the time of my latest comment I decided to implement it myself (and to ignore benjv’s  remarks ;).

As you can see in the mentioned pull request it will probably be available sometime soon when it gets approved. I have it running locally for some time now and it works perfectly for me.

**Comment by loungebob** [comment]
Thanks, that would be great! I dont understand how this is not generating more interest. How do others handle the quality issue?

**Comment by loungebob** [comment]
So, thanks for the “preferred words” option. I may have not thought this through cause it does not work for me as I expected. I was looking for something along the quality settings line.
E.g. if a preferred word is AMZN SC would ultimately download this as a final quality if it is not already avail during the first scan where SC downloads whatever else fits the the other criteria. As it is now, if SC doesnt find AMZN during the initial search but another file fits the rest of the requirements, it’ll download that and mark it as completed and be done with it.
I guess thats how “preferred” works. 
Any chance we can get more quality settings or customizable quality settings?

**Comment by markprins** [comment]
Yeah, I get what you're saying. I realised myself that there are situations (eg: when there are not many versions available yet) that it might not find the items. When re-reading your initial post (with the context you just provided) it makes sense what you expected.

Implementing this feature was my first contribution to the sickchill project, so I'm a little more into how it works internally. What you suggested is indeed an approach that would help. However it would be a much larger change. Right now it just 'hooks into' the moment when the results are determined, and then tries to find either one of the preference options, and ranks them. If it can't it leaves it alone. This is a fairly transparent feature which would not impact the workings of sickchill.

When going towards what you suggest, it would entail a lot more. A few things that would be required are: ways (for the user) to add words, ways to order them or give them preference over others, might need ways to determine which are equal or synonymous  (DD2.0 == DD2 and DD51 == DD5.1  and you could argue that DD2.0 == DD5.1). Searches should be re-triggered. And the internal comparison for current audio and already donwloaded audio should be done (it may not accept a new file if an already higher quality audio version exists). And lastly there is the question of wether AudioQuality settings should trump VideoQuality settings or vice versa.

Consider having quality for "Allowed": HDTV, WEB-DL, 2160p
And having "Preferred": WEB-DL, 2160p

And for audio "allowed": DD, DD+, DD5.1, TrueHD, Atmos
And for audio "preferred": TrueHD, Atmos

And it has downloaded a release with: "1080p HDTV DD+ atmos"
Now it comes across a release: "1080p WEB-DL DD"

Considering the video quality it should download it as WEB-DL is preferred
Considering the audio quality it should NOT download it as DD is lower than Atmos  

People could have multiple expectations for this scenario. Right now I'd expect either one of three might be possible:
1. Video should trump  audio (the WebDL will be downloaded, audio will only be considered if video is higher as well)
2. Audio should trump video (the Atmos version will be kept, no action is taken until a higher video quality has an higher audio quality as well )
3. only if both video and audio are better it should be downloaded (the current version will be kept untill both video AND audio are from a higher quality. eg: a WebDL with TrueHD and Atmos would only be an option)

Thinking of it, there might be two more expectations to consider:
4. Audio will be considered if the video quality is equal or greather than what is currently downloaded
5. Video will be considered if the audio quality is equal or greater than what is currently downloaded

The strategy here would be user dependant entirely because taking myself as an example I would probably prefer an atmos version in HDTV format. Even when a WebDL, 2160p or BluRay in DD5.1 is available.


I will give this some more thought, and maybe dive into the sickchill code some more, but as of right now, my guess is that it would take too much of work to get it right.

**Comment by BenjV** [comment]
You would have to create a user interface with a decisiontree with all possible combinations of source, resolution, videocodec, biterate, audio codec and releasegroup.

And because normally people want another version if the combination they prefer is not available. 
So you also have to add lots of fallback scenarios and some kind of expire time when they will fallback to other combinations of all of the above parameters.

Good luck with designing and implementing this.

**Comment by loungebob** [comment]
Not sure how, yet. But it needs to do better than it does now. The whole automation concept works less and less since the development in the way content is released and the shift in the way quality is being labeled is basically ignored with the current quality settings. My manual input has increased disproportionally in the last 2-3 years. Ir should be the other way around. Why is it so hard - and I ask this, cause I couldnt do it myself - to implement more quality settings? Couldnt SC just download the first block of an e.g. mkv torrent, have mediainfo read the stats and then apply quality settings I defined somewhere and if it matches, download the torrent? Not just use the filename as metadata source? I realise that wont work for nzb/rar files but I seriously could live with SC having to download those completely first and then check quality requirements during post-process. and repeat if necessary. That way is still better than the current state where I basically have to download all of the releases and then manually sort through them or use the restrictive “must contain” method where everything that does not fall into those criteria needs to be done manually. Did that make any sense?

**Comment by BenjV** [comment]
Does not work for Nzb's and torrents of course and that are the only sources available on the web.
They have the be downloaded in full before they could be analysed, before that you only have a random set of datablocks.

And maybe you should read the comment of both @markprins and myself, then you could see how difficult this is.
If you could come up with a functional description on how to do it, then people with programming knowledge could tell you if it is possible to implement or not.
But shouting that it should be possible without a clue how, does not help.

**Comment by loungebob** [comment]
First of all, no caps, so no shouting. And second, that’s exactly how things get invented and great ideas become alive. I dont need to know how it should be coded or implemented, I just have to express the need for it. Everything else follows.
Having said that, I wonder how torrents can be streamed or I can manually query mediainfo on a torrent video that literally just got added and has only downloaded a few blocks if you’re statement that the torrent has to be downloaded in full before this can be done oughta be true?
I mentioned how this could be done for nzb files above (download completely, apply quality settings in post). I still think, complete media metadata can be pulled from a torrent without having to download it first. But maybe I’m wrong. In any case, SC/SR has been basically working the same way for the last 6 years I’ve been using it. Everything else around it changed. New delivery methods, new streaming services, new audio/video codecs and so on. It’s not hard to guess that maybe SC should include more granular quality settings if it wants to stay relevant.

**Comment by loungebob** [comment]
@markprins Yes, exactly that. I realize this would mean a lot more options to chose from in quality settings and even decision trees but how is that a bad thing? It might be more work initially for the user but once set properly, it means a lot less work going forward. All I know, nowadays I skip SC and download whole RSS feeds and then throw away 90% of downloads. This cant be the way. There needs to be more intelligence in this. And I dont mean this as an insult. There was no need for it up until a few years ago because there were fewer sources and fewer releases. Now you get like 12 releases per show/movie and there is need to specify which one you want beyond just looking at filename. Which has become less relevant because the scene really doesnt get it. How would they, they’re still coming to terms with the acceptance of WEB-DLs. Duh.

**Comment by miigotu** [comment]
Quality settings aren't being ignore, there is just not a better way to do it so far. It isn't that automation is getting worse, it's that you are getting more picky.

There is a way to mark an episode as allowed rather than preferred and look for a better match, by checking if it meets both preferred words and preferred quality by using the release name, but I'm sure that won't be good enough. What you are looking for is an AI.

**Comment by markprins** [comment]
If you're fine with the situation of downloading a whole EP and then decide if it's useable for your situation there are other options (I had thought of it before, but didn't consider it being a solution because it would be more of a workaround).

You could hook in to the postprocessing and do evaluation of what is downloaded there. So it will download the episode, then run the post-processor, this one evaluates if the file is correct. It will run the file through MediaInfo (ignoring "sample" files), check the relevant fields if it is allowed or not. If it is acceptable, it will pass. If it is NOT acceptable, it will trigger a 'failed' and communicate this back to SC. SC will then mark the release as 'failed' and will try another one. 

This could be a solution to your problem, but will also introduce a lot of new problems. Most notably because what mediainfo will report back can be a multitude of different settings or information parameters. Various options could be considered (for example:  DD could be considered as DD2.0 and DD5.1. But also stuff like (totally randomly chosen) which version of MKVmerge was used and such). If setting up SickChill is hard (and a lot of work) when determining quality (and/or audio options), moving this logic to the post processor will be even more work.

Another problem that may/will arise is that mediainfo could be out of date. I have a machine which has media info running, but does not report that there is an Atmos stream. Whereas another system correctly identifies the Atmos stream. So the script would also be dependant on media-info being up-to-date. All in all, going the post-processor way would probably be a better location as you're wishes are dependant on what the file actually is instead of what the release describes. But that doesn't make it a lot easier :) 

To circle back to you're statement "But how is that a bad thing". It is not a _bad_ thing per se. It's just that _I'm_ not really looking forward to weeks or months of work ;) I introduced the feature, because I really really wanted it. And it was just an afternoon worth of work (not taking into account tweak-ups after pull request feedback and such). And it solves 80% of my problems. Going from 'one afternoon' to 'multiple days of work and a lead time of multiple weeks or months' for a feature that solves the remaining 20% of the problems doesn't feel right.

And as BenjV said, it requires a lot more up-front (technical) design. It starts to sound much more like my daywork than leasure ;)

**Comment by BenjV** [comment]
And I predict almost nobody will want to use it because it will download lots of files which will be deleted and not viewed.
And the suggestion that only a part of the file could be downloaded to analyse its contents is just not possible.
It would mean building special torrent and nzb clients that download first the section of a file that hold the metadata and that is also depending on the container  used (e.g. mkv, mp4, avi, xvid etc.)
