### ISSUE TITLE
Git Problems on Synology? Read this

### ISSUE THREAD

**Issue by Mickroz** [SickChill/SickChill#5821]
There is a problem with the git package from SynoCommunity.
https://github.com/SynoCommunity/spksrc/issues/3843

Login with ssh, sudo to root with "sudo su -" and run:
```
git config --system http.sslCAInfo /etc/ssl/certs/ca-certificates.crt
```
This fixed it for me, you could try running it as your normal user with sudo, haven't tried that.

**Comment by miigotu** [comment]
Wish I could sticky this 🤷‍♂️

**Comment by cristoforo** [comment]
Thanks, worked like a charm (not with default user though).
One line command:

`sudo git config --system http.sslCAInfo /etc/ssl/certs/ca-certificates.crt`

**Comment by tinyhands01** [comment]
Does not work.  "Failed to update Git. This package is not published by Synology Inc."

**Comment by hairyhippy** [comment]
Any news?  Not working here either.

**Comment by miigotu** [comment]
Nobody said anything about updating git, but you could install Synology's package for it.

**Comment by RobotWithHumanHair** [comment]
FWIW, I just had this problem today and @Mickroz's solution worked for me.

**Comment by djpoulet** [comment]
Hello all, I've had this error since a while now and @Mickroz's solution with @cristoforo's single line command worked like a charm. Thank's all.

**Comment by tinyhands01** [comment]
@miigotu - That _was_ the Synology package.  Nobody said anything about updating git, but if an older version of git won't pull, step 1 is usually to update git.

Nothing worked to update the package, so I uninstalled it and installed the .spk matching my architecture.

**Comment by miigotu** [comment]
> I have created a new SickChill package for Synology with a fix for issue #5821
> 
> It can be downloaded here:
> https://github.com/BenjV/SYNO-packages/raw/master/SickChill%20noarch%20V1.3.spk
> 
> It is save to install it when SickChill is already installed, because it wil just upgrade the Synology package and do a git pull for the latest SickChill code from github.
> The database and config.ini and all the cache items will not be affected.
> 
> @miigotu
> Maybe you can change the link in #6230 to https://github.com/BenjV/SYNO-packages
> Then people can look themselves for the latest package instead downloading an old version.

**Comment by hairyhippy** [comment]
I appreciate that you've closed this but I get a failed to run package message once this is installed.

I installed the previous version via SickBeard Custom from the Synology Community package centre.  Where as I noted this one installed a "new" packaged named "SickChill".

**Comment by miigotu** [comment]
Maybe you did not have the correct git or python installed?

**Comment by miigotu** [comment]
Please try my new package: https://github.com/SickChill/sickchill-synology/releases
Source scripts: https://github.com/SickChill/sickchill-synology/tree/sickchill/spk/sickchill

**Comment by hairyhippy** [comment]
Hi miigotu

Still getting failed to run package.
Git is version 2.24.1-12
Python3 3.5.6-8
Python 2.7.14-19
DSM is 6.2.2-24922 Update 4

**Comment by miigotu** [comment]
Can you ssh into the box and try starting the service on the command line and see why it fails?

**Comment by hairyhippy** [comment]
What is the command line string?

**Comment by miigotu** [comment]
I think it's `sudo -i synoservicecfg –start sickchill`

**Comment by miigotu** [comment]
Try this package, I found an error:
https://github.com/SickChill/synology-sickchill/releases/tag/20200523-0

**Comment by ErinVoid** [comment]
`Starting sickchill command /volume1/@appstore/sickchill/env/bin/python /volume1/@appstore/sickchill/SickChill/SickBeard.py --daemon --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/config.ini --datadir /volume1/@appstore/sickchill/var
/var/packages/sickchill/scripts/start-stop-status: line 49: /volume1/@appstore/sickchill/env/bin/python: No such file or directory`

In `/volume1/@appstore/sickchill` there is `app`, `SickChill and `var`. No `env`.

**Comment by miigotu** [comment]
Thanks, I will check that the virtual env is created.

**Comment by miigotu** [comment]
@ErinVoid That specific error should be fixed in https://github.com/SickChill/synology-sickchill/releases/tag/20200603-0

**Comment by ErinVoid** [comment]
Overwriting, I go this `Starting sickchill command /volume1/@appstore/sickchill/env/bin/python /volume1/@appstore/sickchill/SickChill/SickBeard.py --daemon --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/config.ini --datadir /volume1/@appstore/sickchill/var
/volume1/@appstore/sickchill/env/bin/python: can't open file '/volume1/@appstore/sickchill/SickChill/SickBeard.py': [Errno 2] No such file or directory`

Uninstalling then installing 20200603-0 `Starting sickchill command /volume1/@appstore/sickchill/env/bin/python /volume1/@appstore/sickchill/SickChill/SickBeard.py --daemon --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/config.ini --datadir /volume1/@appstore/sickchill/var
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2n  7 Dec 2017) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.
[Errno 13] Permission denied` but the Sickchill starts. `sudo -i synoservicecfg --status pkgctl-sickchill` produces
`Service [pkgctl-sickchill] status=[enable]
required upstart job: 
	[pkgctl-sickchill] is start. 
=======================================`
on accessing http://my.ip:8081/ the following is displayed `Looks like we do not have enough disk space to render the page! {error}`
Not sure this wil help buy the only reference I can find on the Internet to that message is [https://github.com/SickChill/SickChill/commit/0d4863918a8bda7dc1724f3a2ae884b6ed37d197](url) in `webserve.py`.

**Comment by miigotu** [comment]
@ErinVoid looks like we are just one step away from the fix =P
Seems sickchill cannot write to `/volume1/@appstore/sickchill/SickChill/gui/slick/cache/mako`

**Comment by ErinVoid** [comment]
Installing over the top `Starting sickchill command /volume1/@appstore/sickchill/env/bin/python /volume1/@appstore/sickchill/SickChill/SickBeard.py --daemon --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/config.ini --datadir /volume1/@appstore/sickchill/var
/volume1/@appstore/sickchill/env/bin/python: can't open file '/volume1/@appstore/sickchill/SickChill/SickBeard.py': [Errno 2] No such file or directory`
New install same error `Starting sickchill command /volume1/@appstore/sickchill/env/bin/python /volume1/@appstore/sickchill/SickChill/SickBeard.py --daemon --pidfile /volume1/@appstore/sickchill/var/sickchill.pid --config /volume1/@appstore/sickchill/var/config.ini --datadir /volume1/@appstore/sickchill/var
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2n  7 Dec 2017) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.
[Errno 13] Permission denied` and same message in browser. 
On the -1 install `/volume1/@appstore/sickchill/SickChill/gui/slick/cache` does not exist and is owner by root:root. Adding the cache folder gets `[Errno 13] Permission denied: '/volume1/@appstore/sickchill/SickChill/gui/slick/cache'`
Running `sudo chown -R sc-sickchill:sickchill ./SickChill/` in `/volume1/@appstore/sickchill/` solved the issue for me.

**Comment by miigotu** [comment]
```bash
ls -ld /volume1/@appstore/sickchill/SickChill/gui/slick/cache
ls -l /volume1/@appstore/sickchill/var
```

**Comment by ErinVoid** [comment]
As I said, the last line solved it for me. Seems like a permissions issue on `/volume1/@appstore/sickchill/SickChill...`. the `chown` line solved the problem.

**Comment by miigotu** [comment]
Yeah, I had the `ln -s` backwards and I just added some more code to it. Once I debug it again I'll post a new package that handles updates.
