### ISSUE TITLE
SickChill fails to restart

### ISSUE THREAD

**Issue by YoYoost** [SickChill/SickChill#5871]
Branch/Commit: Master / 4dedd01
OS: Debian 9
Browser: Firefox/Chrome

I used the systemd runscript to (auto)start SickChill however when I press restart of when SickChill updates it won't restart. When I start the service using ```$ systemctl start sickbeard.service``` it starts fine and is actually updated.
Unfortunately I cannot provide logs as SickChill shuts down fine and after that the service just stays terminated.

Is there a setting I missed or does anyone recognize this?

**Comment by miigotu** [comment]
When running as a service you need to set it to autostart  and autorestart

**Comment by BenjV** [comment]
@miigotu 
That's only on Windows not on Linux.

@YoYoost 
Pressing restart will try to start SickChill normally (not with the command  "systemctl start sickbeard.service"), so that is the difference.
I don't know you configuration but maybe SickChill cannot find itself or there are right issue's, but for sure it will not start the way you start it normally.

**Comment by miigotu** [comment]
@BenjV I use Linux.... SC will kill itself and let the service manager bring it back up

**Comment by YoYoost** [comment]
I fixed this by adding the following under the ``` [Service] ``` systemd directive:
```
RemainAfterExit=no
RestartSec=5s
Restart=always
```
I still think BenjV is correct in that my setup somehow doesn't have the right permissions or cannot find itself but this is at least a workaround.
