### ISSUE TITLE
Feature Request: add movies in addition to adding tv shows

### ISSUE THREAD

**Issue by Viss** [SickChill/SickChill#5902]
The sources the torrents come from have a variety of content in addition to tv shows. It would be pretty amazing to say "get the bluray rip of this movie" so that it behaves the same way as with tv shows.

**Comment by Wally73** [comment]
for movies there are other programs , sickchill is for tv shows

**Comment by theskillwithin** [comment]
What are the programs for movies?

**Comment by Viss** [comment]
there are several, but since I'm running sickchill on a synology nas, the suggestion of "just run another tool for movies" is pretty dismissive of the feature request and not the kind of response someone who is very happy with sickchill would appreciate. considering the same torrent sites serve a multitude of different torrents in addition to tv, it would likely improve the user-base of sickchill if it could be used to fetch 'whatever the user asked for, so long as the description matched the right ways'. There's no reason the existing logic for discovering torrents for tv shows couldnt be slightly modified to include other torrents using the exact same string matching and selection tooling.

**Comment by BenjV** [comment]
The big difference of searching movies is that a movie is a one off and tv shows are seaquels 
So you only have to add a tv show once and finding the episodes can be done by SickChill.
That's the main purpose of the program, getting rid of adding and searching every episode.

If you know the movie you want you can easily search the movie yourself versus searching it via an application.
And if you don't want to do that, use one of the dedicated programs like Radarr for that.

By the Way:
Searching for movies is a lot more complicated because most tv show have a very standard naming convention on the web but lots of posted movies are not compliant to the naming conventions and so they are very difficult to find by a program.

Also in my humble opinion it is very rude to more or less demand (instead of politely asking) extra functionality from people who spend a great amount of effort to create and maintain an application, on the base that you **think** it would be easy to add this functionality.

So my suggestion would be, do a pull request, add the functionality and I am sure that if it meets the quality standards it will be added to SickChill.

**Comment by GreatMaker** [comment]
take a look at:
https://github.com/CouchPotato/CouchPotatoServer/
