### ISSUE TITLE
[Feature request] option to set audio quality to at least 5.1

### ISSUE THREAD

**Issue by heula** [SickChill/SickChill#5971]
there are several video quality options we can set but no audio quality options.
If possible I would like an option to set audio to any sound with at least 5.1 surround sound.
The media info shows often how many channels audio the video contains. Perhaps it can read that before downloading?

Thanks

**Comment by deepseth** [comment]
I think this is a superb idea. Especially since I just got a 5.1 sound system at home and now fully appreciate how much better it is than stereo, and get annoyed every time I watch something that is 2.0 instead of 5.1.

That said, I think this needs to be done by the indexers rather than by SickChill. From my last time looking at an indexer code, it had an option to download a small segment of the post to check if it was password protected, and to validate the media type. If not using post headers (so just, filename strings) to determine what media type & quality a post is, it was using that mechanism to validate.

As such, until an indexer starts tracking that information and exposing audio quality as a 'thing', SickChill can't really filter by that either.

SickChill is an intermediary between an index and a download tool. It reads an index, filters down to what a user has requested, and feeds into the downloader. If you can get indexes to expose audio quality, SickChill can filter on that.

Asking for SickChill to start implementing downloading functions is (IMO) out of scope, and I wouldn't be surprised to see this either languish and get closed as stale, or get tagged WONTFIX and closed.

**Comment by ulrick65** [comment]
I agree, awesome idea...unfortunately I agree with the rest of what @deepseth said as well.  Not sure how SC could do this, but sure would be nice.

**Comment by miigotu** [comment]
Yeah, this is not quite possible. The logic gets insanely complex and it would be nearly undoable to make it configurable to the point where the user gets the desired results without moving to an ai based approach. You could add a required word like "5.1|7.1|8.1|10.1" with all the strings you are ok with accepting piped as 1 require_word
