### ISSUE TITLE
Always refreshing library at startup

### ISSUE THREAD

**Issue by NilsNojje** [SickChill/SickChill#5982]
Branch/Commit: master
OS: Ubuntu 18.04.4 LTS
Browser: CHrome
What you did: n/a
What happened: Every time Sickchill starts up, a full refresh of library is done.
What you expected: Unnecessary to perform every startup.
Logs: NA

**Comment by BenjV** [comment]
Why would that be unnecessary?
The principal of ChickChill is that is always is running and on a scheduled base has activities like searching and postprocessing.
If you stop SickChill it has to create a know state after starting again.

**Comment by NilsNojje** [comment]
> Why would that be unnecessary?
> The principal of ChickChill is that is always is running and on a scheduled base has activities like searching and postprocessing.
> If you stop SickChill it has to create a know state after starting again.

I've noticed this behavois lately as my whole VM got unresponsive during the refresh. Wasn't like that before. I agree of keeping the state up to date, but if I for say manually perform a refresh and then restart SickChill, it will do the same refresh right away.

The state should be saved anyway, so this is why I'm wondering is this is how it's meant to be?

**Comment by BenjV** [comment]
Normally SickChill gets a regular updates form Tvdb for all shows that have changed.
That is just one message and the SickChill filters out the show you are interested in.
But if you stop SickChill it has not way to know if you missed one or more updates and so a complete refresh is done which is a lot more effort because all you shows must be queried one by one to get the latest state.
The fact that you VM got unresponsive can have a lot of reasons, maybe you could lower the priority of SickChill or maybe you have a network issue which is one of the biggest reasons for unresponsive behavior.

**Comment by miigotu** [comment]
It's set to do that because tvdb's updates API is broken.
