### ISSUE TITLE
Bug Found With Mass Updater & Series.xml files

### ISSUE THREAD

**Issue by cadmuslabslex** [SickChill/SickChill#5987]
Not sure if this is a Windows 7 issue, I didn't test on Windows 10 or if its a SickChill issue but here is a heads up. 

When doing a massupdate if your series.xml files are set to hidden SickChill will report back a permissions issue. 

Saying: "Unable to write file to X:\TV\TVShowName\series.xml - are you sure the folder is writable? error 13 : Permission denied. 

However, if you go into the folder settings and set the series.xml file back to not being hidden, whala it works fine. 

This has been driving me nuts for months, preventing my shows from updating and I just figured it out today. 

So I thought I would share in case anyone else was having a similar issue.

**Comment by BenjV** [comment]
Are you sure?
Because python does not do anything with the windows attribute 'hidden".
And error 13 means just what it says (permission denies) and does not read the attributes at all.

Maybe you changed the ownership to admin privileges when you changed the attribute.
The only other possibility is that the file is open by another program.

**Comment by miigotu** [comment]
This is not a bug, it's just how the win32 API works.
https://stackoverflow.com/questions/13215716/ioerror-errno-13-permission-denied-when-trying-to-open-hidden-file-in-w-mod
