### ISSUE TITLE
Startup issue - ImportError: No module named ipaddress

### ISSUE THREAD

**Issue by crowaust** [SickChill/SickChill#6032]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: Master
OS: windows 2k8r2
Browser:chrome
What you did:updated sickchill
What happened:update failed, sick chill no longer starts
What you expected:
Logs:
```

C:\SickRage>git remote set-url origin https://github.com/SickChill/SickChill.git


C:\SickRage>git fetch origin

C:\SickRage>git checkout master
Already on 'master'
Your branch is up to date with 'origin/master'.

C:\SickRage>git branch -u origin/master
Branch 'master' set up to track remote branch 'master' from 'origin'.

C:\SickRage>git reset --hard origin/master
HEAD is now at 49c74620f is_ip_private() should handle IPv6 addresses (#6030)

C:\SickRage>git pull
Already up to date.

C:\SickRage>SickBeard.py
Traceback (most recent call last):
  File "C:\SickRage\SickBeard.py", line 67, in <module>
    import sickbeard
  File "C:\SickRage\sickbeard\__init__.py", line 41, in <module>
    import sickchill
  File "C:\SickRage\sickchill\__init__.py", line 5, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "C:\SickRage\sickchill\show\indexers\__init__.py", line 22, in <module>
    from .handler import ShowIndexer
  File "C:\SickRage\sickchill\show\indexers\handler.py", line 31, in <module>
    from sickbeard.tv import Show
  File "C:\SickRage\sickbeard\tv.py", line 48, in <module>
    from . import db, helpers, logger, network_timezones, notifiers, postProcess
or, subtitles
  File "C:\SickRage\sickbeard\helpers.py", line 31, in <module>
    import ipaddress
ImportError: No module named ipaddress

C:\SickRage>
```

**Comment by skalvaro** [comment]
Just updated and encountered the same issue.

**Comment by stynoo** [comment]
Same issue encountered in an iocage jail on FreeNAS
The commit that caused it is https://github.com/SickChill/SickChill/commit/49c74620ffcc123d6d8a347f7e25fd946154f270

**Comment by Xx-Ness-xX** [comment]
Having the same issue after https://github.com/SickChill/SickChill/commit/49c74620ffcc123d6d8a347f7e25fd946154f270 update. At first I thought it was my NGINX reverse proxy, but restarting it did not help.
```c:\SickRage>SickBeard.py
Traceback (most recent call last):
  File "C:\SickRage\SickBeard.py", line 67, in <module>
    import sickbeard
  File "C:\SickRage\sickbeard\__init__.py", line 41, in <module>
    import sickchill
  File "C:\SickRage\sickchill\__init__.py", line 5, in <module>
    from .show.indexers import indexer, ShowIndexer
  File "C:\SickRage\sickchill\show\indexers\__init__.py", line 22, in <module>
    from .handler import ShowIndexer
  File "C:\SickRage\sickchill\show\indexers\handler.py", line 31, in <module>
    from sickbeard.tv import Show
  File "C:\SickRage\sickbeard\tv.py", line 48, in <module>
    from . import db, helpers, logger, network_timezones, notifiers, postProcessor, subtitles
  File "C:\SickRage\sickbeard\helpers.py", line 31, in <module>
    import ipaddress
ImportError: No module named ipaddress

**Comment by miigotu** [comment]
git pull and start SC up again

**Comment by crowaust** [comment]
> git pull and start SC up again

changes downloaded and applied, now starting normally.

**Comment by brianjmurrell** [comment]
Isn't the solution to this that one needs to `pip install ipaddress` or install the appropriate RPM, etc. etc., rather than vendoring it right into SC?

**Comment by miigotu** [comment]
@brianjmurrell not currently, no. Everything is bundled with SC, requirements isnt even used because it isnt packaged, since we have legacy packages that are modified.

**Comment by brianjmurrell** [comment]
How do you scale up all of this bundling/vendoring in terms of keeping up with upstream security updates?  Surely you'd rather spend more time making SickChill better than you would maintaining the bundled items in terms of patching them when their upstream fixes a security vulnerability.

I mean, I **really** hope you are paying attention to all of those upstreams to fix security vulnerabilities.

As much as the software world is making a move to bundling, this maintenance headache is the horror of vendoring/bundling rather than using bona fide libraries which are maintained and updated by their respective parties.  You essentially become responsible for the security if everything you vendor rather than leaving it to upstream and their downstream distribution mechanisms to manage.

There have already been actual cases of projects who see bundling as being the answer to all of their interop issues, but ignoring what they bundle and as a result their own software package, complete with vulnerable bundles become a security vulnerability in and of themselves.

Anyway, I'll get off my soapbox.

**Comment by miigotu** [comment]
Dude, every fork of sickbeard is done that way, and always has been. We update them as the updates come, and we would rather NOT have to do that. So if you have the skills to get away from that without breaking 100k SC installs, please do it for us.

**Comment by brianjmurrell** [comment]
I'm not sure you are going to be able to correct this situation without user intervention given the nature of the change, but as I am sure you know, the way this sort of thing is typically handled is with `pip` and `requirements.txt` to install and maintain the dependencies.

Because rectifying this is going to require an update that implements it to have the `pip` command run, I don't know if you can automate this or not such as to be transparent to users.  It's also possible that a users' distro can provide many of these dependencies.

But maybe the disruption is worth it so that you don't have to do [massive updates](https://github.com/SickChill/SickChill/compare/f9161da71a75dbabf83fd862bc4e46a0b4391352...694ca61) yourself.

Thanks for that update of all of those dependencies though.  Makes me feel like we might at least be up-to-date on potential security vulnerabilities.

**Comment by miigotu** [comment]
SC is not a module, it is a package.

**Comment by brianjmurrell** [comment]
I'm no python expert, but I don't think module/package makes any distinction on whether you `import` dependencies vs. bundling them.

**Comment by miigotu** [comment]
The distribution method does make a difference.

**Comment by brianjmurrell** [comment]
I don't think the python developers/ecosystem ever *expects* anyone/thing to bundle all of the third-party dependencies even in a package.  My understanding is that while, yes, a package is collection of modules, that usually means they are modules written by the same author(s) and released in the package.  It doesn't mean that it should bundle third party modules and those should be imported from their externally managed location, i.e. with `pip` or installed as distribution packages, etc.

But frankly, it seems like you aren't really terribly interested in unburdening yourself from the effort or **responsibility** of this issue.  I am just trying to help by suggesting how you can make this all less work for yourself, but you seem be wanting to put up reasons why you think you can't.

So I will stop beating this poor dead horse.

**Comment by miigotu** [comment]
@brianjmurrell The problem here is you are trying to explain to me how to distribute python packages like I am an idiot. If you have a solution, MAKE A PR and stop acting like you know something I don't.
