### ISSUE TITLE
Sickchill anime Search doesn't work

### ISSUE THREAD

**Issue by SiddLord93** [SickChill/SickChill#6074]
It's plain and simple the anime search doesn't work. 
I want to know if the function really works before i sent the logs.
Because I have sickchill running on 2 different setups. At home and at a friend of mine. Both the sickchill setup doesn't work when it comes to finding anime.(Synology dsm6.x)

Yes I did turn on the setting "this show is a anime" 
And I have a anidb account setup.

The problem is: Searching: one piece s21e23 but it has to be episode 923. 

So can anyone confirm if the setting "anime" works on sickchill 

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: synology ds214+ dSM 6.2.2-24922 Update 4
Browser: Firefox and chrome
What you did: searching for anime with sickchill
What happened:search failed because of the search string: one piece s21e23 
What you expected: correct match of anime search. One piece 923

**Comment by thargan81** [comment]
This is going to need your logs to review. I've a number of shows in Sickchill as anime and they work. I also added One Piece and it was able to find the four most recent episodes. Stalled slightly as one of the search providers timed out, but that's a temporary issue that's not down to SC.

**Comment by SiddLord93** [comment]
Ah thankyou for the fast comments! I will post the logs asap!

**Comment by SiddLord93** [comment]
![log](https://user-images.githubusercontent.com/60181233/76151990-ef1c1500-60ba-11ea-9f96-dc4304f9af1b.PNG)

**Comment by miigotu** [comment]
![image](https://user-images.githubusercontent.com/390379/76155840-ea0d9480-60bf-11ea-93a8-60d9134e24d0.png)
SC search works just fine:
https://nzbfinder.ws/api?apikey=****&episode=923&cat=5070&tvdbid=81797&t=tvsearch

nzbfinder has a broken maxage it seems, if you add maxage=600 to my url the results dont show up, but maage 1500 does (which doesnt make sense because the episode you are trying to get is somewhere around 90 days old). Either use an indexer who doesnt have this bug, or set your usenet retention in SC to a higher value.
