### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by 03397** [SickChill/SickChill#6158]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master f9161da71a75dbabf83fd862bc4e46a0b4391352
Database Version: 44.1
OS: Linux-3.4.6-x86_64-with-glibc2.2.5
Python Version:2.7.14 (default, Jan 11 2018, 08:24:40) [GCC 6.3.0]
SSL Version:OpenSSL 1.0.2k 26 Jan 2017
Browser:Chrome
What you did:
What happened:High Memory usage on My NAS around 1GB
What you expected:
Logs:
```
PASTE LOGS HERE
```
Guys, after using SichChill for a while my memory usage jumps to 1GB.
SichChill is ran on a QNAP nas with 4GB memory.

**Comment by BenjV** [comment]
As always that is most likely not a problem at all.

Qnap is a Linux box and on Linux the processes that have ended are not removed from memory but stay in memory until that memory is needed for active processes.
This is done on purpose by Linux to speedup things, when those ended processes are needed again and they are still (in otherwise unused memory) they start much faster.
And SickChill starts lots of processes who are after doing there job and then end, but as I said kept in memory by Linux afterwards.

The only way you can conclude that you have too little memory is when Linux start swapping out active processes to disk.

**Comment by 03397** [comment]
I understand what you are saying and you are right.
But my qnap at that time mounts a swap automatically and starts using.
This is a sign of low memory.
I think sickchill using 1GB is too much memory.

**Comment by BenjV** [comment]
My installation of SickChill on Synology and also on Windows has no memory problems at all.
It always is a few Mbytes and not even in the neighbourhood of a Gbyte.
So it cannot be a Sickchill issue.

**Comment by 03397** [comment]
My friend I know what I see. Sickchill consumes 1GB ram.
If this it is considered normal go ahead and close the ticket.

**Comment by BenjV** [comment]
In my environment it is very much less memory but I don't have a Qnap.
And closing an issue must be done by the issue opener self.

**Comment by miigotu** [comment]
Check the logs to see what SC is doing when the memory jumps. Likely it is trying to subtitle a show or scan a very large file that has errors.
