### ISSUE TITLE
aired order instead of netflix order

### ISSUE THREAD

**Issue by Impulse1337** [SickChill/SickChill#6181]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch: master
Commit: 50a2b16835064938d2a99129fca8744edcfb18a2
Database Version: 44.1
OS: docker
Browser: Opera
What you did: added serie (la casa de papel)
What happened: only 2 seasons showed 
What you expected: 4 seasons showed. 
![image](https://user-images.githubusercontent.com/7289057/78681680-57922800-78ed-11ea-838d-9420c3da037a.png)
![image](https://user-images.githubusercontent.com/7289057/78681730-62e55380-78ed-11ea-9d6a-afa198bd975e.png)

Is there any way to select another approach for SR to check the seasons? Because providers are using the 4 seasons layout, only SR is picking up the 2 seasons, and thus setting up the episodes wrong and even deleting them..

**Comment by miigotu** [comment]
I think you can set the show to dvdOrder in SC, and that does what you are asking. Netflix is just a label for it there for their "alternate order" which is called dvdOrder on the API.

**Comment by miigotu** [comment]
Actually that doesn't work. I'll have to dig into it, maybe they just don't have it documented yet.

**Comment by miigotu** [comment]
https://forums.thetvdb.com/viewtopic.php?p=174244#p174244

**Comment by miigotu** [comment]
https://forums.thetvdb.com/viewtopic.php?f=17&t=63756

**Comment by mikey0613** [comment]
Typical of TvDB... implement a "Feature" that screws up things, and that no one can access or use...

Apr, 8, 2020: "You are correct. Our apologies, but the flexible season orders are not exposed on the current API, but they will be in v4 which we are starting to build right now."

Apr 11, 2020: "We've just begun building it. It will be several months. Brand new API."

**Comment by miigotu** [comment]
Any update on this functionality in the api?

**Comment by BS3DP** [comment]
Can i just add, i found this issue when looking for a similar issue related to Futurama. The aired episodes are different to how nzb's are named as they follow the DVD episodes. Setting to DVD ordering does nothing. loaded the debug mode and it gets data for the aired episodes numbered but as soon as it goes into the DVD numbers, aired s1 has 9 episodes but DVD s1 has 13, it breaks and reports a 404 because the data it gets back from the API doesn't line up.

I can confirm that by checking the API results my self that the episodes returned by the API is correct when SickChill uses the https://api.thetvdb.com/series/73871/episodes/query?dvdSeason=1 and when checking the data it displays all the data from s1e1 to s1e13 for the DVD season.

Seems to me that there maybe some sort of bug causing the show season data to loaded from the cache and then checked? Im not sure but i know that deleting the show and then re-adding the show it doesn't give me a option to set DVD ordering so i would expect it gets the aired episodes caches them and then changing to DVD order doesn't pick it up, Or maybe its not checking the api response correctly? Im not sure im just spit balling here

**Comment by miigotu** [comment]
@BS3DP you sure it isn't scene numbering and not DVD order?

**Comment by BS3DP** [comment]
@miigotu I've just checked between scene numbering and the DVD order and it seems to kinda line up but there's still something odd going on. After looking up at some of the scene numbering stuff i did notice that some of the scene numbers were correct going into aired season 2 showing the first 4 episodes as really the last 4 episodes of season 1. But between DVD order being on or off, it seems to remove episodes entirely. 

Aired s2e4 is "Xmas Story" in the DVD order that's also s2e4 but now the remaining 4 episodes that are part of the season 1 on the DVD order that were displayed as part of season 2 aired when having DVD order off are now missing. Scene numbering and absolute numbering is whacked out from the end of season 2 because the system http://thexem.de/xem/show/956 doesn't have past s2 data but that doesn't explain why SickChill isn't displaying the remaining DVD season 1 episodes in season 1, it still displays the number of episodes bases on the aired seasons if that makes sense. Aired s1 is 9 episodes but DVD s1 is 13 episodes but even with DVD order, it still displays the aired number of episodes ie 9. 

Im trying to help and explain the best i can, from what i can tell SickChill isn't adjusting the seasons to reflect the correct DVD order. I can go though and label the episodes with scene numbering but it would be nice for SickChill to display the DVD ordered seasons into their correct season based on the DVD's. Aired season 7 is actually made up of DVD seasons 7 and 8, similar between aired season 6 joining DVD seasons 5 and 6

**Comment by miigotu** [comment]
@BS3DP Nobody releases nzb/torrents in dvd order. Just get xem to update futurama on their site

**Comment by digrouz** [comment]
Hello, I face the some issue with the same show, is there a fix in the end ?

**Comment by daanw1978** [comment]
With part 5 of Casa de Papel coming up in september, it would be really good to have a solution for this. It seems TVDB has the correct numbering in their 'Netflix order', so it should be a matter of having an option in sickchill to honour that?

**Comment by ejlkemper** [comment]
Hi, I am having the same issue with Star Trek Voyager, DVD order still shows aired order in show-list, after trying all kinds of settings day after day. Reboots, re-scans/Full update, nothing makes the show-list show the correct list as shown in TVdb DVD list?

**Comment by ghenry22** [comment]
DVD Order and Aired Order are different issues to this, in order to resolve this issue "Alternative Order" needs to be enabled as an option alongside aired & dvd order.  The Alternative order will return the netfilx order (or in the case of cartoons the correct episode ordering vs the ridiculous so called aired order that splits episodes into storyline segments).

**Comment by BKSteve** [comment]
Aired out DVD order don't work. It's a tvdb API issue

**Comment by miigotu** [comment]
> DVD Order and Aired Order are different issues to this, in order to resolve this issue "Alternative Order" needs to be enabled as an option alongside aired & dvd order. The Alternative order will return the netfilx order (or in the case of cartoons the correct episode ordering vs the ridiculous so called aired order that splits episodes into storyline segments).

Sure, get alternative order on API v2 from thetvdb, or add support and send a PR, and be sure to send a PR. We can only work with the data given to us.
