### ISSUE TITLE
Force Update Not Updating Airdates for Postponed Episodes

### ISSUE THREAD

**Issue by rutskiuk** [SickChill/SickChill#6234]
I've noticed that for one show that has been put on hold recently that SickChill won't update their airdates for future episodes which means that incorrect airdates are marking unaired episodes as wanted.

This means indexers are going to be hit with requests for non existent episodes and the show list incorrectly lists a completely downloaded show as incomplete
I had a look through the logs and it seems to show that because the episode is marked as wanted SickChill isn't updating the episode.
It also looks like even subsequent episodes currently unaired are also not being updated so each week various shows in the same situation will mount up wanted non existent episodes.

I can fix the problem by removing and re-adding the show but shouldn't this be resolved by a force update?

Branch: master
Commit: ddeceaaaa6ea1b01b4164d40008dedaa9fbb5e1b
Version: v2020.04.19-7
Database Version: 44.1

OS: Windows 10
Browser: Firefox
What you did: tried to force update a show to update its airdates
What happened: airdates are untouched
What you expected: airdates to be updated and episode status to be changed to unaired
Logs:
```
2020-04-19 22:55:42 DEBUG    SHOWQUEUE-FORCE-UPDATE :: Not touching status [ Wanted ] It could be skipped/ignored/snatched/archived
```

**Comment by ebaydan777** [comment]
it also looks like timezones are incorrect and it's showing incorrect time in sickchill

**Comment by miigotu** [comment]
@rutskiuk there is no way to change this behavior safely, because TVDB api is unreliable. If I deleted or updated the airdate for every episode that returned None from thetvdb, the next time the api was failing to return proper data it would change your whole database to unaired, or worse it could delete every episode from your DB.

Postponed episodes are incredibly rare, and are only an issue right now because of quarantine. It is best to just live with it for now unless you can get thetvdb to return "postponed" in the api when an airdate was actually removed on purpose.

**Comment by miigotu** [comment]
I think I found a solution, pushed in https://github.com/SickChill/SickChill/commit/518e33e628df975eb178c2a6b8541066818a2359

**Comment by rutskiuk** [comment]
Brilliant! Sorted it for me 💯
