### ISSUE TITLE
Sort Change

### ISSUE THREAD

**Issue by 777black777** [SickChill/SickChill#6252]
Branch/Commit: master/518e33e628df975eb178c2a6b8541066818a2359
OS: Linux-3.10.105-x86_64-with-glibc2.2.5 (Synology NAS)
Browser: Firefox/Edge Chromium/Chrome
What you did: Attempted to sort by only Downloads column in the Simple Layout
What happened: Sort was by Show column and then Downloads column
What you expected: Sort only by Downloads column or whatever column one chooses without the show name also being sorted as a primary/secondary sort key. Previous version allowed for sort by just the Downloads column. Unable to find a setting that allows for the sort to be reverted back to the previous methodology.

**Comment by miigotu** [comment]
Previous version did not allow that, it has been this way for a very long time (2-3 years)

**Comment by 777black777** [comment]
I am left to assume that my very old installation (was called SickRage when I first installed it) of SickChill on my Synology NAS allowed my preferred sorting method to carry over into new versions and that maybe my attempt to fix the update problems the other day cleared out my bug?

Just confirming then, that name column sort secondary is now the default and has become cannon and I should re-orient my way of looking at the table?

**Comment by miigotu** [comment]
https://github.com/SickChill/SickChill/commit/31cf4bbee917ad48f2db4552f1573fab90ef717b#diff-5329b74ce808a7064dc3b930e52c97b6R1896
It has been this way since Nov 18, 2015 

I do think its kind of annoying, but even without this the downloads do not sort by total number, only percentage complete. So 19/19 is the same as 176/176, it then sorts those *equal* valued items by name

**Comment by miigotu** [comment]
I am going to leave it this way, otherwise some people will come in and demand change =P
