### ISSUE TITLE
ReadyNAS instructions corrections

### ISSUE THREAD

**Issue by theskillwithin** [SickChill/SickChill#6296]
@miigotu on the following instructions for the readynas hard restart:

this is moving SickChill-master folder into sickchill, so now u have /apps/sickchill/SickChill-master.   I had to do `mv SickChill-master/* /apps/sickchill`  and `mv SickChill-master/.* /apps/sickchill` to get the dot files moved over as well.

also i noticed i had no `/apps/sickchill/gui/slick/` and no `server.key server.cert`

making the temp sickchill-backup folder in my ~ dir made it so i could not fully move over the files to backup, getting a out of space error.  so instead i made my sickchill-backup folder in /data/Documents  and that worked because that is a partition readynas is tracking

instructions i am referring to:
```
systemctl stop fvapp-sickchill
mkdir ~/sickchill-backup
cd ~/sickchill-backup
wget https://github.com/SickChill/SickChill/archive/master.zip
unzip master.zip

cd /apps/sickchill
mv app-config config.xml fvapp-sickchill.service logo.png ~/sickchill-backup/
mv server.key server.cert ~/sickchill-backup/ 2> /dev/null
mv gui/slick/cache ~/sickchill-backup/
find ./ -mindepth 1 -delete

cd ~/sickchill-backup
cp -R app-config app-config-backup
mv app-config config.xml fvapp-sickchill.service logo.png /apps/sickchill/
mv server.key server.cert /apps/sickchill/ 2> /dev/null
mv SickChill-master/ /apps/sickchill
mv cache /apps/sickchill/gui/slick/
rmdir SickChill-master
systemctl start fvapp-sickchill
```

**Comment by miigotu** [comment]
Fixed. server.(key|cert) are just the auto-generated self-signed certificates if you use the built-in https without providing a cert, most people do not have them.

**Comment by didyouexpectthat** [comment]
Hi there.
I highly, highly recommend you change the ~ path due to the 4GB OS on ReadyNASOS 6. Typically, ReadyNAS users login with root user and the /root is on the OS partition. 
Moving some SickChill folders will cause the OS to fill up and it's a mess to clean up properly, sometimes leading to an OS reinstall. I would recommend changing ~ to /home/admin/  or mkdir'ing /apps/sickchill-backup and using it. /apps, /data, and /home are all on the data volume and should have enough space to move from /apps.

**Comment by miigotu** [comment]
@didyouexpectthat done, but there are probably like 5 people on the planet still using readynas (and also using SC) and this is a one-time fix haha, I dont think I need to keep changing the instructions 10 times a day.
