### ISSUE TITLE
Manual search for X keeps searching for Y

### ISSUE THREAD

**Issue by utdrmac** [SickChill/SickChill#6517]
Branch/Commit: Branch: master
Commit: 8d193c7ae804baa4a3110dafae25cc7d5b83ef82
Version: v2020.06.07-3
Database Version: 44.1

OS: Ubuntu/Docker
Browser: Chrome

What you did: Attempting to manually search for season 4, episode 4 of a show
What happened: Search string in logs shows searching for season 4, episode **2**
What you expected: For the search to search for what i asked it to search

In the web GUI, I first clicked on the magnifying glass icon for S04E02. This search failed, for whatever reasons. I then clicked on S04E03. This succeeded and download began. I then clicked on S04E04. The manual search continued looking for S04E02 as noted in the logs below. The logs pasted below appeared _after_ I clicked on S04E04. Seems like it is not clearing some internal cache.

The second line of the logs even explicitly says "Beginning search for S04E004", yet everything else says S04E02. Why doesn't sickchill search for what I asked it to search for?

Logs:
```
2020-06-08 14:26:53 DEBUG    SEARCHQUEUE-MANUAL- :: formatting pattern: %SN - S%0SE%0E - %EN -> Paw Patrol - S04E004 - Pups Save the Cat Show
2020-06-08 14:26:53 INFO     SEARCHQUEUE-MANUAL- :: Beginning manual search for: [Paw Patrol - S04E004 - Pups Save the Cat Show]
2020-06-08 14:26:53 DEBUG    SEARCHQUEUE-MANUAL-272472 :: [Rarbg] :: Last update was too soon, using old cache: 2020-06-08 14:20:00. Updated less then 10 minutes ago
2020-06-08 14:26:53 DEBUG    SEARCHQUEUE-MANUAL-272472 :: [MagnetDL] :: Last update was too soon, using old cache: 2020-06-08 14:25:44. Updated less then 10 minutes ago
2020-06-08 14:26:53 INFO     SEARCHQUEUE-MANUAL-272472 :: [Rarbg] :: Performing episode search for Paw Patrol
2020-06-08 14:26:53 DEBUG    SEARCHQUEUE-MANUAL-272472 :: [Rarbg] :: GET URL: http://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=sickchill&format=json [Status: 200]
2020-06-08 14:26:53 DEBUG    SEARCHQUEUE-MANUAL-272472 :: [Rarbg] :: Search Mode: Episode
2020-06-08 14:26:53 DEBUG    SEARCHQUEUE-MANUAL-272472 :: [Rarbg] :: Search string: Paw Patrol S04E02
2020-06-08 14:26:56 DEBUG    SEARCHQUEUE-MANUAL-272472 :: [Rarbg] :: GET URL: http://torrentapi.org/pubapi_v2.php?sort=seeders&min_leechers=0&min_seeders=1&search_tvdb=272472&app_id=sickchill&search_string=Paw+Patrol+S04E02&ranked=0&category=tv&format=json_extended&token=saf85uzr4p&limit=100&mode=search [Status: 200]
```

**Comment by miigotu** [comment]
http://thexem.de/xem/show/4814

Scene numbers are mapped to tvdb numbers.

**Comment by utdrmac** [comment]
Could you please explain that? I have no idea what that means. What is a scene number and how is that related to tvdb? How does that statement fix the issue of searching for something that I specifically did not ask for?

**Comment by miigotu** [comment]
The numbering you see in SC is the numbering on tvdb. The episode you are searching for is listed on providers by their scene number. When you search it, the season and episode is translated from tvdb numbering into scene numbering by using xem, and then searches for that episode on providers. When it is found, it is matched back to the episode you searched for.

**Comment by utdrmac** [comment]
So where is the core issue? Still doesn’t make sense (still not understanding) how clicking on episode X for manual search means to search episode Y.
Is there some way to ignore the scene numbering and just search directly on episode number pattern? (I still don’t really know what a scene number is)

**Comment by miigotu** [comment]
There is no core issue. It is doing exactly what it is supposed to do.

Scene releases that are found on providers (torrent and nzb sites) are numbered differently in the release than they are numbered on thetvdb. In order to grab the correct episode, it has to be translated to the scene number for the search string.

You can turn off scene numbering in the settings for the show, but it is unlikely to get you good results. You will get for example s01e04, because you clicked s01e04 (tvdb number) but it is listed on the torrent site by scene numbering. You would just end up with for example s01e02 saved as s01e04 instead of s01e04.

The numbering is different usually because of specials and double episodes. This process is necessary to actually get the episode you are looking for because otherwise it is not a 1:1 match with the numbering.

**Comment by utdrmac** [comment]
Maybe I can explain what I'm experiencing and that will help understand where I'm coming from. I've got SC configured to use rarbg as my provider. I click the magnifying glass next to S04E02 of "whatever" show. SC can't find anything. I can see in the logs that it called some torrentapi (which I believe is rar's API) and that it found several results but for whatever reasons, it ignored all of them. Even though, I can see in the logs, the exact match that it _should_ have picked. When I go directly to rarbg's site and enter in the exact same search pattern/phrase, I get many results, including the exact one I want also. It's just frustrating to see in the logs a complete ignore of what I'm asking for and then have to do it manually. I mean, isn't that what SC is for, to not have to do it manually?

**Comment by miigotu** [comment]
I don't know how else to explain it to you. The numbers between what is shown in SC and providers are not always a 1:1 match.

`S04E04 - Pups Save the Cat Show` on TheTVDB (tvdb numbering) is uploaded to providers as `S04E02 - Pups Save the Cat Show` (scene numbering).

The numbers are not what is important. What is important is that you get `Pups Save the Cat Show` instead of `Pups Save the Chili Cook-Off`, which is on torrent providers as S04E04.

Where this gets confusing, is that there are some uploaders uploading files in TVDB numbering (against scene rules/standards) which makes a few shows a bit tricky to get working correctly since there is no standard being followed. Paw Patrol is one of these shows.

Edit Paw Patrol, uncheck scene numbering, save, force a full update on the show. Search.
