### ISSUE TITLE
Cannot access GUI on trusted networks

### ISSUE THREAD

**Issue by SimonHova** [SickChill/SickChill#6531]
The network in my home is split across several VLANs, my SickChill installation is on the 10.6.0.0/16 subnet, but I tend to access it from my WLAN VLAN, 10.18.0.0/16. How can I make the entire 10.0.0.0/8 subnet trusted and access my GUI?

**Comment by bradwtracy** [comment]
The same issue occurs for docker containers.  The *local* subnet for the docker container is 172.17.x.x but I of course don't access SC using that subnet since, by the nature of containers, they use their own.  I access on 192.168.x.x but SC insists I am exposing my install publically just because I access on a different subnet.

**Comment by fatgeek** [comment]
I'm having the same issue. Running in Docker (linuxserver.io) on Unraid. Looks like I got an automatic update last night. My instance is in no way exposed to the internet. The error message says to manually edit the config.ini, bur doesn't offer any actual explanation on the error. The inplementation of this "feature" seems to have a pretty narrow view of how people use SickChill. I have no desire to need a user/pass for something only accessible from within my home network.
