### ISSUE TITLE
With large number of episodes, page loading very slow

### ISSUE THREAD

**Issue by ronrosenfeld** [SickChill/SickChill#6575]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:  1e656000415b1e32dee9e04dabc53a3636045c02
OS: Docker on Synology
Browser: Edge
What you did: Click on a show from the show list
What happened: Page showing every episode of show list opened, but takes forever (> 5 min) to update
What you expected: more rapid update
Logs:
```
PASTE LOGS HERE
```
This seems to happen with shows that have many episodes.  This case is unusual with 25 Seasons / 160 episodes per season.  But I've run into this problem, to a lesser extent, with other shows.

Is there any way to speed this process up?  Even if it means ignoring older seasons?

**Comment by ronrosenfeld** [comment]
I found the setting for "show all seasons" and disabled that.  However, in accord with the poster of issue [6179](https://github.com/SickChill/SickChill/issues/6179), I sure wish this could either be on a "per show" basis, or possibly a setting where the last few seasons could be expanded.  So maybe this should be a feature request.

**Comment by miigotu** [comment]
Not handling any feature requests right now. I'm in the middle of porting to python3 (works already, mostly done) and a major overhaul and refactor that breaks existing config but fixes a ton of problems. Since people will have to redo their install to get the python3 version, I figured it's a good time for those breaking changes.
