### ISSUE TITLE
NZB Provider issue

### ISSUE THREAD

**Issue by DrDrewZA** [SickChill/SickChill#6718]
NZB Finder doesnt seem to like Sickchill at the moment:

2020-09-10 18:33:03 INFO :: SEARCHQUEUE-BACKLOG-270261 :: [NZBFinder.ws] :: Request failed: 400 Client Error: Bad Request for url: https://nzbfinder.ws/api?t=tvsearch&limit=100&offset=0&cat=5030%2C5040%2C5010%2C5045&maxage=2500&apikey=xxxxxxxxxxxxe280bfce7550359bc19e1ab&tvdbid=270261&season=7&ep=194 ()

### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:latest PIP version
OS:win10
Browser:Edge
What you did:
What happened:
What you expected:
Logs:
```
PASTE LOGS HERE
```

**Comment by miigotu** [comment]
What happens if you copy the url into the browser (with your correct API key)

**Comment by Wally73** [comment]
api url of nzbfinder did change months ago
https://nzbfinder.ws/api/v1/api?t=tvsearch&etc

**Comment by miigotu** [comment]
The api url we use is fine.
@DrDrewZA The problem is that Jimmy Fallon is air by date and you don't have the show set to air by date, and also that they do not have the season (2020) and ep (for example 08/10) set in the 2020 episodes of that show. SC is doing exactly what it is supposed to be doing. However, I will adjust it (and hopefully not break other providers)
