### ISSUE TITLE
There is no way to make it work in python 3.8.5

### ISSUE THREAD

**Issue by carloscebrian666** [SickChill/SickChill#6727]
Hi, since sickhill was updated to python 3.8.5 I have not had a way to get it to work for more help than I have asked. It installs without problems in Windows 10 with the installer 0.5.7 and it does not let me import the database because the Macro error appears, I scrape 1,500 tv shows again and when I have 400 again the Mako error appears. I think I have no choice but to abandon it because it is desperate, an out-of-place instability. The Mako error that keeps getting is "File C: \ SickChill \ SickChill \ lib3 \ dateutil \ tz \ tz.py: 260, in _naive_is_dst:
return time.localtime (timestamp + time.timezone) .tm_isdst
OSError: [Errno 22] Invalid argument ", if someone can help me thank you very much, if not it is possible that you will be very lucky because I have not had it.
Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

**Comment by carloscebrian666** [comment]
File C:\SickChill\SickChill\lib3\dateutil\tz\tz.py:260, in _naive_is_dst:
return time.localtime(timestamp + time.timezone).tm_isdst
OSError: [Errno 22] Invalid argument

**Comment by miigotu** [comment]
Send me sickchill.db and cache.db in PM on discord, telegram, or slack.

**Comment by miigotu** [comment]
Funny how you rage quit because you cannot follow simple instructions. I don't know where you are from but where I'm from when you ask someone to do something for you (especially when it is free and you are abusing it to the max) you should be polite about it.

Go ahead back to the other fork where they didn't even reply to your issue at all. I was even helping you in private message on telegram the past few days. 
https://github.com/SickChill/SickChill/issues/6728

Have fun fixing it by yourself.

**Comment by carloscebrian666** [comment]
Hello, I ask you please accept my apologies, I have been very unfair
for my impatience and frustration and indeed if everyone does not have
problems with the database, the problem is only mine, you have all the
reason in the world that I have been disgusting For this I ask you my
sincere apologies that it will never happen again. I'm going to calm
down, wait a few days and I'll tell you. Again sorry. A greeting.
