### ISSUE TITLE
Error with lxml library

### ISSUE THREAD

**Issue by beberito** [SickChill/SickChill#6802]
Hi,

I installed sickchill on my ASUSTOR NAS.
I get a error on startup :

`Traceback (most recent call last):
  File "/opt/bin/SickChill.py", line 17, in <module>
    from sickchill.movies import MovieList
  File "/opt/lib/python3.8/site-packages/sickchill/movies.py", line 8, in <module>
    from imdb.parser.http.piculet import Path, Rule
  File "/opt/lib/python3.8/site-packages/imdb/parser/http/__init__.py", line 40, in <module>
    from . import (
  File "/opt/lib/python3.8/site-packages/imdb/parser/http/companyParser.py", line 32, in <module>
    from .piculet import Path, Rule, Rules
  File "/opt/lib/python3.8/site-packages/imdb/parser/http/piculet.py", line 263, in <module>
    from lxml import etree as ElementTree
ImportError: cannot import name 'etree' from 'lxml' (/opt/lib/python3.8/site-packages/lxml/__init__.py)
 Done (Thu Sep 24 18:40:32 CEST 2020)
`
lxml is up to date, as well as other packages.

Do you have any clue ?

**Comment by miigotu** [comment]
`pip3 install -U lxml`

**Comment by beberito** [comment]
> root@NAS:/volume1/.@plugins/AppCentral/sickbeard-tvrage` # pip3 install -U lxml
> Requirement already up-to-date: lxml in /volume1/.@plugins/AppCentral/entware/opt/lib/python3.8/site-packages (4.5.2)


Here is the full startup attent of sickchill : 
> root@NAS:/volume1/.@plugins/AppCentral/sickbeard-tvrage/CONTROL # ./start-stop.sh start
> SickChill prestartup checks... (Thu Sep 24 20:08:47 CEST 2020)
> Starting SickChillRequirement already up-to-date: pip in ./env/lib/python3.8/site-packages (20.2.3)
> Requirement already up-to-date: sickchill in ./env/lib/python3.8/site-packages (2020.9.23.post2)
> Requirement already satisfied, skipping upgrade: bencode.py in ./env/lib/python3.8/site-packages (from sickchill) (4.0.0)
> Requirement already satisfied, skipping upgrade: httplib2 in ./env/lib/python3.8/site-packages (from sickchill) (0.18.1)
> Requirement already satisfied, skipping upgrade: kodipydent in ./env/lib/python3.8/site-packages (from sickchill) (0.3.1)
> Requirement already satisfied, skipping upgrade: python3-fanart in ./env/lib/python3.8/site-packages (from sickchill) (2.0.0)
> Requirement already satisfied, skipping upgrade: jsonrpclib-pelix in ./env/lib/python3.8/site-packages (from sickchill) (0.4.1)
> Requirement already satisfied, skipping upgrade: subliminal in ./env/lib/python3.8/site-packages (from sickchill) (2.1.0)
> Requirement already satisfied, skipping upgrade: configobj in ./env/lib/python3.8/site-packages (from sickchill) (5.0.6)
> Requirement already satisfied, skipping upgrade: imagesize in ./env/lib/python3.8/site-packages (from sickchill) (1.2.0)
> Requirement already satisfied, skipping upgrade: ifaddr in ./env/lib/python3.8/site-packages (from sickchill) (0.1.7)
> Requirement already satisfied, skipping upgrade: imdbpy>=2020.09.20 in ./env/lib/python3.8/site-packages (from sickchill (2020.9.20)
> Requirement already satisfied, skipping upgrade: ipaddress in ./env/lib/python3.8/site-packages (from sickchill) (1.0.23)
> Requirement already satisfied, skipping upgrade: new-rtorrent-python in ./env/lib/python3.8/site-packages (from sickchill) (1.0.1a0)
> Requirement already satisfied, skipping upgrade: validators in ./env/lib/python3.8/site-packages (from sickchill) (0.18.1)
> Requirement already satisfied, skipping upgrade: Unidecode in ./env/lib/python3.8/site-packages (from sickchill) (1.1.1)
> Requirement already satisfied, skipping upgrade: cloudscraper in ./env/lib/python3.8/site-packages (from sickchill) (1.2.46)
> Requirement already satisfied, skipping upgrade: Mako in ./env/lib/python3.8/site-packages (from sickchill) (1.1.3)
> Requirement already satisfied, skipping upgrade: python-slugify in ./env/lib/python3.8/site-packages (from sickchill) (4.0.1)
> Requirement already satisfied, skipping upgrade: rarfile in ./env/lib/python3.8/site-packages (from sickchill) (4.0)
> Requirement already satisfied, skipping upgrade: pymediainfo in ./env/lib/python3.8/site-packages (from sickchill) (4.2.1)
> Requirement already satisfied, skipping upgrade: PySocks in ./env/lib/python3.8/site-packages (from sickchill) (1.7.1)
> Requirement already satisfied, skipping upgrade: gntp in ./env/lib/python3.8/site-packages (from sickchill) (1.0.3)
> Requirement already satisfied, skipping upgrade: pyaes in ./env/lib/python3.8/site-packages (from sickchill) (1.6.1)
> Requirement already satisfied, skipping upgrade: send2trash in ./env/lib/python3.8/site-packages (from sickchill) (1.5.0)
> Requirement already satisfied, skipping upgrade: CacheControl in ./env/lib/python3.8/site-packages (from sickchill) (0.12.6)
> Requirement already satisfied, skipping upgrade: requests in ./env/lib/python3.8/site-packages (from sickchill) (2.24.0)
> Requirement already satisfied, skipping upgrade: win-inet-pton in ./env/lib/python3.8/site-packages (from sickchill) (1.1.0)
> Requirement already satisfied, skipping upgrade: twilio in ./env/lib/python3.8/site-packages (from sickchill) (6.45.2)
> Requirement already satisfied, skipping upgrade: deluge-client in ./env/lib/python3.8/site-packages (from sickchill) (1.9.0)
> Requirement already satisfied, skipping upgrade: timeago in ./env/lib/python3.8/site-packages (from sickchill) (1.0.14)
> Requirement already satisfied, skipping upgrade: beekeeper in ./env/lib/python3.8/site-packages (from sickchill) (0.9.2)
> Requirement already satisfied, skipping upgrade: markdown2 in ./env/lib/python3.8/site-packages (from sickchill) (2.3.9)
> Requirement already satisfied, skipping upgrade: python-dateutil in ./env/lib/python3.8/site-packages (from sickchill) (2.8.1)
> Requirement already satisfied, skipping upgrade: pynma in ./env/lib/python3.8/site-packages (from sickchill) (1.0)
> Requirement already satisfied, skipping upgrade: PyGithub in ./env/lib/python3.8/site-packages (from sickchill) (1.53)
> Requirement already satisfied, skipping upgrade: putio.py in ./env/lib/python3.8/site-packages (from sickchill) (8.6.2)
> Requirement already satisfied, skipping upgrade: qbittorrent-api in ./env/lib/python3.8/site-packages (from sickchill) (2020.9.9)
> Requirement already satisfied, skipping upgrade: html5lib in ./env/lib/python3.8/site-packages (from sickchill) (1.1)
> Requirement already satisfied, skipping upgrade: python-twitter in ./env/lib/python3.8/site-packages (from sickchill) (3.5)
> Requirement already satisfied, skipping upgrade: chardet in ./env/lib/python3.8/site-packages (from sickchill) (3.0.4)
> Requirement already satisfied, skipping upgrade: enzyme in ./env/lib/python3.8/site-packages (from sickchill) (0.4.1)
> Requirement already satisfied, skipping upgrade: tmdbsimple in ./env/lib/python3.8/site-packages (from sickchill) (2.6.6)
> Requirement already satisfied, skipping upgrade: tornado in ./env/lib/python3.8/site-packages (from sickchill) (6.0.4)
> Requirement already satisfied, skipping upgrade: profilehooks in ./env/lib/python3.8/site-packages (from sickchill) (1.12.0)
> Requirement already satisfied, skipping upgrade: Js2Py in ./env/lib/python3.8/site-packages (from sickchill) (0.70)
> Requirement already satisfied, skipping upgrade: packaging in ./env/lib/python3.8/site-packages (from sickchill) (20.4)
> Requirement already satisfied, skipping upgrade: tvdbsimple in ./env/lib/python3.8/site-packages (from sickchill) (1.0.6)
> Requirement already satisfied, skipping upgrade: beautifulsoup4 in ./env/lib/python3.8/site-packages (from sickchill) (4.9.1)
> Requirement already satisfied, skipping upgrade: pyOpenSSL in ./env/lib/python3.8/site-packages (from sickchill) (19.1.0)
> Requirement already satisfied, skipping upgrade: tus.py in ./env/lib/python3.8/site-packages (from sickchill) (1.3.4)
> Requirement already satisfied, skipping upgrade: feedparser in ./env/lib/python3.8/site-packages (from sickchill) (6.0.1)
> Requirement already satisfied, skipping upgrade: sqlalchemy in ./env/lib/python3.8/site-packages (from sickchill) (1.3.19)
> Requirement already satisfied, skipping upgrade: guessit in ./env/lib/python3.8/site-packages (from sickchill) (3.1.1)
> Requirement already satisfied, skipping upgrade: pysrt>=1.0.1 in ./env/lib/python3.8/site-packages (from subliminal->sickchill) (1.1.2)
> Requirement already satisfied, skipping upgrade: dogpile.cache>=0.6.0 in ./env/lib/python3.8/site-packages (from subliminal->sickchill) (1.0.2)
> Requirement already satisfied, skipping upgrade: stevedore>=1.20.0 in ./env/lib/python3.8/site-packages (from subliminal->sickchill) (3.2.2)
> Requirement already satisfied, skipping upgrade: six>=1.9.0 in ./env/lib/python3.8/site-packages (from subliminal->sickchill) (1.15.0)
> Requirement already satisfied, skipping upgrade: click>=4.0 in ./env/lib/python3.8/site-packages (from subliminal->sickchill) (7.1.2)
> Requirement already satisfied, skipping upgrade: appdirs>=1.3 in ./env/lib/python3.8/site-packages (from subliminal->sickchill) (1.4.4)
> Requirement already satisfied, skipping upgrade: babelfish>=0.5.2 in ./env/lib/python3.8/site-packages (from subliminal->sickchill) (0.5.5)
> Requirement already satisfied, skipping upgrade: pytz>=2012c in ./env/lib/python3.8/site-packages (from subliminal->sickchill) (2020.1)
> Requirement already satisfied, skipping upgrade: lxml in ./env/lib/python3.8/site-packages (from imdbpy>=2020.09.20->sickchill) (4.5.2)
> Requirement already satisfied, skipping upgrade: decorator>=3.4.0 in ./env/lib/python3.8/site-packages (from validators->sickchill) (4.4.2)
> Requirement already satisfied, skipping upgrade: requests-toolbelt>=0.9.1 in ./env/lib/python3.8/site-packages (from cloudscraper->sickchill) (0.9.1)
> Requirement already satisfied, skipping upgrade: pyparsing>=2.4.7 in ./env/lib/python3.8/site-packages (from cloudscraper->sickchill) (2.4.7)
> Requirement already satisfied, skipping upgrade: MarkupSafe>=0.9.2 in ./env/lib/python3.8/site-packages (from Mako->sickchill) (1.1.1)
> Requirement already satisfied, skipping upgrade: text-unidecode>=1.3 in ./env/lib/python3.8/site-packages (from python-slugify->sickchill) (1.3)
> Requirement already satisfied, skipping upgrade: setuptools in ./env/lib/python3.8/site-packages (from pymediainfo->sickchill) (47.1.0)
> Requirement already satisfied, skipping upgrade: msgpack>=0.5.2 in ./env/lib/python3.8/site-packages (from CacheControl->sickchill) (1.0.0)
> Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in ./env/lib/python3.8/site-packages (from requests->sickchill) (2.10)
> Requirement already satisfied, skipping upgrade: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./env/lib/python3.8/site-packages (from requests->sickchill) (1.25.10)
> Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in ./env/lib/python3.8/site-packages (from requests->sickchill) (2020.6.20)
> Requirement already satisfied, skipping upgrade: PyJWT>=1.4.2 in ./env/lib/python3.8/site-packages (from twilio->sickchill) (1.7.1)
> Requirement already satisfied, skipping upgrade: xmltodict<=0.10.1,>=0.9.2 in ./env/lib/python3.8/site-packages (from beekeeper->sickchill) (0.10.1)
> Requirement already satisfied, skipping upgrade: deprecated in ./env/lib/python3.8/site-packages (from PyGithub->sickchill) (1.2.10)
> Requirement already satisfied, skipping upgrade: attrdict>=2.0.0 in ./env/lib/python3.8/site-packages (from qbittorrent-api->sickchill) (2.0.1)
> Requirement already satisfied, skipping upgrade: webencodings in ./env/lib/python3.8/site-packages (from html5lib->sickchill) (0.5.1)
> Requirement already satisfied, skipping upgrade: future in ./env/lib/python3.8/site-packages (from python-twitter->sickchill) (0.18.2)
> Requirement already satisfied, skipping upgrade: requests-oauthlib in ./env/lib/python3.8/site-packages (from python-twitter->sickchill) (1.3.0)
> Requirement already satisfied, skipping upgrade: tzlocal>=1.2 in ./env/lib/python3.8/site-packages (from Js2Py->sickchill) (2.1)
> Requirement already satisfied, skipping upgrade: pyjsparser>=2.5.1 in ./env/lib/python3.8/site-packages (from Js2Py->sickchill) (2.7.1)
> Requirement already satisfied, skipping upgrade: soupsieve>1.2 in ./env/lib/python3.8/site-packages (from beautifulsoup4->sickchill) (2.0.1)
> Requirement already satisfied, skipping upgrade: cryptography>=2.8 in ./env/lib/python3.8/site-packages (from pyOpenSSL->sickchill) (3.1)
> Requirement already satisfied, skipping upgrade: sgmllib3k in ./env/lib/python3.8/site-packages (from feedparser->sickchill) (1.0.0)
> Requirement already satisfied, skipping upgrade: rebulk==2.* in ./env/lib/python3.8/site-packages (from guessit->sickchill) (2.0.1)
> Requirement already satisfied, skipping upgrade: pbr!=2.1.0,>=2.0.0 in ./env/lib/python3.8/site-packages (from stevedore>=1.20.0->subliminal->sickchill) (5.5.0)
> Requirement already satisfied, skipping upgrade: wrapt<2,>=1.10 in ./env/lib/python3.8/site-packages (from deprecated->PyGithub->sickchill) (1.12.1)
> Requirement already satisfied, skipping upgrade: oauthlib>=3.0.0 in ./env/lib/python3.8/site-packages (from requests-oauthlib->python-twitter->sickchill) (3.1.0)
> Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.8 in ./env/lib/python3.8/site-packages (from cryptography>=2.8->pyOpenSSL->sickchill) (1.14.2)
> Requirement already satisfied, skipping upgrade: pycparser in ./env/lib/python3.8/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.8->pyOpenSSL->sickchill) (2.20)
> Requirement already satisfied: feedparser>=6.0.0.b3 in ./env/lib/python3.8/site-packages (6.0.1)
> Requirement already satisfied: sgmllib3k in ./env/lib/python3.8/site-packages (from feedparser>=6.0.0.b3) (1.0.0)
> /opt/lib/python3.8/site-packages/sickchill/locale
> /opt/lib/python3.8/site-packages/sickchill/locale
> Traceback (most recent call last):
>   File "/opt/bin/SickChill.py", line 17, in <module>
>     from sickchill.movies import MovieList
>   File "/opt/lib/python3.8/site-packages/sickchill/movies.py", line 8, in <module>
>     from imdb.parser.http.piculet import Path, Rule
>   File "/opt/lib/python3.8/site-packages/imdb/parser/http/__init__.py", line 40, in <module>
>     from . import (
>   File "/opt/lib/python3.8/site-packages/imdb/parser/http/companyParser.py", line 32, in <module>
>     from .piculet import Path, Rule, Rules
>   File "/opt/lib/python3.8/site-packages/imdb/parser/http/piculet.py", line 263, in <module>
>     from lxml import etree as ElementTree
> ImportError: cannot import name 'etree' from 'lxml' (/opt/lib/python3.8/site-packages/lxml/__init__.py)
>  Done (Thu Sep 24 20:09:07 CEST 2020)

Everything is up to date (at least for sickchill)
I don't understand ...

**Comment by miigotu** [comment]
What package is this? Because none of our official packages install/update packages in the startup script.

**Comment by beberito** [comment]
It's a apk package provided by asustor

**Comment by chewiiie** [comment]
Same problem and error here, also on an Asustor NAS since the last app update vers. 20200909 from the Asus App repository.

Any idea? NAS is running the last ADM version : 3.5.1.R8C1. It was already up-do-date and SickChill worked before. The update of SickChill created this issue. All apps are up-to-date including Python (2.7.10.r10), Python 3 (3.7.0.r5), EntWare (1.0.0), Perl (5.28.0.r5)... I also contacted the package maintainer in parrallel.

root@matrix:/volume1/.@plugins/AppCentral/sickbeard-tvrage/CONTROL # ./start-stop.sh start
SickChill prestartup checks... (Fri Sep 25 12:12:59 CEST 2020)
Starting SickChillRequirement already up-to-date: pip in ./env/lib/python3.8/site-packages (20.2.3)
Requirement already up-to-date: sickchill in ./env/lib/python3.8/site-packages (2020.9.24.post3)
Requirement already satisfied, skipping upgrade: deluge-client in ./env/lib/python3.8/site-packages (from sickchill) (1.9.0)
Requirement already satisfied, skipping upgrade: python-dateutil in ./env/lib/python3.8/site-packages (from sickchill) (2.8.1)
Requirement already satisfied, skipping upgrade: Js2Py in ./env/lib/python3.8/site-packages (from sickchill) (0.70)
Requirement already satisfied, skipping upgrade: enzyme in ./env/lib/python3.8/site-packages (from sickchill) (0.4.1)
Requirement already satisfied, skipping upgrade: markdown2 in ./env/lib/python3.8/site-packages (from sickchill) (2.3.9)
Requirement already satisfied, skipping upgrade: pynma in ./env/lib/python3.8/site-packages (from sickchill) (1.0)
Requirement already satisfied, skipping upgrade: ifaddr in ./env/lib/python3.8/site-packages (from sickchill) (0.1.7)
Requirement already satisfied, skipping upgrade: Mako in ./env/lib/python3.8/site-packages (from sickchill) (1.1.3)
Requirement already satisfied, skipping upgrade: configobj in ./env/lib/python3.8/site-packages (from sickchill) (5.0.6)
Requirement already satisfied, skipping upgrade: timeago in ./env/lib/python3.8/site-packages (from sickchill) (1.0.14)
Requirement already satisfied, skipping upgrade: validators in ./env/lib/python3.8/site-packages (from sickchill) (0.18.1)
Requirement already satisfied, skipping upgrade: win-inet-pton in ./env/lib/python3.8/site-packages (from sickchill) (1.1.0)
Requirement already satisfied, skipping upgrade: gntp in ./env/lib/python3.8/site-packages (from sickchill) (1.0.3)
Requirement already satisfied, skipping upgrade: jsonrpclib-pelix in ./env/lib/python3.8/site-packages (from sickchill) (0.4.1)
Requirement already satisfied, skipping upgrade: beautifulsoup4 in ./env/lib/python3.8/site-packages (from sickchill) (4.9.1)
Requirement already satisfied, skipping upgrade: bencode.py in ./env/lib/python3.8/site-packages (from sickchill) (4.0.0)
Requirement already satisfied, skipping upgrade: rarfile in ./env/lib/python3.8/site-packages (from sickchill) (4.0)
Requirement already satisfied, skipping upgrade: kodipydent in ./env/lib/python3.8/site-packages (from sickchill) (0.3.1)
Requirement already satisfied, skipping upgrade: subliminal in ./env/lib/python3.8/site-packages (from sickchill) (2.1.0)
Requirement already satisfied, skipping upgrade: qbittorrent-api in ./env/lib/python3.8/site-packages (from sickchill) (2020.9.9)
Requirement already satisfied, skipping upgrade: ipaddress in ./env/lib/python3.8/site-packages (from sickchill) (1.0.23)
Requirement already satisfied, skipping upgrade: imagesize in ./env/lib/python3.8/site-packages (from sickchill) (1.2.0)
Requirement already satisfied, skipping upgrade: new-rtorrent-python in ./env/lib/python3.8/site-packages (from sickchill) (1.0.1a0)
Requirement already satisfied, skipping upgrade: python-twitter in ./env/lib/python3.8/site-packages (from sickchill) (3.5)
Requirement already satisfied, skipping upgrade: tvdbsimple in ./env/lib/python3.8/site-packages (from sickchill) (1.0.6)
Requirement already satisfied, skipping upgrade: twilio in ./env/lib/python3.8/site-packages (from sickchill) (6.45.3)
Requirement already satisfied, skipping upgrade: beekeeper in ./env/lib/python3.8/site-packages (from sickchill) (0.9.2)
Requirement already satisfied, skipping upgrade: httplib2 in ./env/lib/python3.8/site-packages (from sickchill) (0.18.1)
Requirement already satisfied, skipping upgrade: PySocks in ./env/lib/python3.8/site-packages (from sickchill) (1.7.1)
Requirement already satisfied, skipping upgrade: tmdbsimple in ./env/lib/python3.8/site-packages (from sickchill) (2.6.6)
Requirement already satisfied, skipping upgrade: CacheControl in ./env/lib/python3.8/site-packages (from sickchill) (0.12.6)
Requirement already satisfied, skipping upgrade: profilehooks in ./env/lib/python3.8/site-packages (from sickchill) (1.12.0)
Requirement already satisfied, skipping upgrade: send2trash in ./env/lib/python3.8/site-packages (from sickchill) (1.5.0)
Requirement already satisfied, skipping upgrade: pyaes in ./env/lib/python3.8/site-packages (from sickchill) (1.6.1)
Requirement already satisfied, skipping upgrade: chardet in ./env/lib/python3.8/site-packages (from sickchill) (3.0.4)
Requirement already satisfied, skipping upgrade: pymediainfo in ./env/lib/python3.8/site-packages (from sickchill) (4.2.1)
Requirement already satisfied, skipping upgrade: html5lib in ./env/lib/python3.8/site-packages (from sickchill) (1.1)
Requirement already satisfied, skipping upgrade: pyOpenSSL in ./env/lib/python3.8/site-packages (from sickchill) (19.1.0)
Requirement already satisfied, skipping upgrade: feedparser in ./env/lib/python3.8/site-packages (from sickchill) (6.0.1)
Requirement already satisfied, skipping upgrade: sqlalchemy in ./env/lib/python3.8/site-packages (from sickchill) (1.3.19)
Requirement already satisfied, skipping upgrade: PyGithub in ./env/lib/python3.8/site-packages (from sickchill) (1.53)
Requirement already satisfied, skipping upgrade: tus.py in ./env/lib/python3.8/site-packages (from sickchill) (1.3.4)
Requirement already satisfied, skipping upgrade: requests in ./env/lib/python3.8/site-packages (from sickchill) (2.24.0)
Requirement already satisfied, skipping upgrade: tornado in ./env/lib/python3.8/site-packages (from sickchill) (6.0.4)
Requirement already satisfied, skipping upgrade: packaging in ./env/lib/python3.8/site-packages (from sickchill) (20.4)
Requirement already satisfied, skipping upgrade: Unidecode in ./env/lib/python3.8/site-packages (from sickchill) (1.1.1)
Requirement already satisfied, skipping upgrade: guessit in ./env/lib/python3.8/site-packages (from sickchill) (3.1.1)
Requirement already satisfied, skipping upgrade: imdbpy>=2020.09.20 in ./env/lib/python3.8/site-packages (from sickchill) (2020.9.25)
Requirement already satisfied, skipping upgrade: python-slugify in ./env/lib/python3.8/site-packages (from sickchill) (4.0.1)
Requirement already satisfied, skipping upgrade: putio.py in ./env/lib/python3.8/site-packages (from sickchill) (8.6.2)
Requirement already satisfied, skipping upgrade: cloudscraper in ./env/lib/python3.8/site-packages (from sickchill) (1.2.46)
Requirement already satisfied, skipping upgrade: python3-fanart in ./env/lib/python3.8/site-packages (from sickchill) (2.0.0)
Requirement already satisfied, skipping upgrade: six>=1.5 in ./env/lib/python3.8/site-packages (from python-dateutil->sickchill) (1.15.0)
Requirement already satisfied, skipping upgrade: tzlocal>=1.2 in ./env/lib/python3.8/site-packages (from Js2Py->sickchill) (2.1)
Requirement already satisfied, skipping upgrade: pyjsparser>=2.5.1 in ./env/lib/python3.8/site-packages (from Js2Py->sickchill) (2.7.1)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.9.2 in ./env/lib/python3.8/site-packages (from Mako->sickchill) (1.1.1)
Requirement already satisfied, skipping upgrade: decorator>=3.4.0 in ./env/lib/python3.8/site-packages (from validators->sickchill) (4.4.2)
Requirement already satisfied, skipping upgrade: soupsieve>1.2 in ./env/lib/python3.8/site-packages (from beautifulsoup4->sickchill) (2.0.1)
Requirement already satisfied, skipping upgrade: pytz>=2012c in ./env/lib/python3.8/site-packages (from subliminal->sickchill) (2020.1)
Requirement already satisfied, skipping upgrade: pysrt>=1.0.1 in ./env/lib/python3.8/site-packages (from subliminal->sickchill) (1.1.2)
Requirement already satisfied, skipping upgrade: babelfish>=0.5.2 in ./env/lib/python3.8/site-packages (from subliminal->sickchill) (0.5.5)
Requirement already satisfied, skipping upgrade: click>=4.0 in ./env/lib/python3.8/site-packages (from subliminal->sickchill) (7.1.2)
Requirement already satisfied, skipping upgrade: dogpile.cache>=0.6.0 in ./env/lib/python3.8/site-packages (from subliminal->sickchill) (1.0.2)
Requirement already satisfied, skipping upgrade: stevedore>=1.20.0 in ./env/lib/python3.8/site-packages (from subliminal->sickchill) (3.2.2)
Requirement already satisfied, skipping upgrade: appdirs>=1.3 in ./env/lib/python3.8/site-packages (from subliminal->sickchill) (1.4.4)
Requirement already satisfied, skipping upgrade: urllib3>=1.24.2 in ./env/lib/python3.8/site-packages (from qbittorrent-api->sickchill) (1.25.10)
Requirement already satisfied, skipping upgrade: attrdict>=2.0.0 in ./env/lib/python3.8/site-packages (from qbittorrent-api->sickchill) (2.0.1)
Requirement already satisfied, skipping upgrade: future in ./env/lib/python3.8/site-packages (from python-twitter->sickchill) (0.18.2)
Requirement already satisfied, skipping upgrade: requests-oauthlib in ./env/lib/python3.8/site-packages (from python-twitter->sickchill) (1.3.0)
Requirement already satisfied, skipping upgrade: PyJWT>=1.4.2 in ./env/lib/python3.8/site-packages (from twilio->sickchill) (1.7.1)
Requirement already satisfied, skipping upgrade: xmltodict<=0.10.1,>=0.9.2 in ./env/lib/python3.8/site-packages (from beekeeper->sickchill) (0.10.1)
Requirement already satisfied, skipping upgrade: msgpack>=0.5.2 in ./env/lib/python3.8/site-packages (from CacheControl->sickchill) (1.0.0)
Requirement already satisfied, skipping upgrade: setuptools in ./env/lib/python3.8/site-packages (from pymediainfo->sickchill) (47.1.0)
Requirement already satisfied, skipping upgrade: webencodings in ./env/lib/python3.8/site-packages (from html5lib->sickchill) (0.5.1)
Requirement already satisfied, skipping upgrade: cryptography>=2.8 in ./env/lib/python3.8/site-packages (from pyOpenSSL->sickchill) (3.1)
Requirement already satisfied, skipping upgrade: sgmllib3k in ./env/lib/python3.8/site-packages (from feedparser->sickchill) (1.0.0)
Requirement already satisfied, skipping upgrade: deprecated in ./env/lib/python3.8/site-packages (from PyGithub->sickchill) (1.2.10)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in ./env/lib/python3.8/site-packages (from requests->sickchill) (2020.6.20)
Requirement already satisfied, skipping upgrade: idna<3,>=2.5 in ./env/lib/python3.8/site-packages (from requests->sickchill) (2.10)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in ./env/lib/python3.8/site-packages (from packaging->sickchill) (2.4.7)
Requirement already satisfied, skipping upgrade: rebulk==2.* in ./env/lib/python3.8/site-packages (from guessit->sickchill) (2.0.1)
Requirement already satisfied, skipping upgrade: lxml in ./env/lib/python3.8/site-packages (from imdbpy>=2020.09.20->sickchill) (4.5.2)
Requirement already satisfied, skipping upgrade: text-unidecode>=1.3 in ./env/lib/python3.8/site-packages (from python-slugify->sickchill) (1.3)
Requirement already satisfied, skipping upgrade: requests-toolbelt>=0.9.1 in ./env/lib/python3.8/site-packages (from cloudscraper->sickchill) (0.9.1)
Requirement already satisfied, skipping upgrade: pbr!=2.1.0,>=2.0.0 in ./env/lib/python3.8/site-packages (from stevedore>=1.20.0->subliminal->sickchill) (5.5.0)
Requirement already satisfied, skipping upgrade: oauthlib>=3.0.0 in ./env/lib/python3.8/site-packages (from requests-oauthlib->python-twitter->sickchill) (3.1.0)
Requirement already satisfied, skipping upgrade: cffi!=1.11.3,>=1.8 in ./env/lib/python3.8/site-packages (from cryptography>=2.8->pyOpenSSL->sickchill) (1.14.2)
Requirement already satisfied, skipping upgrade: wrapt<2,>=1.10 in ./env/lib/python3.8/site-packages (from deprecated->PyGithub->sickchill) (1.12.1)
Requirement already satisfied, skipping upgrade: pycparser in ./env/lib/python3.8/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.8->pyOpenSSL->sickchill) (2.20)
Requirement already satisfied: feedparser>=6.0.0.b3 in ./env/lib/python3.8/site-packages (6.0.1)
Requirement already satisfied: sgmllib3k in ./env/lib/python3.8/site-packages (from feedparser>=6.0.0.b3) (1.0.0)
/volume1/.@plugins/AppCentral/sickbeard-tvrage/env/lib/python3.8/site-packages/sickchill/locale
/volume1/.@plugins/AppCentral/sickbeard-tvrage/env/lib/python3.8/site-packages/sickchill/locale
Traceback (most recent call last):
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/env/bin/SickChill.py", line 17, in <module>
    from sickchill.movies import MovieList
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/env/lib/python3.8/site-packages/sickchill/movies.py", line 8, in <module>
    from imdb.parser.http.piculet import Path, Rule
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/env/lib/python3.8/site-packages/imdb/parser/http/__init__.py", line 40, in <module>
    from . import (
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/env/lib/python3.8/site-packages/imdb/parser/http/companyParser.py", line 32, in <module>
    from .piculet import Path, Rule, Rules
  File "/volume1/.@plugins/AppCentral/sickbeard-tvrage/env/lib/python3.8/site-packages/imdb/parser/http/piculet.py", line 263, in <module>
    from lxml import etree as ElementTree
ImportError: cannot import name 'etree' from 'lxml' (/volume1/.@plugins/AppCentral/sickbeard-tvrage/env/lib/python3.8/site-packages/lxml/__init__.py)
 Done (Fri Sep 25 12:13:42 CEST 2020)

**Comment by miigotu** [comment]
The maintainer of that package needs to ensure you have libxslt-dev and libxml2-dev. This is not a sickchill issue this is a package maintainer issue.

**Comment by chewiiie** [comment]
Thanks for the tip @miigotu
