### ISSUE TITLE
AniDB anime series are not found even by enabling AniDB from the "anime" menu

### ISSUE THREAD

**Issue by zFerry98** [SickChill/SickChill#6950]
Branch/Commit: Develop / db8bb71
OS: WS2019
Browser: Chrome (latest)
What you did: Add existing series, all indexers (but there is only TheTVDB)
What happened: ? as result.
What you expected: Find the series by searching for them on AniDB

I don't understand the purpose of AniDB support if it doesn't find the series on AniDB.
If it was added only as a tool to put the written info of the same series on TheTVDB, honestly ... It is useless.

## Short explanation:

I have two "lists", one of normal anime (ex, Dragon Ball) and is run by Sonarr.
One of Anime 18+ (and theTVDB doesn't even hold 1 but they are still anime), I wanted to let SickChill manage it ... too bad it doesn't find 1 (not even sickrage).
The fact is that on PLEX there is a plugin (HAMA, written in python) that allows you to add series (NOT present on TheTVDB) that are on AniDB (such as Fate / Stay Night Heaven feel's).
Now wouldn't it be possible to merge that plugin on sickchill?
Or am I wrong and is there a way to import series that are indexed only on AniDB in sickchill?
Series name found only on AniDB (18+) "Knight of Erin" with ID: 15677.

I want to clarify that what I wrote does not want to be an insult or an improssing outburst but a Bug / Feature request.

<details>
 <summary>imgs:</summary>
 
![image](https://user-images.githubusercontent.com/17975351/104045368-bc611280-51de-11eb-9b55-a450294c4b4a.png)
![image](https://user-images.githubusercontent.com/17975351/104045493-edd9de00-51de-11eb-9b56-59e79663c30a.png)
HAMA link: https://github.com/ZeroQI/Hama.bundle

</details>

**Comment by Nyaran** [comment]
Currently there is only one indexer on SickChill, TheTVDB, the AniDB integration is just to fetch additional information.

The HAMA plugin is not compatible, as Plex and SickChill are not the same software.

At this moment I'm working on a new AniDB integration, but there is no ETA

**Comment by Smokey23** [comment]
Also, because the AniDB integration is not working currently, you have to manually locate and add the tag for the group that is releasing the anime you want to download.  If you do not add the tag, it WILL NOT download the episode of the show.

1. From the Show's page, click the 'Edit' button in the upper right.
2. On the 'Edit Show' page, click the 'Format' tab (2nd tab).
3. Enter the name of the group into the 'Custom Group' field then press the 'Add to White List' button.
4. Press the 'Save Changes' button at the bottom left of the page to save the changes.

I hope this helps!

**Comment by InFerNoBeasTz** [comment]
thanks for working on anidb
