### ISSUE TITLE
Sickchill fails to start after updating to latest version

### ISSUE THREAD

**Issue by knyllers** [SickChill/SickChill#7074]
Hi sickchill devs,
something went tits-up after updating to latest pip release...

I can't enable debug logging since the app won't start. Perhaps I can change the log level manually in some config file somewhere on the file system?

### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: pip install sickchill==2021.4.5.post1
OS: Ubuntu 20.04
Browser: Chrome
What you did: Updated Sickchill to version above (was previous version)
What happened: Sickchill won't start
What you expected: Sickchill starts successfully

Logs:
```
user@server:~$ sudo service sickchill restart
Job for sickchill.service failed because the control process exited with error code.
See "systemctl status sickchill.service" and "journalctl -xe" for details.
user@server:~$ sudo service sickchill status
● sickchill.service - SickChill Daemon
     Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2021-04-06 12:10:26 CEST; 2s ago
    Process: 12983 ExecStart=/usr/bin/python3.8 /home/user/.local/bin/SickChill.py -q --daemon --nolaunch --datadir=/home/user/sickchill (code=exited, status=1/FAILURE)

Apr 06 12:10:26 server systemd[1]: Starting SickChill Daemon...
Apr 06 12:10:26 server python3.8[12983]: Traceback (most recent call last):
Apr 06 12:10:26 server python3.8[12983]:   File "/home/user/.local/bin/SickChill.py", line 5, in <module>
Apr 06 12:10:26 server python3.8[12983]:     from SickChill.SickChill import start
Apr 06 12:10:26 server python3.8[12983]:   File "/home/user/.local/bin/SickChill.py", line 5, in <module>
Apr 06 12:10:26 server python3.8[12983]:     from SickChill.SickChill import start
Apr 06 12:10:26 server python3.8[12983]: ModuleNotFoundError: No module named 'SickChill.SickChill'; 'SickChill' is not a package
Apr 06 12:10:26 server systemd[1]: sickchill.service: Control process exited, code=exited, status=1/FAILURE
Apr 06 12:10:26 server systemd[1]: sickchill.service: Failed with result 'exit-code'.
Apr 06 12:10:26 server systemd[1]: Failed to start SickChill Daemon.

```

**Comment by kalokyeung** [comment]
@knyllers I have exactly the same. Just updated and now it won't start anymore.

**Comment by jrgprzm** [comment]
I have the same issue, running on Raspbian with python 3.6 pip installation. I've reverted back to the previous working release with:

`pip3 install -U sickchill==2021.3.28.post3`

**Comment by berndveit** [comment]
Same issue on Mac (Big Sur - Intel):

"***@MacMiniServer / % python ./Library/Frameworks/Python.framework/Versions/3.9/bin/SickChill.py
Traceback (most recent call last):
  File "./Library/Frameworks/Python.framework/Versions/3.9/bin/SickChill.py", line 5, in <module>
    from SickChill.SickChill import start
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/SickChill.py", line 5, in <module>
    from SickChill.SickChill import start
ImportError: No module named SickChill"

**Comment by miigotu** [comment]
The script has changed due to moving to pyproject.toml, I need to figure out how to handle that.

**Comment by miigotu** [comment]
Can you try pip install -U sickchill again, I'm confused why this would be failing (SickChill.py is in the wheel)

**Comment by jrgprzm** [comment]
I think I was able to fix it, I ran again the update and after starting it I got now this:

`osmc@osmc:~$ sudo service sickchill start 
Job for sickchill.service failed because the control process exited with error code.
See "systemctl status sickchill.service" and "journalctl -xe" for details.
osmc@osmc:~$ systemctl status sickchill.service
* sickchill.service - SickChill Daemon
   Loaded: loaded (/etc/systemd/system/sickchill.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2021-04-06 15:48:33 CDT; 17s ago
  Process: 11386 ExecStart=/usr/bin/python3.7 /home/osmc/.local/bin/SickChill.py -q --daemon --nolaunch (code=exited, status=2)
  
Apr 06 15:48:33 osmc systemd[1]: Starting SickChill Daemon...
Apr 06 15:48:33 osmc python3.7[11386]: /usr/bin/python3.7: can't open file '/home/osmc/.local/bin/SickChill.py': [Errno 2] No such file or directory
Apr 06 15:48:33 osmc systemd[1]: sickchill.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
Apr 06 15:48:33 osmc systemd[1]: sickchill.service: Failed with result 'exit-code'.
Apr 06 15:48:33 osmc systemd[1]: Failed to start SickChill Daemon.`

I noticed that `/home/osmc/.local/bin/SickChill.py` didn't exist, so I looked for it and found it in `/home/osmc/.local/lib/python3.7/site-packages/SickChill.py`. I then modified the starting script to point to the new location:
`sudo nano /etc/systemd/system/sickchill.service` and after that 
`sudo systemctl daemon-reload
sudo service sickchill start `

After that it started fine and I just have the issue described by #7075 7075

I am not sure this is exportable to the other people having this issue or if this required change was intented.

**Comment by Guesch** [comment]
Removed the docker and the image (Unraid) and still the same error after re-installing it :(

**Comment by miigotu** [comment]
No amount of reinstalling is going to fix it. You either have to change the startup script to point to the site-packages or wait until I figure out what is messed up with poetry.

**Comment by miigotu** [comment]
Update to latest version, I have built it using setup.py for now.
Waiting on https://github.com/python-poetry/poetry-core/pull/40 until I can switch to completely using pyproject.toml

464edce4c11d192814ae6824dc1a033218914484

**Comment by jrgprzm** [comment]
I am having some issues with the latest update, now I am getting this:

```
Collecting python<4,>=3.6 (from sickchill)
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/python/
```

And of course the update fails after that.

**Comment by miigotu** [comment]
Try sickchill-2021.4.6.post4

**Comment by jrgprzm** [comment]
That did the trick!
`pip3 install -U sickchill==2021.4.6.post4`
Did put back the .py file in the "correct" place. I had to revert the change I did earlier today to point just to `/home/osmc/.local/bin/SickChill.py` and I am back on business. Thank you!

As a note, `pip3 install -U sickchill ` is back to be "working" (it detects it's on the last version and therefore doesn't do anything.)

**Comment by knyllers** [comment]
pip3 install sickchill==2021.4.6.post4 did the trick. 

Thanks a bunch!
