### ISSUE TITLE
sickchill service paused

### ISSUE THREAD

**Issue by fonzy69** [SickChill/SickChill#7251]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit:Stable, last version
OS:Windows
Browser:Vivaldi
What you did:nothing
What happened:Sickchill service is paused
What you expected:it start
Logs:
```
No logs
```
all was worjing fine an today i see the service is paused, it is impossible to restart it.
i try to uninstall / reinstall sickchill without success.
In event viewer nssm tell there is an error 126
if i try to launch manually i have this message: 

c:\SickChill\Python3>python.exe "C:\SickChill\SickChill\SickChill.py" --nolaunch --port=8081 --datadir="C:\SickChill\Data"
sickchill found: False
virtualenv found: False
pip args: c:\SickChill\Python3\python.exe -m pip install --no-input --disable-pip-version-check --no-python-version-warning --no-color --trusted-host=pypi.org --trusted-host=files.pythonhosted.org -qqU setuptools poetry --pre
Command result: c:\SickChill\Python3\python.exe: No module named pip

Trying user site-packages
Command result: c:\SickChill\Python3\python.exe: No module named pip

poetry found: False
Because of the above errors, we will try creating a new virtualenvironment in C:\SickChill\SickChill\.venv
virtualenv found: False
virtualenv module not found, cannot create virtualenv

thanks for your help.

**Comment by ncdaol** [comment]
@fonzy69 The same issue is discussed in https://github.com/SickChill/SickChill/issues/7249.

**Comment by DavidPinilo** [comment]
Same thing happened to me on Raspbian. I tried what's suggested in #7249 but it still won't start. I get:

 sickchill.service - SickChill Daemon
   Loaded: loaded (/lib/systemd/system/sickchill.service; disabled; vendor prese
   Active: failed (Result: timeout) since Mon 2021-07-12 14:47:12 BST; 20s ago
  Process: 874 ExecStart=/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemo

Jul 12 14:45:42 raspberrypi systemd[1]: Starting SickChill Daemon...
Jul 12 14:47:12 raspberrypi systemd[1]: sickchill.service: Start operation timed
Jul 12 14:47:12 raspberrypi systemd[1]: sickchill.service: Control process exite
Jul 12 14:47:12 raspberrypi systemd[1]: sickchill.service: Failed with result 't
Jul 12 14:47:12 raspberrypi systemd[1]: Failed to start SickChill Daemon.
lines 1-10/10 (END)
● sickchill.service - SickChill Daemon
   Loaded: loaded (/lib/systemd/system/sickchill.service; disabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Mon 2021-07-12 14:47:12 BST; 20s ago
  Process: 874 ExecStart=/usr/bin/python3 /opt/sickchill/SickChill.py -q --daemon --nolaunch

Jul 12 14:45:42 raspberrypi systemd[1]: Starting SickChill Daemon...
Jul 12 14:47:12 raspberrypi systemd[1]: sickchill.service: Start operation timed out. Termin
Jul 12 14:47:12 raspberrypi systemd[1]: sickchill.service: Control process exited, code=kill
Jul 12 14:47:12 raspberrypi systemd[1]: sickchill.service: Failed with result 'timeout'.
Jul 12 14:47:12 raspberrypi systemd[1]: Failed to start SickChill Daemon.

**Comment by miigotu** [comment]
For windows, reinstall with the new installer: https://github.com/SickChill/windows-sickchill/releases/tag/v0.6.0

**Comment by dieselVtwin** [comment]
Windows 10 with SickChill version n-1 (whatever was current on 11-12 Jul when it it was last working...) when it auto-updated and failed to restart.
Installer says I must uninstall.
Link to doc or tool for Windows uninstall?

Thanks!

**Comment by miigotu** [comment]
You uninstall it just like any other program on Windows, from programs and features. 
When the uninstaller asks if you want to delete database and settings be careful to select the correct option.
