### ISSUE TITLE
SickChill refused to update, upon reinstall the service gets stuck in 'Paused'

### ISSUE THREAD

**Issue by Jonnehs** [SickChill/SickChill#7711]
Windows 2019 host - no idea how to collect logs on the issue as it seems it never attempts to start

the nssm service editor references the following in the arguments;

"C:\SickChill\Python3\tools\Scripts\SickChill.exe" --nolaunch --port=8081 --datadir="C:\SickChill\Data"

that sickchill.exe does not exist in the scripts folder (or anywhere)

**Comment by Mikk36** [comment]
My final solution was to uninstall the service while keeping data and then install again in the same location.
Initial inability to update was from broken .git/config file (real contents were replaced with a repeating NUL character). After fixing that, it resulted in that same "Paused" service.

**Comment by Jonnehs** [comment]
You cant reinstall from the built EXEs without uninstalling, I was trying to find the git stuff to do a manual pull but I'm really not sure what I'm looking for.

**Comment by Mikk36** [comment]
Can you not uninstall while keeping data?
I previously installed it using the SickChillInstaller, which creates the service using nssm.
When uninstalling, it asked if I wanted to keep data, which I agreed to in order to not nuke the existing conf etc.
But as I mentioned, something had horrifically gone wrong, because I was able to do a git pull, `git status` showed that everything had been updated, but still no cigar, the service failed to start SickChill.

If You are unsure, just find the data directory and do a backup before uninstalling. It should reside in `C:\SickChill\Data`.

**Comment by Jonnehs** [comment]
yes, I've tried uninstalling and reinstalling, but it doesn't resolve the issue

**Comment by BKSteve** [comment]
I'm not a windows user of SC but this was mentioned on SickChill Discord about service not working.
[https://github.com/SickChill/windows-sickchill/issues/38](https://github.com/SickChill/windows-sickchill/issues/38 )
