### ISSUE TITLE
Better provider warning logs

### ISSUE THREAD

**Issue by gits68** [SickChill/SickChill#7739]
Branch/Commit: 01020f3636d01535f60b83464d8127ea0efabfc7
OS: docker
What you did: [View Warnings](https://localhost:8081/errorlogs/?level=30)
What happened: 2021-12-09 04:22:43 Unable to connect to provider
What you expected: 2021-12-09 04:22:43 **YggTorrent:** Unable to connect to provider

logs from the web interface are incomplete, this require to go to sickchill.log to find the right information.

Proposed change:

```
sed -i 's/"Failed to download any results"/"{0}: Failed to download any results".format(self.name)/' \
    /app/sickchill/sickchill/providers/GenericProvider.py
sed -i 's/"Unable to connect to provider"/"{0}: Unable to connect to provider".format(self.name)/' \
    /app/sickchill/sickchill/oldbeard/providers/*.py
```

well, I suppose this change have to be done to every **logger.warning()** call.
would be better to adapt the **/errorlogs/?level=30** log viewer...

Logs before:
```
2021-12-09 04:07:38 WARNING :: SEARCHQUEUE-DAILY-SEARCH :: [YggTorrent] :: Unable to connect to provider
```

Logs after:
```
2021-12-09 04:07:38 WARNING :: SEARCHQUEUE-DAILY-SEARCH :: [YggTorrent] :: YggTorrent: Unable to connect to provider
```

**Comment by BKSteve** [comment]
Rather than doing all this `sed` stuff you could just branch and do your own pull requests.
The level of effort on your part wouldn't be much different.

On the logs you show, what's the real difference in actual information? It seems to be duplicate `YggTorrent`

> Logs before:
2021-12-09 04:07:38 WARNING :: SEARCHQUEUE-DAILY-SEARCH :: [YggTorrent] :: Unable to connect to provider
Logs after:
2021-12-09 04:07:38 WARNING :: SEARCHQUEUE-DAILY-SEARCH :: [YggTorrent] :: YggTorrent: Unable to connect to provider
