### ISSUE TITLE
Python packages reinstalled at each launch

### ISSUE THREAD

**Issue by ntarocco** [SickChill/SickChill#7747]
Having some issues on my Synology NAS after last update, I have uninstalled and reinstalled Sickchill to start from scratch.
I now have a new error message on the top bar: `No NZB/Torrent providers found or enabled for daily searches and backlog searches. Please check your settings.`
When I go to the `Search Provider` settings, I see the msg `no providers available to configure. `.

I started debugging the issue reading the code and, importing some modules in the Python console, I noticed that the [__init__.py](https://github.com/SickChill/SickChill/blob/master/sickchill/__init__.py#L4) file is installing the Python packages at each lunch. This is because the function [check_installed()](https://github.com/SickChill/SickChill/blob/master/sickchill/init_helpers.py#L378) always return `False` on my NAS.

This also explains why, when I start Sickchill from the Synology web interface, it takes a long time (many minutes) to have the Sickchill's webserver up and running and display the web interface.

I tried to comment out that line `poetry_install()`, and the start-up is much faster, less than a minute.

Is this behaviour wanted for some reasons or a bug?

BTW, I still have to figure out why I get the error `No NZB/Torrent providers found or enabled for daily searches and backlog searches.`.

Branch: master
Commit: 01020f3636d01535f60b83464d8127ea0efabfc7
Database Version: 44.5
OS:  Linux-3.2.40-i686-with-glibc2.0 (Synology DSM 6)
Python: 3.8.12
Browser: Any
Logs: No errors in the logs

**Comment by BKSteve** [comment]
As SC runs on many different platforms the resolution of the `check_installed` has fallen by the side for DSM.
The pip string is called by SC with `-qU` is not meant to download each package every time 'as far as I know' but yes every restart takes a long time at present. @miigotu is working on many items and I understand there's some fixes coming, and still work to be done but as most people load and leave it running the priority hasn't been on this. I did quite a bit of build testing to get the current package to load on many varieties of DSM hardware and software version. Still no notifications on DSM7 as they changed the system too much but in general it works for all.

It's been a long time since I installed new to get `No NZB/Torrent providers found or enabled for daily searches and backlog searches. Please check your settings.`
So I installed clean on my spare DSM. Go to `Search Settings` in `NZB` or `Torrent` tab and tick and set one of these. Click `save changes` (I clicked both save buttons) and then go to `Search Providers` and they should show up.

**Comment by BKSteve** [comment]
In the search to find why loading is so slow, mismatch of package parameters is noted on poetry site.
In `pyproject.toml` the packaging allows `>=20.9,<21.0` but poetry 1.1.12 is `>20.4,<21.0` so changing it reduced restart time with the `python -m poetry export -f requirements.txt --without-hashes` to around 20 seconds and less than 30 seconds.

**Comment by ntarocco** [comment]
Thank you for your answer. I have reinstalled Sickchill from scratch and now it works correctly.
