### ISSUE TITLE
Always in status snatched

### ISSUE THREAD

**Issue by Ilocans** [SickChill/SickChill#7842]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: master
OS: Docker on a pi
Browser:
What you did: https://github.com/SickChill/SickChill/wiki/NZBtoMedia
What happened: Episodes are not marked as succeeded or failed they stay on the snatched status
What you expected: Episodes to be marked as succeeded or failed and try to download another one
Logs:
```
[16:56:12] [INFO]::MAIN: The /mnt/Scripts/nzbToMedia/nzbToSickBeard.py script completed successfully.
Changing to directory: /mnt/Scripts/nzbToMedia

-- Cleaning bytecode --
b'Removing __pycache__/\n'
b'Removing __pycache__/\n'

-- Cleaning folders: ['libs', 'core'] --
No folders to clean

Returning to directory:  /usr/local/share/sabnzbdplus

-- Cleanup finished --

SickBeard: Successfully post-processed.....
```
I am using sabnzbd and sickchill together and the status of the download never seem to be updated in sickchill whatever the result is. I double checked the url, port, api key, ...
I don't know what I am missing.

**Comment by BKSteve** [comment]
With `snatched` it means that SC has found something and should have sent it to your downloader.
Has it sent to you downloader? Did it download? Did it go to the right folder for SC to post process?
The log you have is only INFO so when you set DEBUG on make sure to restart SC to enable it and then select debugging in the log drop list instead of INFO.

When download is completed and the file post processed that is when the status changes from `snatched` to `downloaded`

**Comment by miigotu** [comment]
you use sabtonzbd, and then you still need to postprocess the files

**Comment by Ilocans** [comment]
Indeed, I think I was not clear on some point:
The file is detected by sickchill then sent to sabnzb which try to download and post process the file with NZBtoMedia.
The file is downloaded and processed in success or it fails, either way the script is executed but the status does not change in Sickchill

I followed all the step in  https://github.com/SickChill/SickChill/wiki/NZBtoMedia

**Comment by miigotu** [comment]
you need to change your fork in the nzbtomedia config most likely
