### ISSUE TITLE
Wiki install process for raspberry pi points to outdated SickRage repo

### ISSUE THREAD

**Issue by justkamiii** [SickChill/SickChill#7862]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: N/A
OS: N/A
Browser: N/A
What you did: N/A
What happened: N/A
What you expected: N/A
Logs:
```
 N/A
```

The article showcased on the SickChill install wiki (https://www.htpcguides.com/install-sickrage-raspberry-pi-usenet-torrent-tv/ and https://www.algissalys.com/how-to/sickrage-sabnzbd-raspberry-pi-tvpi-part-2) shows the old SickRage repo as the one to clone, which could potentially mislead normal users who don't know about echel0n's sickrage repo into downloading and using it

**Comment by BKSteve** [comment]
The page already had the `IMPORTANT NOTE` below but tweak the guide slightly to mention before going to any particular hardware.

**Comment by BKSteve** [comment]
Now that one of the links is dead and the other is `rage` intensive as you rightly point out. And doing some other wiki page updates soon so considering using the guide of https://www.htpcguides.com/install-sickrage-raspberry-pi-usenet-torrent-tv/ and updating it so want to know is it still valid?
The `git clone` bit could be updated to `pip install` and use `systemctl` instead of `service`
Anything else?
