### ISSUE TITLE
Stuck in state "This show is queued to be refreshed"

### ISSUE THREAD

**Issue by LapinFou** [SickChill/SickChill#7910]
Branch/Commit:  https://github.com/SickChill/SickChill/releases/tag/2022.02.20
OS: Synology NAS (Docker | scr.io/linuxserver/sickchill)
Browser: Firefox

I'm not 100% sure what happen. My guess is:
1- SickChill send to SabNzbd a d/l request.
2- Through NzbToMedia, the downloaded episode has been added in SickChill

Since then, the concerned TV show is displaying this message "_The information on this page is in the process of being updated_".
All other shows are displaying the message "_This show is queued and awaiting an update_".

I tried to restore a few days old backup. The messages were not here anymore. I forced a mass update in order to rescan all files.
Again, this went fine.

But, this morning, the messages were back. 😓

**Comment by LapinFou** [comment]
I restart SickChill and the messages are gone for now. Hower, I wouldn't be surprise to see them re-spawning tomorrow. 😅

**Comment by nydave69** [comment]
> INFO :: MAIN :: 389651: Unable to find IMDb show info in the database

I get a lot of those every reboot..

> All other shows are displaying the message "_This show is queued and awaiting an update_".

I see this very often.....   Check your server status and see if it's hung trying to update shows...
It takes a reboot to clear them..   This is an every day thing for me.

**Comment by LapinFou** [comment]
> > All other shows are displaying the message "_This show is queued and awaiting an update_".
> 
> I see this very often..... Check your server status and see if it's hung trying to update shows... It takes a reboot to clear them.. This is an every day thing for me.
I've been using SickChill for years without any issue. This appeared few days ago. And, yes, it hung when trying to update shows. 😓
I don't know if something has been corrupted in the SickChill database or if it is a bug.
Last solution would be to recreate all the setup from scratch, but this is a lot of work. 😨

**Comment by nydave69** [comment]
I started from scratch,  didn't fix anything..
Also it's not hanging on just one show..  Everyday I have to reboot and the list starts with a different show.
I created a ticket a while back about this issue....

**Comment by BKSteve** [comment]
TheTVDB API often hangs this process and leaves shows with "The information on this page is in the process of being updated"

**Comment by LapinFou** [comment]
> I started from scratch, didn't fix anything.. Also it's not hanging on just one show.. Everyday I have to reboot and the list starts with a different show. I created a ticket a while back about this issue....
No messages yet this morning. 🤞

Which platform are you using with SickChill?
> TheTVDB API often hangs this process and leaves shows with "The information on this page is in the process of being updated" Restart clears the queue

I see. So, the only way workaround is to restart SickChill?

**Comment by BKSteve** [comment]
You can also adjust the hour the daily refresh is done in settings. `When to update shows`

**Comment by LapinFou** [comment]
> You can also adjust the hour the daily refresh is done in settings. `When to update shows`

What would be the goal? To avoid the "peak hour" of all SickChil users?

**Comment by miigotu** [comment]
Avoid peak for all users of thetvdb api

**Comment by LapinFou** [comment]
OK. I will try this solution to find an appropriate update hour.
@miigotu unless restarting SickChill, there is no way to clear the queue when it hangs?

**Comment by miigotu** [comment]
Not currently no. Hopefully someday we get some information that helps us find where exactly it hangs and can find a way to work around it. Or maybe some day I'll get around to removing thetvdb 🤣

**Comment by LapinFou** [comment]
😅
As a workaround, there is no way to add a timeout somewhere?

**Comment by LapinFou** [comment]
Since it is not really a bug and there is no workaround (expected changing the update time), maybe this ticket can be closed?

**Comment by nydave69** [comment]
It's funny that I have other apps that use the TVDB in a similar way and they don't hang..

**Comment by miigotu** [comment]
It's funny that you don't have any other apps that scrape and update information as often in order to provide the functionality that SC does. If it's so funny, just don't use SC.

**Comment by miigotu** [comment]
> Since it is not really a bug and there is no workaround (expected changing the update time), maybe this ticket can be closed?

I'm fine with leaving it open, in hopes that someday we can find a way around tvdb throttling and/or blocking users who have large amounts of show or click refresh/update on shows too often.

**Comment by BKSteve** [comment]
IMO one thing to do is remove all completed and cancelled old series that aren't airing new episodes. That way you reduce your hits on theTVDB API and are less likely to be blocked or throttled and more likely to get the ones that actually require updating

**Comment by LapinFou** [comment]
I tried to setup many different update time, but I still got the problem. 😥
I also tried to reboot my ADSL router (in order to get a new IP), but no joy. The issue is still there.

**Comment by Teamshake** [comment]
> 
Mine was hanging until i got rid of a bunch of canceled shows.  Havent had an issue since.

**Comment by LapinFou** [comment]
Thanks for the tip, unfortunately all my shows are in "Continuing" status.

**Comment by ronrosenfeld** [comment]
FWIW, I run SC on two different platforms (two different locations).  On the Docker (on Synology) platform, things frequently get "stuck" -- so much that I have set a task to restart SC every morning.  

On my Windows platform, I have **never** had it get stuck.  

And I have the same group of shows on both platforms. Also using NZBGet with NZBtoMedia on both platforms.

**Comment by LapinFou** [comment]
Which Docker version are you using? The official one? The LinuxServer one?

**Comment by LapinFou** [comment]
Sorry, I wasn't clear enough. I'm not asking about the Docker version.  I was asking about the SickChill docker Hub. 😅

**Comment by ronrosenfeld** [comment]
It is not the LinuxServer version.  It is the image at `sickchill/sickchill`

**Comment by LapinFou** [comment]
Thanks. I'm using this version → https://hub.docker.com/r/linuxserver/sickchill
You are using this version, correct? → https://hub.docker.com/r/sickchill/sickchill
If yes, it means the issue is out there. 😁

**Comment by ronrosenfeld** [comment]
@LapinFou 
Yes, you are correct so far as my sickchill source.

Also, please check your **server status**.  When I get this error, there are multiple shows listed:

![Untitled](https://user-images.githubusercontent.com/18516066/158575169-1540939e-9ffb-49e2-957c-3329653a6078.png)

**Comment by LapinFou** [comment]
Next time the issue arises, I will check and post a screenshot.

**Comment by miigotu** [comment]
The source doesn't make so much difference as the OS or base image used for the docker image. The SC code is the same no matter where you run it, but we can't control device resources or the OS.

I would imagine some open connections or memory limit is hit and triggers an obscure bug in python.

**Comment by LapinFou** [comment]
Can we enable a DEBUG log somewhere in order to help you to tackle this issue?

For the record, no more issue for the last few days. Fingers crossed! 🤞

**Comment by nydave69** [comment]
Just so everyone knows;     I have not changed a thing since this issue has started, no updates nothing

For the past two mornings the queue has completed correctly...        No reboot required..

anyone got a guess as to why?

**Comment by miigotu** [comment]
Because SC is not the problem.

**Comment by LapinFou** [comment]
Same comment on my side. Everything is working flawless since 1 week.

**Comment by nydave69** [comment]
OK the problem is back....  was a good two days though.....

**Comment by BKSteve** [comment]
I have 202 active shows in my list on my DS412+ v6 and it hasn't failed to update any show in a very long time. 
I did have issues and needed to make sure my firewall was letting theTVDB and related site data through.
Then played with the time and my system scans at 2 (AM) which is actually GMT 17:00 which seems to work best after trying 4, 15, 16 and a bunch of others.

@nydave69 what are you running SC on and how many other things are running?

https://github.com/SickChill/SickChill/issues/7910#issuecomment-1069117853
> I would imagine some open connections or memory limit is hit and triggers an obscure bug in python.

**Comment by ronrosenfeld** [comment]
@BKSteve I'm running SC on a DS718+ using Docker. My "fix" has been to restart SC every morning using cron.

**Comment by nydave69** [comment]
OK,  I'm running on Windows on a dedicated server...   This is a long running setup..
I found and solved my problem....    Everything is running as it should once again.

Shows that had an 's in the title were the problem,  It's part of the issue I reported months ago about extra characters showing up in the Scene Exceptions.

**Comment by miigotu** [comment]
> OK, I'm running on Windows on a dedicated server... This is a long running setup.. I found and solved my problem.... Everything is running as it should once again.
> 
> Shows that had an 's in the title were the problem, It's part of the issue I reported months ago about extra characters showing up in the Scene Exceptions.

If you know the problem is that for sure, please look at the code and find where I can fix it, or provide a patch or pull request.

**Comment by nydave69** [comment]
After running fine for a few weeks the problem is back...   And here is why;

![image](https://user-images.githubusercontent.com/14140816/167845682-713f9d4b-1695-45c7-96c6-6d8c618ca33a.png)
The last line for the show exceptions has that "#39;s" in it.  If that line is used in the update it hangs the queue. like right now.
I had added that new show (to me) 2 days ago.   The problem is that line cannot be edited since it was generated from a file online by SickChill.    Someone needs to look at that code and see why we keep getting that escape sequence instead of the ' that should be there.

**Comment by miigotu** [comment]
Exceptions aren't used in any updates, we only use the tvdbid. That information comes from thetvdb, or IMDb.

Find the problem in code, and submit a pull request.

**Comment by BKSteve** [comment]
What I find interesting @nydave69 is that I've added this show in SC running on SynoDSM it only has one line and no `#39;`
![image](https://user-images.githubusercontent.com/10173496/168201390-678ca8b4-d98a-4fb4-bc39-e18dbcc6e0d2.png)

This `#39` in your list is the decimal code for the `'` character but the regex `re.` filtering on show names removes that when processing and therefore shouldn't exist in the `show` list. This is done in `sickchill/oldbeard/helpers.py`  `def sanitizeSceneName`

**Comment by nydave69** [comment]
> What is the exact name of the folder the series is being stored in?
> I'm wondering if it's a windows things and creating the second grey line from the folder name and when folder name is read the `#39` comes in.

When I create the new show there is no lines in the exceptions..
They show up later and cannot be edited from the GUI..  SickChill adds them from some online source.

And it happens every time the show name has an ' in it..

**Comment by BKSteve** [comment]
> And it happens every time the show name has an ' in it..

That's the issue we need to track down. Why is it happening on your windows machine and not either of my SC installs on DSM or Debian?

**Comment by nydave69** [comment]
I go into the database and edit it out.   I have found that sequence in file names also.
Now that I know I can fix it...

**Comment by BKSteve** [comment]
Well it's a html conversion of the show name or folder done somewhere in the code which throws the `#39;`
A long term fix by tracking down the cause and fixing it in the code is why I was trying to reproduce the same issue.
But I couldn't reproduce it on any of my platforms even installed on Windows 10 but still not able to and it doesn't seem to be coming in from an online source.

So wonder what causes it on your machine? 
It could possibly be some older dependencies or older python code sneaking in. 
How is SC installed on your `dedicated server` and your python 3.8+ too.

**Comment by nydave69** [comment]
I found the following while booting up SickChill watching the command window....
![image](https://user-images.githubusercontent.com/14140816/170478290-fef82d40-227e-4280-b9da-98ccf70c6ecc.png)
![image](https://user-images.githubusercontent.com/14140816/170478561-5e90e197-c5f7-4994-b1c4-99a5f6e6a3d6.png)

these errors do not show in the log,  not sure why since debug is enabled.
this is just one of the errors that I could manually catch.  

This morning the show queue was hung again, but because an exception was thrown trying to get information from the TVDB,
It's an old show that has been loaded in SickChill for years, For some reason the ID could not be found "NoneType"

Only errors in this mornings log is;


2022-05-26 06:21:12 INFO :: POSTPROCESSOR :: Auto post processing task for O:\utorrent\completedDownload\SC was added to the queue
AA AttributeError: 'NoneType' object has no attribute 'id'
AA showObj = Show.find(settings.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\sickchill\oldbeard\helpers.py", line 940, in get_show
AA TypeError: expected string or bytes-like object
AA return _compile(pattern, flags).match(string)
AA File "C:\SickChill\Python3\tools\lib\re.py", line 191, in match
AA if re.match(r"^t?t?\d{7,8}$", name) or re.match(r"^\d{6}$", name):
AA File "C:\SickChill\Python3\tools\Lib\site-packages\sickchill\show\indexers\tvdb.py", line 110, in search
AA result = target(*args, **kwargs)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\sickchill\show\indexers\wrappers.py", line 25, in wrapper
2022-05-26 06:13:25 INFO :: SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Quality of Star.Trek.Strange.New.Worlds.S01E04.1080p.WEB.H264-CAKES[rartv] is 1080p WEB-DL
2022-05-26 06:13:25 INFO :: SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Quality of Star.Trek.Strange.New.Worlds.S01E04.1080p.WEB.H264-CAKES[rartv] is 1080p WEB-DL
2022-05-26 06:13:25 INFO :: SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Quality of The.Flight.Attendant.S02E08.1080p.WEB.H264-CAKES[rartv] is 1080p WEB-DL
2022-05-26 06:13:25 INFO :: SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Quality of The.Flight.Attendant.S02E08.1080p.WEB.H264-CAKES[rartv] is 1080p WEB-DL
AA AttributeError: 'NoneType' object has no attribute 'id'
AA showObj = Show.find(settings.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\sickchill\oldbeard\helpers.py", line 940, in get_show
AA TypeError: expected string or bytes-like object
AA return _compile(pattern, flags).match(string)
AA File "C:\SickChill\Python3\tools\lib\re.py", line 191, in match
AA if re.match(r"^t?t?\d{7,8}$", name) or re.match(r"^\d{6}$", name):
AA File "C:\SickChill\Python3\tools\Lib\site-packages\sickchill\show\indexers\tvdb.py", line 110, in search
AA result = target(*args, **kwargs)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\sickchill\show\indexers\wrappers.py", line 25, in wrapper
2022-05-26 06:13:25 INFO :: SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Found result Star.Trek.Strange.New.Worlds.S01E04.1080p.WEB.H264-CAKES[rartv] at magnet:?xt=urn:btih:3fb0e7343f1752d6d69c095ebc5076710f8eaee6&dn=Star.Trek.Strange.New.Worlds.S01E04.1080p.WEB.H264-CAKES%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2840&tr=udp%3A%2F%2F9.rarbg.to%3A2900&tr=udp%3A%2F%2Ftracker.tallpenguin.org%3A15760&tr=udp%3A%2F%2Ftracker.slowcheetah.org%3A14790
2022-05-26 06:13:25 INFO :: SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Found result Star.Trek.Strange.New.Worlds.S01E04.1080p.WEB.H264-CAKES[rartv] at magnet:?xt=urn:btih:3fb0e7343f1752d6d69c095ebc5076710f8eaee6&dn=Star.Trek.Strange.New.Worlds.S01E04.1080p.WEB.H264-CAKES%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2990&tr=udp%3A%2F%2F9.rarbg.to%3A2980&tr=udp%3A%2F%2Ftracker.tallpenguin.org%3A15710&tr=udp%3A%2F%2Ftracker.slowcheetah.org%3A14800
AA AttributeError: 'NoneType' object has no attribute 'id'
AA showObj = Show.find(settings.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\sickchill\oldbeard\helpers.py", line 940, in get_show
AA TypeError: expected string or bytes-like object
AA return _compile(pattern, flags).match(string)
AA File "C:\SickChill\Python3\tools\lib\re.py", line 191, in match
AA if re.match(r"^t?t?\d{7,8}$", name) or re.match(r"^\d{6}$", name):
AA File "C:\SickChill\Python3\tools\Lib\site-packages\sickchill\show\indexers\tvdb.py", line 110, in search
AA result = target(*args, **kwargs)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\sickchill\show\indexers\wrappers.py", line 25, in wrapper
2022-05-26 06:13:24 INFO :: SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Found result The.Flight.Attendant.S02E08.1080p.WEB.H264-CAKES[rartv] at magnet:?xt=urn:btih:7d700afb06e88058b6aa161a6177432c551f1f48&dn=The.Flight.Attendant.S02E08.1080p.WEB.H264-CAKES%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2800&tr=udp%3A%2F%2F9.rarbg.to%3A2880&tr=udp%3A%2F%2Ftracker.thinelephant.org%3A12740&tr=udp%3A%2F%2Ftracker.fatkhoala.org%3A13740
2022-05-26 06:13:24 INFO :: SEARCHQUEUE-DAILY-SEARCH :: [Rarbg] :: Found result The.Flight.Attendant.S02E08.1080p.WEB.H264-CAKES[rartv] at magnet:?xt=urn:btih:7d700afb06e88058b6aa161a6177432c551f1f48&dn=The.Flight.Attendant.S02E08.1080p.WEB.H264-CAKES%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2750&tr=udp%3A%2F%2F9.rarbg.to%3A2820&tr=udp%3A%2F%2Ftracker.thinelephant.org%3A12780&tr=udp%3A%2F%2Ftracker.fatkhoala.org%3A13770
AA AttributeError: 'NoneType' object has no attribute 'id'
AA showObj = Show.find(settings.showList, sickchill.indexer.search_indexers_for_series_id(name=full_sanitizeSceneName(name))[1].id)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\sickchill\oldbeard\helpers.py", line 940, in get_show
AA TypeError: expected string or bytes-like object
AA return _compile(pattern, flags).match(string)
AA File "C:\SickChill\Python3\tools\lib\re.py", line 191, in match
AA if re.match(r"^t?t?\d{7,8}$", name) or re.match(r"^\d{6}$", name):
AA File "C:\SickChill\Python3\tools\Lib\site-packages\sickchill\show\indexers\tvdb.py", line 110, in search
AA result = target(*args, **kwargs)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\sickchill\show\indexers\wrappers.py", line 25, in wrapper
2022-05-26 06:12:32 INFO :: POSTPROCESSOR-AUTO :: Auto post processing task for O:\utorrent\completedDownload\SC completed



2022-05-26 05:57:59 INFO :: SHOWQUEUE-REFRESH :: Performing refresh on The Enemy Within (2019)
2022-05-26 05:57:51 INFO :: SHOWQUEUE-REFRESH :: Could not find any season_poster images on Fanart.tv for The Worst Witch (1986)
AA requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.thetvdb.com/series/75431/images/query?keyType=season&subKey=4
AA raise HTTPError(http_error_msg, response=self)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\requests\models.py", line 953, in raise_for_status
AA response.raise_for_status()
AA File "C:\SickChill\Python3\tools\Lib\site-packages\tvdbsimple\base.py", line 146, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\tvdbsimple\base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\tvdbsimple\base.py", line 149, in _GET
AA response = self._GET(path, params=filters)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\tvdbsimple\series.py", line 480, in _get_image_type
AA return self._get_image_type('season', language)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\tvdbsimple\series.py", line 425, in season
AA images = getattr(api_results, keyType)(lang or show.lang)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\sickchill\show\indexers\tvdb.py", line 187, in __call_images_api
AA result = target(*args, **kwargs)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\sickchill\show\indexers\wrappers.py", line 25, in wrapper
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA Exception: No results for your query
AA raise Exception(response.json()['Error'])
AA File "C:\SickChill\Python3\tools\Lib\site-packages\tvdbsimple\base.py", line 144, in _request
2022-05-26 05:57:50 INFO :: SHOWQUEUE-REFRESH :: Could not find any season_poster images on Fanart.tv for The Worst Witch (1986)
AA requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.thetvdb.com/series/75431/images/query?keyType=season&subKey=3
AA raise HTTPError(http_error_msg, response=self)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\requests\models.py", line 953, in raise_for_status
AA response.raise_for_status()
AA File "C:\SickChill\Python3\tools\Lib\site-packages\tvdbsimple\base.py", line 146, in _request
AA return self._request(method=method, path=path, params=params, payload=payload, forceNewToken=True)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\tvdbsimple\base.py", line 142, in _request
AA return self._request('GET', path, params=params, cleanJson=cleanJson)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\tvdbsimple\base.py", line 149, in _GET
AA response = self._GET(path, params=filters)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\tvdbsimple\series.py", line 480, in _get_image_type
AA return self._get_image_type('season', language)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\tvdbsimple\series.py", line 425, in season
AA images = getattr(api_results, keyType)(lang or show.lang)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\sickchill\show\indexers\tvdb.py", line 187, in __call_images_api
AA result = target(*args, **kwargs)
AA File "C:\SickChill\Python3\tools\Lib\site-packages\sickchill\show\indexers\wrappers.py", line 25, in wrapper
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA Exception: No results for your query
AA raise Exception(response.json()['Error'])
AA File "C:\SickChill\Python3\tools\Lib\site-packages\tvdbsimple\base.py", line 144, in _request
2022-05-26 05:57:39 INFO :: SHOWQUEUE-REFRESH :: Performing refresh on The Worst Witch (1986)
2022-05-26 05:57:35 INFO :: SHOWQUEUE-FORCE-UPDATE :: 326691: Updating NFOs for show with new indexer info
2022-05-26 05:57:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Performing refresh on Mysteries of the Abandoned (2017)
2022-05-26 05:57:19 INFO :: SHOWQUEUE-FORCE-UPDATE :: Permanently deleting episode 01E07 from the database


But I watched the bootup and hundreds of trapps and other errors were thrown but only the above errors are in the log
Yes I know it's my setup is the problem again, and again I'll rebuild it from scratch something I'm getting really good at since I do it every few months..   Maybe the above information may help someone.

**Comment by BKSteve** [comment]
@nydave69 Can you post the `Help & info > SickChill Configuration` info for interest.

The errors you post are not usual so rather than just reinstall SC and restoring a backup you might want to do a full rebuild of the database too.
Make sure you have tvshow.nfo files in each show folder. (`metadata, kodi`)
Then after you've uninstalled just start fresh and `add existing shows` SC will use the `tvshow.nfo` to collect all the data. If not you have to search for all shows.

As I can't tell if your `config.ini` has any corruption I'd go clean, but you could copy it back and only rebuild the database too.

**Comment by miigotu** [comment]
You need to set the codepage to Unicode on windows. That error you got likely completely kills the show updater thread, so it can't even finish logging.

You can set it on each boot before starting SC with `chcp 65001 && python3 SickChill.py` on the command line, change the codepage to 65001 by changing language settings, or try the steps in this link (probably the best choice if it works):
https://robocorp.com/docs/troubleshooting/windows-codepage

**Comment by nydave69** [comment]
> @nydave69 Can you post the `Help & info > SickChill Configuration` info for interest.

  SickChill Info:
Install: pip
Version: v2022.02.20
Database Version: 44.5

  Python Version:
3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]

  SSL Version:
OpenSSL 1.1.1k 25 Mar 2021

  OS:
Windows-7-6.1.7601-SP1

  Locale:
en_US.cp1252


  User:
Plex

  Program Folder:
C:\SickChill\Python3\tools\Lib\site-packages\sickchill

  Config File:
C:\SickChill\Data\config.ini

  Database File:
C:\SickChill\Data\sickchill.db

  Cache Folder:
C:\SickChill\Data\cache

  Log Folder:
C:\SickChill\Data\Logs

  Executable:
C:\SickChill\Python3\tools\python.exe

  Main Script:
C:\SickChill\Python3\tools\Lib\site-packages\SickChill.py

  Arguments:
--nolaunch --port 8085 --datadir C:\\SickChill\\Data


I'm just curious as to why doesn't the startup of SickChill force the use of UTF-8 if it's required?

**Comment by nydave69** [comment]
> Also, the bad show name exception might very well be coming from your tvshow.nfo or show.xml or whatever metadata file you are using if any.

When I create a new show on SickChill there s no NFO or XML until SickChill creates it...

**Comment by miigotu** [comment]
> > Also, the bad show name exception might very well be coming from your tvshow.nfo or show.xml or whatever metadata file you are using if any.
> 
> When I create a new show on SickChill there s no NFO or XML until SickChill creates it...
> 

That doesn't matter. If there is an encoding error because your machine locale and charmap are not using UTF-8 it's going to create problems everywhere. File names, nfo files, exceptions, notifications, literally everything depends on proper encoding/decoding and the default windows charmap does not translate most special wide characters from unicode.

**Comment by nydave69** [comment]
I tried all the suggestions to set the UTF-8 on this machine, I also googled and found a few others suggestions examples.
It's a widespread problem, I see that they are going to set UTF-8 in python as default in later versions. 
Well SickChill still is showing;
![image](https://user-images.githubusercontent.com/14140816/170826035-118eb24b-79e0-4c4a-952d-cc38cc215d75.png)
Yes I have rebooted the system....

> That doesn't matter. If there is an encoding error because your machine locale and charmap are not using UTF-8 it's going to create problems everywhere. File names, nfo files, exceptions, notifications, literally everything depends on proper encoding/decoding and the default windows charmap does not translate most special wide characters from unicode.

Doesn't this affect all windows machines since they don't use UTF-8 by default?
and this system has been running this way for years..   with SickChill..   just started seeing this problem in the last 6 months.

I'll keep looking for a fix for UTF-8,

**Comment by miigotu** [comment]
It does effect all windows machines, but setting locale is part of the windows guides for SickChill, and has been suggested for years as fixes. Windows updates occasionally make it work, and other times make it screwed up.

One thing I just learned, is that setting locale with PowerShell does not work, you need to use cmd.exe
Try `sc stop SickChill && chcp 65001 && LC_CTYPE=en_US.utf-8 LC_ALL=en_US.utf-8 LANG=en_US.utf-8 SickChill.py` and check the local in the browser.

**Comment by miigotu** [comment]
There is a reason most developers suggest not using windows for server resources, js 🙂
