### ISSUE TITLE
Post Processing Error Anime

### ISSUE THREAD

**Issue by Linden-Ryuujin** [SickChill/SickChill#7978]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Branch/Commit: v2021.07.14-1 
OS: Linux-5.10.28-Unraid-x86_64-with-glibc2.33 
Browser: Firefox
What you did:
Run Post Processing
What happened:
Episode was not parsed correctly
What you expected:
Logs:
```
2022-05-24 07:22:56 DEBUG :: POSTPROCESSOR :: Starting new thread: POSTPROCESSOR
2022-05-24 07:22:56 INFO :: POSTPROCESSOR :: Auto post processing task for /media/Downloads/Bittorrents/_sickchill was added to the queue
2022-05-24 07:22:57 INFO :: POSTPROCESSOR-AUTO :: Beginning auto post processing task: /media/Downloads/Bittorrents/_sickchill
2022-05-24 07:22:57 DEBUG :: POSTPROCESSOR-AUTO :: Processing in folder /media/Downloads/Bittorrents/_sickchill
2022-05-24 07:22:57 INFO :: POSTPROCESSOR-AUTO :: Processing /media/Downloads/Bittorrents/_sickchill
2022-05-24 07:22:57 DEBUG :: POSTPROCESSOR-AUTO :: Processing folder /media/Downloads/Bittorrents/_sickchill
2022-05-24 07:22:57 DEBUG :: POSTPROCESSOR-AUTO :: Could not properly parse a show and episode from [[Judas] One Piece - 1017.mkv]: Unable to match [Judas] One Piece - 1017.mkv to a show in your database. Parser result:  - S10E17 [GROUP: [Judas] One Piece ] [ABD: False] [ANIME: False] [whichReg: ['stupid']] Score: -4
2022-05-24 07:22:57 DEBUG :: POSTPROCESSOR-AUTO :: /media/Downloads/Bittorrents/_sickchill : No processable items found in folder
2022-05-24 07:22:57 INFO :: POSTPROCESSOR-AUTO :: Successfully processed
```

I fixed this locally, but the fix seems so odd that I can't believe that it hasn't been encountered before... so I feel like I must be missing something. I updated the regex for anime_standard to make the "Source_Quality_Etc-" optional (see my updated regex below).
`sickchill\oldbeard\name_parser\regexes.py`
```
(
        "anime_standard",
        # [Group Name] Show Name.13-14
        # [Group Name] Show Name - 13-14
        # Show Name 13-14
        # [Group Name] Show Name.13
        # [Group Name] Show Name - 13
        # Show Name 13
        r"""
     ^(\[(?P<release_group>.+?)\][ ._-]*)?                        # Release Group and separator
     (?P<series_name>.+?)[ ._-]+                                 # Show_Name and separator
     (?P<ep_ab_num>((?!(1080|720|480)[pi])|(?![hx].?26[45]))\d{1,4})                                       # E01
     (-(?P<extra_ab_ep_num>((?!(1080|720|480)[pi])|(?![hx].?26[45]))\d{1,4}))?                             # E02
     (v(?P<version>[0-9]))?                                       # version
     ([ ._-]+\[(?P<extra_info>\d{3,4}[xp]?\d{0,4}[\.\w\s-]*)\])?       # Source_Quality_Etc-
     (\[(?P<crc>\w{8})\])?                                        # CRC
     .*?                                                          # Separator and EOL
     """,
    )
```

**Comment by Linden-Ryuujin** [comment]
I thought I must be missing something as none of the examples appeared to work. As this is down as the anime standard (and it feels like a pretty standard naming convention) it seems really odd no one has spotted it before. Thanks for turning it into a proper pull request!

**Comment by BKSteve** [comment]
I must admit I'd never gone looking as I usually collect seasons and then manipulate with bulkrename and process them in.
Once I changed them to SxxEyy processing happened as 
`374 "anime_SxxExx"`  
389 `([. _-]+((?P<extra_info>.+?))?              # Source_Quality_Etc-`

There's probably a couple of other regexes that need some review, but this one should resolve most.

**Comment by miigotu** [comment]
I'm not sure I'm ok with this change. Source and quality are always present with scene releases. The object of SC goes beyond matching every filename, we want to weed out non-scene releases because most fakes and poor quality releases do not follow scene standards. So if we stick strictly to scene rules, we weed out 99% of bad releases and fakes. This policy is why you rarely see a fake release snatched and processed in SC. Making this change will also affect regular series.

**Comment by miigotu** [comment]
I'll tell you what, I'll allow this change to see what happens. Let's just make a mental note for this in case there are issues that pop up with incorrect parse results or bad/fake releases making it all the way into people's collections so we can revert this if necessary.

**Comment by miigotu** [comment]
Issue with that change: https://github.com/SickChill/SickChill/pull/7981#issuecomment-1140626473

I can help a little with guidance, but I don't have my laptop here atm.

**Comment by Linden-Ryuujin** [comment]
> I'm not sure I'm ok with this change. Source and quality are always present with scene releases.

I had a feeling this might be more complex. The issue for me was that by the time we get here the episode has already been downloaded and gets stuck in post processing with nothing shows up in the log unless you turn on debug. Also none of the examples in code have a quality entry (I copied the optional stuff from the "anime_french_fansub" style) which is why I modified this particular set. With anime most people are white listing their group anyway so they've probably already made the decision about which release they want I would think.

**Comment by BKSteve** [comment]
Closing and shift focus to the pull request #7981

**Comment by Linden-Ryuujin** [comment]
I know this opened a bit of a can of worms but I just wanted to confirm that now this has made it into a release it's fixed my issue. Thanks for all the effort everyone.

**Comment by Linden-Ryuujin** [comment]
Unfortunatly as of v2022.08.22 this is broken again - I'm guessing this was expected, it's broken  by #8098 which I think was a revert to fix larger issues.

**Comment by BKSteve** [comment]
Working on a larger anime processing solution. Branch will link here and hopefully you can assist in testing

**Comment by miigotu** [comment]
I think one way would be to force a different download folder for anime. Then, we can check if we are parsing in the completed anime downloads folder or the shows downloads folder, and compile only those regexes for that post process.

Alternatively, and probably the better choice long term, would be to design a new database, specifically for anime, and migrate the anime out of sickchill.db into the new db. Then, we can split everything away from shows in code. We can use guessit from the get-go, and fix up issues when guessit doesn't get it right later. This makes the code for both anime AND shows much cleaner and easier to maintain. Once we do that, I honestly think anime support in SC would be the best of any software that is freely available anywhere. Right now it is hit or miss and not very much room for improvement. We spam providers with anime requests when we dont need to (like thetvdb, we don't need any information from them for anime at all) We dont need season and episode numbers, just the absolute numbers.

This would allow us to write a front end for anime separately that makes absolute numbering the primary numbering as is convention in anime releases.

Ive said many times, anime is not my thing, but stripping the code out of tv.py and making it modular to where we could duplicate it for cartoons also (instead of trying to stuff cartoons into tv when their convention is also different) feels tasty to me. Everything would be so much cleaner, even if it would be a little more code overall. It would be that much easier to read and follow and maintain.

Once we go through anime, cartoons, daily, sports, documentaries, miniseries, movies, and finally porting shows to that style we could add music and everything. Maybe we can have base classes and specify a `type` of numbering to use, like anime_numbering, or whatever, instead of trying to design 10 databases make the database have a fk relation to a numbering type.

Right now it sucks because no matter what type of release schedule or naming convention or video type we try to force it into SxxExx naming and throw together some arbitrary season and episode that most closely matches. tis not the best waty how echelon did it the first time, and its just a lot of work to undo 10 years of shoehorning a horse cock into an ant eater snout.

**Comment by miigotu** [comment]
Here is what I don't get though:
```python
from sickchill.oldbeard.name_parser import regexes, parser; p = parser.NameParser(); r = p._parse_string("[Judas] One Piece - 1017.mkv"); print(r)
One Piece - S10E17 [ABD: False] [ANIME: False] [whichReg: ['bare']] Score: -6
from sickchill.oldbeard.name_parser import regexes, parser; p = parser.NameParser(parse_method="anime"); r = p._parse_string("[Judas] One Piece - 1017.mkv"); print(r)
One Piece -  [ABS: [1017]] [ANIME VER: 1] [GROUP: Judas] [ABD: False] [ANIME: True] [whichReg: ['anime_bare']] Score: -13
```

This doesn't match a show? That's not what your original log shows so I need to see your logs I guess.

**Comment by miigotu** [comment]
@Linden-Ryuujin why are you using 2022.08.22 and not 2022.8.29?

**Comment by Linden-Ryuujin** [comment]
The log I was getting was the same as when I first started:
```
2022-08-29 22:58:36 INFO :: POSTPROCESSOR-MANUAL :: Beginning manual post processing task: /downloads/Bittorrents/_sickchill
2022-08-29 22:58:36 DEBUG :: POSTPROCESSOR-MANUAL :: Processing in folder /downloads/Bittorrents/_sickchill
2022-08-29 22:58:36 INFO :: POSTPROCESSOR-MANUAL :: Processing /downloads/Bittorrents/_sickchill
2022-08-29 22:58:36 DEBUG :: POSTPROCESSOR-MANUAL :: Processing folder /downloads/Bittorrents/_sickchill
2022-08-29 22:58:36 DEBUG :: POSTPROCESSOR-MANUAL :: Could not properly parse a show and episode from [[Judas] One Piece - 1030.mkv]: Unable to match [Judas] One Piece - 1030.mkv to a show in your database. Parser result:  - S10E30 [GROUP: [Judas] One Piece ] [ABD: False] [ANIME: False] [whichReg: ['stupid']] Score: -4
2022-08-29 22:58:36 DEBUG :: POSTPROCESSOR-MANUAL :: /downloads/Bittorrents/_sickchill : No processable items found in folder
2022-08-29 22:58:36 INFO :: POSTPROCESSOR-MANUAL :: Successfully processed
```

As for the versioning, I guess 2022.08.29 became available between me updating and debugging and then posting here. Do you think the 29 release is likely to fix the issues? I'll update and see how next week goes.

You may well be right about splitting anime out. I'm afraid right now I don't have any time to dig in much beyond very light hacking around to get my own series working (real life is kicking my arse at the moment). I having been thinking that maybe some kind of prelim check based on episodes marked as downloaded could help. Not sure what most of the user base is like but I usually only have 2 or so episodes downloaded at any one time and trying to match against those might make more sense, rather than trying to do a raw match from scratch based on the file name. It seems like something that would have already been considered, so I'm guessing it might cause other issues (or be far more complex).

Anyway thanks again @miigotu I do appreciate the time spent looking at this.

**Comment by miigotu** [comment]
Is `One Piece` in your show list and set as an anime?

**Comment by BKSteve** [comment]
Yes, `One Piece` is in my show list as anime so it processed the snatch, it then saved the file as SxxExx so when doing a file rescan it was throwing the error.

**Comment by Linden-Ryuujin** [comment]
Same for me, it's in my list and marked as anime. Once it picks up the file I don't ever have any issues (it get's move into my release folder with the name S##E##, but that's what I want).

**Comment by miigotu** [comment]
Works on #8124 but Im not sure if I can merge it since I removed the poetry_install garbage lol
