### ISSUE TITLE
Snatched -> Downloaded without post processing

### ISSUE THREAD

**Issue by ncksol** [SickChill/SickChill#8017]
Not really an issue, but a question, as I've not been able to find an answer anywhere. 

My SickChill is setup to drop .torrent files for Deluge to download and afterwards FileBot is taking care of all post processing stuff, so the "post processing" setting in SickChill is turned off. That leaves all the episodes in "Snatched" state forever.

Is there any way to make SickChill automatically change the state? I thought it would do it when it sees the file in the folder that is associated with the show, but no such luck.

**Comment by BKSteve** [comment]
That's how SC is designed. When it processes the downloaded file it renames and puts it in the correct folder and sets the status and quality in the database. 
A manual `re-scan files` should update the status.

**Comment by miigotu** [comment]
You could achieve the goal of retaining the release as it is to continue seeding while also using post processing. Connect directly to deluge (or deluged) and send the files that way. Have an incomplete and a complete folder, on the same drive as your video root. In SC use hard links.

Black hole is a last ditch feature if you can't get a proper connection working because you have some strange setup. It is not recommended at all.

You can seed and have a nice organized and renamed video root without using twice the space this way.
