### ISSUE TITLE
[APP SUBMITTED]: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/sickchill/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000225E3382C40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

### ISSUE THREAD

**Issue by tanjd** [SickChill/SickChill#8053]
### INFO
Python Version: **3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]**
Operating System: **Windows-10-10.0.19044-SP0**
Locale: cp1252
Branch: **pip**
Commit: SickChill/SickChill@2022.7.20
No Log available with ERRORS:
### ERROR
```
Exception generated in thread CHECKVERSION: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/sickchill/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000225E3382C40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```
---
_STAFF NOTIFIED_: @SickChill/owners @SickChill/moderators

**Comment by miigotu** [comment]
This error won't happen anymore soon. The rpartition branch will soon be merged to develop, and then after testing it will be released. That new version will do away with poetry installation every startup, so you won't get shadow banned from pypi because of over-hitting their API causing ddos protection to kick in.
