### ISSUE TITLE
Custom name pattern gives error

### ISSUE THREAD

**Issue by usk78dk** [SickChill/SickChill#8157]
Don't know if this is the right way to address this issue or if I should post another place. If so, please let me know where.

My issue is simply that the following name pattern gives an error (red background in input field) but I can't see any issue with it and the Single-EP Example shows what I expect (Season 02/Show Name S02xE03 Ep Name.ext). the format I try to use is the following;

Season %0S\%SN S%0SxE%0E %EN

**Comment by kyuuk** [comment]
Hello @usk78dk , this would have been better as a discussion, but that's not really a problem. 

first thing, i think you are missing a slash after season folder.
second thing, this pattern is marked as invalid because SickChill won't be able to parse an episode named like that, because of the `x` in `S%0SxE%0E` in the naming conventions it is either `%0Sx%0E` for 02x01or `S%0Sx%0E` for S02E01

i'll close the issue, but feel free to comment again

**Comment by usk78dk** [comment]
@kyuuk Thanks alot. Of course it's the x which was the issue (and shouldn't be in the result I wanted either). How stupid of me. but thanks alot for your help and now all is good ;-)
