### ISSUE TITLE
Cookies and Multiple SickChill Instances

### ISSUE THREAD

**Issue by mannibis** [SickChill/sickchill#8349]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version: [2023.1.2](https://blankrefer.com/?https://github.com/SickChill/SickChill/releases/tag/2023.1.2)
OS: Docker (QNAP)
Browser: Chrome
What you did: Using multiple SickChill instances on same machine (same URL, different webroot)
What happened: Browser forces me to login screen every time I switch between instances
What you expected: To use both instances at same time without re-logging in every time I switch
Logs:
```
PASTE LOGS HERE
```

So I am running 2 SickChill containers, 1 for HD and 1 for UHD content that I keep in separate Plex libraries. This was the only way I figured I could keep multiple qualities. Since I have both instances on the same URL with different webroots via nginx reverse proxy, I am assuming that the sickchill-user cookie is what is causing me to have to log in every time I switch between SickChills. 

Is there any way to put a unique identifier on the cookie so that there can be different cookies for each instance? Or if there is a simpler solution, please advise. Thank you!

**Comment by miigotu** [comment]
Hmm, I think we just set the cookie as sickchill_user, but it is a secure cookie. Can you check that I. The config.ini of both instances under general, that web_cookie_secret is the same and try again? It should allow you to use the same cookie between instances.

**Comment by miigotu** [comment]
Just curious if running just the one version for hd/hevc and then using Plex automatic transcode isn't an option for you? If that was mine it would drive me nuts to have to run 2 versions lol.

**Comment by mannibis** [comment]
> Hmm, I think we just set the cookie as sickchill_user, but it is a secure cookie. Can you check that in the config.ini of both instances under general, that web_cookie_secret is the same and try again? It should allow you to use the same cookie between instances.

I checked both config.ini's (while the containers were running) and they are both different.
web_cookie_secret = XYYKD0o4RMChv22xk0aGu9z7gzGST03ask9WykaDCaY=
web_cookie_secret = ejH3XkYZTGSGNdY6bkHytbTzWcx4JE2pt3pfNY6+mVA=

Is that the expected behavior?

**Comment by miigotu** [comment]
> > Hmm, I think we just set the cookie as sickchill_user, but it is a secure cookie. Can you check that in the config.ini of both instances under general, that web_cookie_secret is the same and try again? It should allow you to use the same cookie between instances.
> 
> I checked both config.ini's (while the containers were running) and they are both different.
> web_cookie_secret = XYYKD0o4RMChv22xk0aGu9z7gzGST03ask9WykaDCaY=
> web_cookie_secret = ejH3XkYZTGSGNdY6bkHytbTzWcx4JE2pt3pfNY6+mVA=
> 
> Is that the expected behavior?
> 
> > Just curious if running just the one version for hd/hevc and then using Plex automatic transcode isn't an option for you? If that was mine it would drive me nuts to have to run 2 versions lol.
> 
> I thought about this for months and this was the best way I could think of. 95% of my plex users don't take advantage of HDR/UHD and I keep separate Plex libraries since not all my content warrants 4K versions. I only do UHD for a specific sets of shows. I know it's a pain but it's mainly for me and 2 other users that actually appreciate UHD/HDR. It's hard enough to get the other users to up their remote quality settings and their internet connections/WiFI would most likely force transcoding anyway with tonemapping and I'd just rather not deal with it

They are both different because a random one is generated when you create a new config.ini. This way, we know your login cookie is safe and secure and unreadable by anyone except sickchill itself.

To accomplish using the same cookie on two instances (on the same base  url), both instances need to be set to the same web_cookie_sectet.

First, since you posted them online, stop both and delete the whole web_cookie_secret line in one of the instances. Start that instance and then shut it down. Copy the new web_cookie_secret from that config.ini and paste it into the config.ini of the other instance and start that instance. 

Now you should have a single NEW web_cookie_secret and it should be the same secret in both config.ini.

Go log into one on the web (your old cookie will be overwritten in the browser when you log in and check `remember me`, since a new secret will have you logged out)

Now go to the other instance and you should already be logged in. F

**Comment by mannibis** [comment]
Awesome, that worked. Thanks miigs. Hope all is well, take care.
