### ISSUE TITLE
[TorrentBytes] :: Unable to connect to provider

### ISSUE THREAD

**Issue by mrsparx** [SickChill/sickchill#8429]
### Before submitting your issue:

Enable debug logging in SickChill settings, reproduce the error (be sure to disable after the bug is fixed)

Version:
Install: [pip](https://anonym.to/?https://pypi.org/project/sickchill/)
Version: [2023.1.2](https://anonym.to/?https://github.com/SickChill/SickChill/releases/tag/2023.1.2)
Database Version: 44.2
OS:
Linux-5.15.79+truenas-x86_64-with
Browser:
Chrome
What you did:
Searching for episodes
What happened:
Login fails. Nothing found.
What you expected:
Something downloaded
Logs:
```
2023-05-03 23:10:14 INFO :: SEARCHQUEUE-MANUAL-266189 :: Unable to find a download for: [Some text changed here...)]
2023-05-03 23:10:14 WARNING :: SEARCHQUEUE-MANUAL-266189 :: [TorrentBytes] :: Unable to connect to provider




AA File "/usr/lib/python3.10/site-packages/sickchill/oldbeard/helpers.py", line 1397, in handle_requests_exception
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.torrentbytes.net', port=443): Max retries exceeded with url: /takelogin.php (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1007)')))
AA raise MaxRetryError(_pool, url, error or ResponseError(cause))
AA File "/usr/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
AA retries = retries.increment(
AA File "/usr/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
AA resp = conn.urlopen(
AA File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 487, in send
AA Traceback (most recent call last):
AA During handling of the above exception, another exception occurred:
AA ssl.SSLError: [SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1007)
AA self._sslobj.do_handshake()
AA File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
AA self.do_handshake()
```

**Comment by miigotu** [comment]
So, there are several things here. The server needs to provide a proper dh key of at least 2048 bits, as well as the other requirements as detailed in these links:

https://weakdh.org/
https://hynek.me/articles/hardening-your-web-servers-ssl-ciphers

This isn't something we changed in sickchill, it's default requirements of python since 2021, I'm assuming torrentbytes either restored a really old backup or someone changed some settings on their server. 
https://github.com/python/cpython/pull/25778

There are workarounds, but it decreases the security and trustability of the sites sickchill is connecting to, because we can't be sure they really are who they say they are if we do.

Some of those potential changes are documented here, as well as documenting the issue: https://stackoverflow.com/questions/38015537/python-requests-exceptions-sslerror-dh-key-too-small

You could try disabling SSL verify and restarting SC to see if the problem goes away. But making a unilateral change to make sickchill less secure is not an option from this side. You could email the site owner and ask them to implement a dh key of greater than or equal to 2048, and provide the links above.

**Comment by mrsparx** [comment]
Alright. Lots of very good information in here. Thank you so much for the detailed answer.
Ill see if there is any possibility to get the site to update their settings.

**Comment by miigotu** [comment]
If you need further support, all support and big reports and everything other than code/releases has been moved to discord. https://discord.gg/7yebVwpntc
